### ISSUE TITLE
Move templates to separate packages

### ISSUE THREAD

**Issue by vladshcherbin** [Meteor-Community-Packages/meteor-autoform#1015]
Now, all the templates come bundled, even if you use only one of them. I use the default ones from bootstrap and the custom ones. So, 70% of templates/styles I don't need. And all of this comes to the client. Lots of users also don't need these templates.

I really would like to use only my custom ones and have no css or extra templates. Is it possible to move the templates to separate packages?

**Comment by dalgard** [comment]
+1
