### ISSUE TITLE
Prevent afFieldInput from generating a label tag?

### ISSUE THREAD

**Issue by fuzzybabybunny** [Meteor-Community-Packages/meteor-autoform#1016]
``` html
{{> afFieldInput class="track-order-change" name="servicesSelected.hdrPhotos.selected" type="boolean-checkbox" noselect="true"}}
```

^^^ this generates the following HTML:

``` html
  <div class="checkbox">
    <label>
      <input type="checkbox" value="true" class="track-order-change" name="servicesSelected.hdrPhotos.selected" data-schema-key="servicesSelected.hdrPhotos.selected">
      My Label That I Defined In The Schema
    </label>
  </div>    
```

Is there a way to have Autoform not create a label tag at all? I need to be able to dynamically generate the label on the front end as well as assign a class to a label. The price for this service changes dynamically and I want the label to look like

 [checkbox] $xx.xx - [the title of the service]

``` html
  <div class="checkbox">
    <label class="bold-if-checked">
      <input type="checkbox" value="true" class="track-order-change" name="servicesSelected.hdrPhotos.selected" title="haha" data-schema-key="servicesSelected.hdrPhotos.selected">
      {{formatToCurrency currentPrice.hdrPhotos}} - {{services.hdrPhotos.title}}
    </label>
  </div>    
```

**Comment by fuzzybabybunny** [comment]
From what I gather, there are severe limitations to generating the label contents.

For ```afFieldInput``` of ```afQuickField```, the contents of their label must be derived programmatically from  the schema, which is very problematic for a variety of reasons.

1. I don't believe that HTML will be rendered if the label string in the schema has any HTML.
2. What if the label requires the values of Session variables or user input that changes dynamically? The schema resides in ```lib``` so it runs on both the client and server, the latter which does not have Session or jQuery.

**Comment by ghaliano** [comment]
With Simple schema:
    type: String,
    autoform: {
      ....
      label: false
    }

**Comment by iSuslov** [comment]
@ghaliano does not work for me..I'm using custom field

**Comment by Roshdy** [comment]
as @ghaliano said, but put it outside the autoform:
..{
    type: String,
    label: false // Or function(){ return false; },
    autoform{
        ...
    }
}

**Comment by JensAttermeyer** [comment]
@Roshdy: For me the problem also exist with your solution. This is my code:

HTML:
`<td>{{> afFieldInput name=this.current.Dispensation}}</td>`

Schema:
`'Products.$.Dispensation': {
    type: Boolean,
    optional: true,
    label: function() {return false},
    autoform: {
      afFieldInput: {
        type: 'boolean-checkbox',
      }
    }
  },`

gerendertes HTML
`    
    <div class="checkbox">
    <label>
      <input value="true" name="Products.0.Dispensation" data-schema-key="Products.0.Dispensation" type="checkbox">
      Dispensation
    </label>
  </div>
  `
Ich hätte gerne nur das input ohne den Text "Dispensation" dahinter. Gibt es da eine Möglichkeit?

**Comment by Roshdy** [comment]
@JensAttermeyer I'm really sorry, I'm spending my honeymoon so I can't help now. I'll get back to you whenever possible

**Comment by kjrhody** [comment]
I'm having some issues with this because I want to customize my checkbox with CSS and need <label> to do so. So I can't have the checkbox generated inside <label>.

I'm pretty new to Meteor so wondered if someone can help me with my syntax. I have tried label: false but I'm not sure that it's in the right place because I get an error.

in helper .js file:

```
Schema.uploadGraphic = new SimpleSchema({

    figReviseYes: {
        type: Boolean,
        label: false,  // this is what generates an error
    }

});
```

in my template file:

```
                        <div id="figCheck" class="checkboxRevise">
                         {{> afFieldInput name="figReviseYes" id="figReviseYes" type="boolean-checkbox"}}
                            <!--<input type="checkbox" id="figReviseYes">-->
                            <label for="figReviseYes"></label>
                        </div>
```
