### ISSUE TITLE
Exclude some required fields from a form

### ISSUE THREAD

**Issue by MaximeWillinger** [Meteor-Community-Packages/meteor-autoform#1025]
Hello,

How can I create an autoForm (with collection attribute) without include all the fields (in particular some required ones).

For example, the following example doesn't work.

**Form :** 

``` html
{{#autoForm collection="myCollection" id="formId" type="method" meteormethod="myMethod"}}

{{/autoForm}}
```

**Schema :** 

``` js
    'createdAt': {
            type: Date,

        }
```

**Error :** 

```
SimpleSchema invalid keys for "formId" context:
{
      name: 'createdAt',
      type: 'required'
}
```

Of course, it works if I add an `optional: true` into my field, but that's not what I want ...
I also tried `autoform.omit`, but it does not change anything.

Thank you for your help,

**Comment by kyooriouskoala** [comment]
@MaximeWillinger 
If you are looking to not show the `createdAt` field to the user even though it is required by the schema, then you would need to pass in the value yourself. 

There's a couple of ways that I've tried which (sort of) work for me: [autoValue] (https://github.com/aldeed/meteor-simple-schema#autovalue) or [Hooks] (https://github.com/aldeed/meteor-autoform#callbackshooks)

**Comment by higgisp** [comment]
I'm not 100% this is the answer you're looking for, but I'm taking a swing.
Without having to use omit in the quickform placeholder this hides the field and set the values at the current date/time and is still required.

```javascript 
createdAt: {
   type: Date,
   optional: false,
   autoform: {
     value: new Date(),
     type: "hidden"
   }
}
```

I threw it into http://autoform.meteor.com/quickform to test it out.
Hope this helps.

**Comment by MaximeWillinger** [comment]
@kyooriouskoala Thank you for your answer! The `autoValue` option seems to be the best way to protect and process an hidden field. @higgisp, I'm not sure that hide a prefilled field is a good security practice... The user can actually change the value, which forces us to re-validate it server-side.

**Comment by dkoo761** [comment]
```javascript
autoform: { type: "hidden" }
```
Brilliant! Don't know how I missed that one.
