### ISSUE TITLE
Make single fields disabled / readonly via schema

### ISSUE THREAD

**Issue by bloigge** [Meteor-Community-Packages/meteor-autoform#1032]
Hi,

Is there a way to disable specific fields via my schema. I am prefilling my collection on the server by getting raw / base data via http requests. Now I want some of the data to be modified by the user, but the rest of the data is not allowed to be modified. I know I could split my form and disable those forms / make them readonly, but I would like to know if there is a way to do that via the schema for specific keys.

Thanks in advance

**Comment by AlexFrazer** [comment]
+1, had this problem myself. Could make it disabled, but not readonly.

**Comment by derwaldgeist** [comment]
+1, also looking for this feature. I would like to use it to set certain fields of a user profile record to readonly, depending on the service with which the user has logged in (e.g. email vs. facebook).

**Comment by aarlaud** [comment]
+1 too.

**Comment by thebarty** [comment]
+1 too

**Comment by saeedjalali1** [comment]
+1 too.

**Comment by AlexFrazer** [comment]
Also, could it be disabled/readonly via a function? Eg:

```
autoform: {
  readonly: function () {
    return this.isUpdate;
  }
}
```

**Comment by ArcaneEngineer** [comment]
+1

**Comment by ghaliano** [comment]
+& too

**Comment by rudza** [comment]
+1

**Comment by rudza** [comment]
I used this attribute to create readonly field: ```autoform: {
      readonly: true
    }```

**Comment by cesarve77** [comment]
+1

**Comment by miri-am** [comment]
+1

**Comment by wilau2** [comment]
+1

**Comment by matadur** [comment]
+1

**Comment by MichaelJCole** [comment]
FWIW:

1) disabled: true works
2) readonly: true didn't work for me, but disabled [is better](http://stackoverflow.com/a/7730719/1483977)

**Comment by maryito** [comment]
+1

**Comment by SiarheiBokuts** [comment]
+1
