### ISSUE TITLE
Broken links from atmospherejs

### ISSUE THREAD

**Issue by ghost** [Meteor-Community-Packages/meteor-autoform#1033]
All the links from the autoform package from atmospherejs has 'blob/master' in it which gives you a 404 when trying to navigate here. 
eg: https://github.com/aldeed/meteor-autoform/blob/master/#a-basic-insert-form
should be:
https://github.com/aldeed/meteor-autoform/#a-basic-insert-form

**Comment by sveinburne** [comment]
+1, same problem here
