### ISSUE TITLE
Update two schema keys from single custom input

### ISSUE THREAD

**Issue by ganySA** [Meteor-Community-Packages/meteor-autoform#1036]
Hi

I have built a custom input control that formats currency e.g 100.50

I would like to save the dollars and cents into different schema values. Currently i am using the valueOut to save the entire value into one field. Is there a means to do this?

Thanks

**Comment by joerodrig3** [comment]
I'm not entirely sure if this would be the best way to do it, but have you tried using a <a href="https://github.com/aldeed/meteor-autoform#callbackshooks">before hook</a>?

```
var currencyHook = {
  before: {
    // Replace `formType` with the form `type` attribute to which this hook applies
    formType: function(doc) {
      // Lets assume the currency(100.50) 
      // is located in doc.currency and it is a String value
      var currency = doc.currency.split(.);
      doc.dollars = currency[0];
      doc.cents = currency[1];

      return doc;  //(synchronous)
      //this.result(doc); (asynchronous)
    }
  }
}
```
That hook would send 3 attributes to whatever method is updating your collection:
doc.currency = 100.50
doc.dollars = 100
doc.cents = 50

**Comment by ganySA** [comment]
thanks will give this a go.
