### ISSUE TITLE
update-pushArray and scope breaks when field name is the same within scoped document

### ISSUE THREAD

**Issue by ganySA** [Meteor-Community-Packages/meteor-autoform#1038]
Hi

I am experiencing a strange problem when using scoped schemas e.g

```
+autoForm collection="Business" doc=currentBusiness scope="services" id="upd-service"     type="update-pushArray"
```

When Parent schema contains the same name field e.g "description" and the pushArray "service" object schema contains the same element name "description" the value on the form is the parent not the scoped value.

```
  +afFieldInput name='description' 
```

Should be "services.$.description" but is showing Business.description (Parent).

Schema looks like:

```
Schemas.Business = new SimpleSchema({
name: {
    type: String,
    label: "Business name",
    max:200
},
description:{
    type:String,
    label: "What does your business do?",
    max:500
},
services:
{
    type:[Object]   
},
"services.$.service":
{
    type: String,
    optional: false,
    max: 100
},
"services.$.description":
{
    type: String,
    optional: false,
    max:200
},
```

**Comment by ganySA** [comment]
Update to this problem:

The data does in fact save properly in the services object. However it seems to "read" description from the parent value as the default value.

So in the below

    +afFieldInput name='description' 

The form is populated initially by "Business.description". When it saves it saves it correctly to Business.services.description - so it is something on initial load.

**Comment by ganySA** [comment]
Additional Info: the following code is where it seems to return the incorrect value.
autoform-inputs.js

getInfoForKey is ignoring the "scope" set, it seems to find the first occurrence of string name.

    getInputValue = function getInputValue(atts, value, mDoc, schemaDefaultValue, fieldDefaultValue, typeDefs) {

      if (typeof value === "undefined") {
       // Get the value for this key in the current document
       if (mDoc) {
         var valueInfo = mDoc.getInfoForKey(atts.name);
         if (valueInfo) {
           value = valueInfo.value;
         } else {
        value = fieldDefaultValue;
      }
    }

**Comment by gdw2** [comment]
I'm seeing this too.

**Comment by sptessier** [comment]
+1

**Comment by felberj** [comment]
did you find a workaround?

**Comment by sptessier** [comment]
None except obviously rename the field to not match the name of a parent field in the schema

**Comment by jimlevett** [comment]
Just to not that I'm also experiencing this

**Comment by khronedev** [comment]
+1 Same problem here

**Comment by soitech** [comment]
+1 Was recently confounded by the validation errors caused by this issue.

**Comment by Mklueh** [comment]
Any news about it?
