### ISSUE TITLE
Array object field store null when remove unordered.

### ISSUE THREAD

**Issue by phanchanra** [Meteor-Community-Packages/meteor-autoform#1049]
Hi sir
i have problem with Array object field when I remove record of embed object unordered, it removes that field but it stores null in `items` filed. how to fix it. 
My Collection
`{
    "_id" : "001-000003",
    "voucherId" : "001-000003",
    "saleDate" : "2015-06-18",
    "staffId" : "001-002",
    "studentId" : "001-000001",
    "items" : [ 
       null, 
        {
            "itemId" : "003",
            "qty" : 1,
            "price" : 10,
            "discount" : 0,
            "amount" : 10
        }
    ],
    "total" : 10,
    "cpanel_branchId" : "001"
}`

**Comment by aldeed** [comment]
Please provide a simple reproduction repo.

**Comment by phanchanra** [comment]
Now I can fix it thank you

**Comment by ofermalbin** [comment]
Happens to me with array of objects that contain 2 elements and then deleting the first element

**Comment by Dagrut** [comment]
Hello,

Here is an example of this bug : 
**test.js**
```js
Collection = new Mongo.Collection("SomeCollection");

function True() {
	return(true);
}
function logDoc(doc) {
	console.log(doc);
}

Collection.allow({
	insert: True,
	update: True,
	remove: True,
});

Collection.find({}).observe({
	added: logDoc,
	changed: logDoc,
});

var schema = new SimpleSchema({
	name: {
		type: [ String ],
		label: "Name",
	},
});

if(Meteor.isServer) {
	Meteor.publish("Collection", function() {
		return Collection.find({});
	});
}
else if(Meteor.isClient) {
	Meteor.subscribe("Collection");
}

Collection.attachSchema(schema);

if(Meteor.isClient) {
	Template.hello.helpers({
		'loadDoc': function() {
			var doc = Collection.findOne({});
			return(doc);
		},
		'haveDoc': function() {
			return(Collection.find({}).count() > 0);
		},
	});
}
```

**test.html**
```html
<body>
	{{> hello}}
</body>

<template name="hello">
	{{#if haveDoc}}
		{{#with loadDoc}}
		{{> quickForm collection="Collection" id="someID0" doc=this type="update"}}
		{{/with}}
	{{else}}
		{{> quickForm collection="Collection" id="someID1" type="insert"}}
	{{/if}}
</template>
```

**.meteor/packages**
```
meteor-platform
aldeed:autoform
aldeed:collection2
```

Try to add three items, submit, remove the middle one, and submit again. You will have a "null" inserted in the array (logged in tty and browser).

**Comment by chmac** [comment]
Just created a reproduction in order to file this very bug, forgetting to check before going through all that hassle! The reproduction is [here](https://github.com/chmac/autoform-remove-field-update/tree/master).

**Comment by chmac** [comment]
Following the code through, it looks like the following query gets passed to the collection's `.update()` method:

```coffee
$set:
  'children.2': 'foo'
$unset:
  'children.0': ''
  'children.1':''
```

The `$unset` part of that doesn't work. It does not remove the two values in the array, either via minimongo on the client or directly via mongo's console either. That's the root cause of this issue I believe.

I guess the issue is that `AutoForm.Utility.reportNulls` returns an object like `children.0: ''` and that is passed directly to `$unset`. In non-array cases, that is the correct modifier, but not in the case of an array. In the case of an array, it looks like the `$pull` operator is required, potentially after the `$unset`. There doesn't seem to be a clean way to remove a single element from an array.

I think in the context of AutoForm, a better solution might be to simply set the value of the entire array, like so:

```coffeescript
$set:
  children: ['a', 'b']
```

I'm not sure how practical it would be to implement that within the current AutoForm architecture though...

**Comment by shactdeveloper** [comment]
I'm having the same issue =(

**Comment by chmac** [comment]
I am working around this issue by adding a `formToDoc` hook and running `_.filter()` over all my array fields. It's a bit of a headache to always remember, but it's certainly less work than implementing our own forms! :-)

**Comment by ChaosKid42** [comment]
@chmac Could you post an example how you work around the issue?

**Comment by chmac** [comment]
@ChaosKid42 Sure thing, here's something along the lines of what I'm doing. Note, this is not copied, so there may be syntax errors, etc...

```coffeescript
AutoForm.addHooks 'formId',
  formToModifier: (modifier) ->
    if modifier.$set.arrayField
      modifier.$set.arrayField = _.compact modifier.$set.arrayField
    modifier
```

Bracket lovers may appreciate [js2.coffee](http://js2.coffee) to convert this into something more brackety...

**Comment by ChaosKid42** [comment]
@chmac Thanks! Works like a charm. Here's my (brackety) code:

```javascript
AutoForm.addHooks(['editPlayerForm'],
{
  formToModifier: function(modifier) {
    if (modifier.$set.comments) {
      modifier.$set.comments = _.compact(modifier.$set.comments);
    }
    return modifier;
  }
});
```

**Comment by ababba15** [comment]
@ChaosKid42 can you please give more info how to use it?

**Comment by jdmswong** [comment]
I'm having this issue too, when values are removed from an autoform generated array field form they are replaced with null values rather than removed from the array

**Comment by ababba15** [comment]
@chmac 's decision works perfectly

**Comment by jflecool2** [comment]
@chmac 's quick fix works for me but I would like a proper fix someday, if someone can manage to track down the bug ... !

**Comment by chmac** [comment]
As far as my reading of the code went, there is no simple fix. The problem is caused by the way that arrays are updated, it's a fundamental architecture thing, because the update query builder doesn't have the original unmodified document, only the requested changes, which makes for an incredibly complex challenge. At least, that's what I remember, we've since moved onto react...

**Comment by marekhattas** [comment]
I definitely decide to move out from autoform package,,,, when i use this fix, another shows up...
(data from one form mess-up with other form from same collection) i just can't use autoform for arrays

**Comment by codeHatcher** [comment]
oh wow, I ended up with a similar issue here https://github.com/orionjs/orion/issues/429 luckily I eventually found this thread which let me in the right direction.

**Comment by asiftyro** [comment]
@chmac it did not workd for me.

```js
AutoForm.addHooks(null, {
  onSuccess: function(operation, result, template) {
    tyroSelectedDoc.set(TYRO_FORM_HIDE_MODE_KEY);
    sAlert.success(centerAlignedPara('Saved Successfully'), {html:true});
},
onError: function(operation, result, template) {
    console.log(operation, new String(result).substring(0, 30)+"...");
    sAlert.error(centerAlignedPara('Could not save'), {html:true});
},
formToModifier: function(modifier) {
    if (modifier.$set.comments) {
      modifier.$set.comments = _.compact(modifier.$set.comments);
  }
  return modifier;
}
});
```

**Comment by chmac** [comment]
@asiftyro We've long since moved to react and left autoform behind. At a glance / guess I'd say you probably don't want to be passing `null` as the first parameter, but I could well be wrong. I don't remember much about those old days anymore... :-)

**Comment by abate** [comment]
I've just hit this problem. thank you for the work around.

**Comment by prafful-panwar** [comment]
` foreach ($event->volunteers as $key => $volunteer) {
                if ($volunteer['user_id'] == $userId) {
                    $event->where('volunteers.user_id', intval($userId))
                        ->unset("volunteers.$key");
                }
            }`

Facing the same issue, can anyone help me around. After unset its replacing array with null.
