### ISSUE TITLE
Nested schemas won't validate

### ISSUE THREAD

**Issue by Framnk** [Meteor-Community-Packages/meteor-autoform#1055]
I'm trying to create an autoform using a schema which has a nested schema as a field.  This seems to work alright and I can render form fields for the nested schema type using the 'field.value' syntax, i.e:

{{> afQuickField name='nestedschema.name' }}

However, although this works, the form validation seems to ignore any fields marked as 'required' when doing the validation.  I even tried manually validating the field in question in a javascript event and asking the form to validate the specific field using the 'field.value' syntax still does not cause validation to occur on the form.

Any ideas?

**Comment by wojtek-krysiak** [comment]
Hi, 

I had the same problem. Solved this by defining "nestedschema" as an object (without it form doesn't validate nested fields as you described)

```
new SimpleSchema({
    nestedschema: {
        type: Object
    } ,
    "testedschema.name": {
        require: true
    }
});
