### ISSUE TITLE
Can I have a different label for adding an item to an array?

### ISSUE THREAD

**Issue by ndarilek** [Meteor-Community-Packages/meteor-autoform#1070]
I have this:

  "profile.sshKeys":
    type: [Object]
    label: "SSH keys"
    minCount: 0
    autoform:
      initialCount: 0
  "profile.sshKeys.$.name":
    type: String
  "profile.sshKeys.$.key":
    type: String

The form for this includes an "SSH keys" label, which is fine. But the add form for a new key includes `<h3>SSH keys</h3>`, which is a bit strange to see above the form for a new key.

Is there a way to distinguish between the section name of what a thing is called, and the form to add a new thing? I'd like to individually tweak the add form label, maybe something like:

  "profile.sshKeys":
    type: [Object]
    label: "SSH keys"
    minCount: 0
    autoform:
      initialCount: 0
      addLabel: "New SSH key"

This would only be set on array keys where there is both a list of items and a form to add a new item. Is something like this already possible and I've just missed it? I've been over the docs several times, but I'm also routinely reading the simple-schema and other docs so my head is a bit jumbled. :)

**Comment by aldeed** [comment]
It might work to set that as the `label` of `profile.sshKeys.$` in the schema. (Which would have type `Object` and you'd change the `profile.sshKeys` type to `Array`.)

**Comment by ndarilek** [comment]
I have the following, which has the exact same output:

  "profile.sshKeys":
    type: Array
    label: "SSH keys"
    minCount: 1
  "profile.sshKeys.$":
    type: Object
    label: "New SSH key"

Thanks.

**Comment by aniskhan001** [comment]
I would also like to have this option. But unfortunately setting a `label` to the Array (`profile.sshKeys` in this case) doesn't respect the label of item level (`profile.sshKeys.$ `). Both are labeled same with the above snippet.
