### ISSUE TITLE
Date field always shows as required

### ISSUE THREAD

**Issue by ndarilek** [Meteor-Community-Packages/meteor-autoform#1071]
Maybe I'm missing something in the docs. I have a SimpleSchema with a Date type. No matter what I type into this field, it always shows up as required. This is on Firefox 38.

I've created a (sample project)[https://github.com/ndarilek/autoform-date) that exhibits the behavior. Even if I do `new Date()` and copy the string representation into the form, it does not validate. Further, if my formatting was bad, I'd expect an error telling me I've submitted a bad date, not one stating that the field is required. In another project I've also attempted this with type=datetime but with no different results. Am I missing something?

Thanks.

**Comment by ndarilek** [comment]
OK, did a bit more digging. Basically, if the date isn't an ISO string, then the conversion fails. I was trying to pass the date directly into .val(). I was able to pass the string into the Date constructor and get a valid date, so it seems like there's no definitive reason this wouldn't work, only the ISO string was chosen as the representative format for dates. I didn't see this in the docs but there is quite a bit there so I might have missed it.

I don't know what the best solution is. Maybe the format can be loosened with a note to take extra care to validate dates on submission? Definitely lost lots of time chasing this one down, so a bit fewer restrictions might be helpful.

Thanks.

**Comment by bshamblen** [comment]
+1 Only ISO formatted date string is being accepted for me. If i enter any other value in the field, even a valid javascript date string like `7/10/2015`, since the field is optional in my schema the value is just discarded and no error is displayed.

**Comment by Adiel-Sharabi** [comment]
+1
