### ISSUE TITLE
adjustment function 

### ISSUE THREAD

**Issue by pociej** [Meteor-Community-Packages/meteor-autoform#1072]
HI @aldeed , 

for now when form is of the type 'disabled' or 'readonly' all the fields are disabled/readonly. As in title, imo it is good idea to allow adjustment function which will decide which fields should be disabled/readonly as autoForm argument . Im open to do that and PR. Thoughts ?

**Comment by bloigge** [comment]
I have the same problem (see [#1032] (https://github.com/aldeed/meteor-autoform/issues/1032)) - would be nice to set this via the schema

**Comment by pociej** [comment]
@bloigge , i have it working for my internal usage . Only thing i have to finish is submit functions. By default disable/readonly forms arent submited (https://github.com/aldeed/meteor-autoform/blob/devel/formTypes/readonly.js#L3) . I needed standard submit behavior. I think we should give user possibility to decide  if read-only field should be submitted or not . Thoughts ?

**Comment by bloigge** [comment]
Hi @pociej , 

I solved my issue by adding $('[name="myAttribute"]').attr("disabled", true)" in Template.myTemplate.rendered for each field that I don't want to be edited. 

I think the best generic way would be to this via the schema or to add an attribute readOnlyFields (like omitFields) to afQuickField. What do you think is the better way - any other solution maybe?

I am pretty new to Javascript and Meteor - but I would like to help. Any hint how to start?
