### ISSUE TITLE
Custom checkbox templates, {atts} has no id

### ISSUE THREAD

**Issue by paulisloud** [Meteor-Community-Packages/meteor-autoform#1074]
Hello, I'm having trouble getting my custom checkbox to work, because the checkbox label has no 'for' attribute when rendered, because {{atts}} has no ID.

In my #autoForm template:

`{{> afFieldInput name='doJournal'}}`

Then I created the template I want to use:
`<template name="afCheckbox_mCheckbox">
  <div><input type="checkbox" class="filled-in" {{atts}} /> <label for="{{atts.id}}">{{afFieldLabelText name=this.name}}</label></div>
</template>`

In my JS I have:
`AutoForm.setDefaultTemplateForType('afCheckbox', 'mCheckbox');`

`Template.afCheckbox_mCheckbox.onRendered(function() {
    m = Template.currentData();
    console.log('current data', m);
});`

And the result of the console log: 

atts: Object: data-schema-key: "doMaxMinAvg" name: "doMaxMinAvg

So as you can see, there is no ID in {{atts}} for this template

Is this a bug or something I'm not doing properly?

**Comment by boustanihani** [comment]
I am also experiencing missing IDs when defining custom input types...

**Comment by shactdeveloper** [comment]
+1

**Comment by pihyper** [comment]
+1
