### ISSUE TITLE
Update user profile clears entire "profile" property when using omitFields

### ISSUE THREAD

**Issue by bshamblen** [Meteor-Community-Packages/meteor-autoform#1078]
I currently have a template that allows a user to update their profile, just like every other Meteor app out there. The user's profile information is stored in a sub-object of the Meteor.users schema, called `profile`. Within this particular form I'm omitting several fields, because I don't want users to have direct access to edit the values (profile image url and screen name).

**HTML file:**

```
<template name="settingsProfile">
    {{#autoForm collection='Meteor.users' doc=user type='update' id='profileUpdateForm'}}
        {{> afQuickField name='profile' omitFields='profile.screenName,profile.image'}}
        <button type='submit' class="btn btn-primary">Save profile</button>
    {{/autoForm}}
</template>
```

**JS file:**

```
Template.settingsProfile.helpers({
    user: function() {
        return Meteor.user();
    }
});

AutoForm.hooks({
    profileUpdateForm: {
        after:  {
            update: function() {
                Router.go('/home');
            }
        }
    }
});
```

I have separate templates to allow the user to upload a profile photo and create their screen name. 

Even though the schema for the `profile` property has these additional fields defined, and I've omitted them from the form, if I remove all of the values from the form and click the save button autoform will completely wipe out the entire `profile` property, which deletes their screen name and profile photo url.
## Steps to reproduce:
1. Navigate to the page containing this template.
2. Set a value for any of the fields with the profile. For example, enter "Bob" in the first name field.
3. Click the save button. This should save your changes and redirect you to the "/home" path.
4. Go to the profile photo page, upload an image, which sets the `profile.image` property after the image is uploaded and resized.
5. Navigate back to the page containing this template. The values entered in step 2 should be displayed.
6. Remove **all** of the values on this form and click save. Even though I'm telling the form to omit the `profile.image` property from the list of fields the code will '$unset` the entire 'profile' property, even though it currently contains a value in one of the omitted fields.

Is there a way to prevent this behavior?

**Comment by jholl** [comment]
+1 ; like #992
