### ISSUE TITLE
Error "Maximum call stack size exceeded" occurs when doc attribute of autoform is static string

### ISSUE THREAD

**Issue by ravish-tech** [Meteor-Community-Packages/meteor-autoform#1084]
Consider the below:
{{#autoForm collection="Fooditem" id="fooditemForm" type="update" doc="xyz"}}

This generates the below error. "xyz" is not defined in template helpers.
Replacing "xyz" with docDataProvider without quotes and defining docDataProvider in helpers solves the issue.

Uncaught RangeError: Maximum call stack size exceeded
All the calls are within file mongo-object.js (152, 164)

**Comment by ethanwillis** [comment]
I also get this error with a similar example

**Comment by Amritpd** [comment]
This happens because the doc attribute expects an object. It works using a helper because autoform assumes the object that is returned is the _id of the document you want to update. In general, the doc attribute takes an object as a parameter, and looks for the _id key within that object.
