### ISSUE TITLE
Update form flickers when submitting

### ISSUE THREAD

**Issue by mazing** [Meteor-Community-Packages/meteor-autoform#1087]
When I submit the update form on http://autoform.meteor.com/updateaf, the form flickers (disappears and reappears). Is it possible to disable this flickering and instead just make the update and keep the form appearing even after submitting the form?

Besides, it scrolls to top on the page when it is submitted which confuses the user. Am I using it wrong when I use

```
{{> quickForm collection="Meteor.users" id="updateForm" type="update" fields="profile.firstName,profile.lastName" doc=user}}
```

since it flickers and scrolls to top?

**Comment by abernix** [comment]
I'm guessing this is related to #846.  I'm having the same problem.  The form is actually removed and re-drawn in the page when it's updated.
