### ISSUE TITLE
Problems with afQuickFields

### ISSUE THREAD

**Issue by mazing** [Meteor-Community-Packages/meteor-autoform#1089]
I cannot get `afQuickFields` to work when it's used in this:

```
{{#autoForm id="createForm" collection="CollectionName" type="method" meteormethod="createElement"}}
  {{> afQuickFields}}
{{/autoForm}}
```

however, it works with

```
{{#autoForm id="updateForm" collection="CollectionName" type="update" doc=this}}
  {{> afQuickFields}}
{{/autoForm}}
```

Instead of `afQuickFields`, I can use

```
{{#autoForm id="createForm" collection="CollectionName" type="method" meteormethod="createElement"}}
  {{#each afFieldNames}}
    {{> afQuickField name=this.name options="auto"}}
  {{/each}}
{{/autoForm}}
```

On http://autoform.meteor.com/qfdetails it says that I should use `{{> afQuickField name=this}}` but `this` prints an object, whereas `this.name` prints the field name.

Am I doing something wrong?

**Comment by dkoo761** [comment]
afQuickFields is also not working for me either. It works on an empty form but not on a form where I'm passing in a data context as the doc.

Here's the autoform definition:

```javascript
{{#autoForm id="edit-role" schema=schema doc=this type="method" meteormethod="/roles/edit"}}
    {{> afQuickFields}}
    <div>
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-default cancel">Cancel</button>
    </div>
{{/autoForm}}
```

Here's the doc:

```javascript
{
    "_id": "F5L5FpwcfQQC3Diot",
    "name": "Test Field Name 123",
    "permissions": [],
    "createdByUserId": "3evB33kYpoXtstuQu",
    "createdAt": "2015-07-15T09:09:41.000Z",
    "updatedAt": "2015-07-16T01:42:41.877Z",
    "updatedByUserId": "3evB33kYpoXtstuQu"
}
```

And here's the error I get:

Exception in template helper: Error: Invalid field name: Test Field Name 123
    at Object.getDefs (http://localhost:3000/packages/aldeed_autoform.js?18753a6e473154133a9c53abf993a65ddd0c01da:257:13)
    at parseOptions (http://localhost:3000/packages/aldeed_autoform.js?18753a6e473154133a9c53abf993a65ddd0c01da:1247:22)
    at Object.autoFormFieldNames (http://localhost:3000/packages/aldeed_autoform.js?18753a6e473154133a9c53abf993a65ddd0c01da:1358:13)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:172:18)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)

If I use the following quickForm it works fine but I need the Save & Cancel buttons:

{{> quickForm id="edit-role" schema=schema doc=this type="method" meteormethod="/roles/edit"}}

For now I am using the quickForm and manually adding the Cancel button via jQuery. Ugly but it's a temporary quick fix for now.
