### ISSUE TITLE
Custom Input Types + $unset

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#1091]
I have a custom `url` input type to automatically add `http://` to URLs if it's missing. It looks something like this:

``` js
AutoForm.addInputType("bootstrap-url", {
  template: "afBootstrapUrl",
  valueOut: function () {
    var url = this.val();
    if (!!url) {
      // add http:// if missing
      if (url.substring(0, 7) !== "http://" && url.substring(0, 8) !== "https://") {
        url = "http://"+url;
      }
      return url;
    }
  }
});

Template.afBootstrapUrl_bootstrap3.helpers({
  atts: function addFormControlAtts() {
    var atts = _.clone(this.atts);
    // Add bootstrap class
    atts = AutoForm.Utility.addClass(atts, "form-control");
    return atts;
  }
});
```

My problem is that when the field is left empty, the field is added to neither the `$set` or `$unset` modifier. Which means it's effectively impossible to clear the field. 

What am I doing wrong?

**Comment by serkandurusoy** [comment]
+1 I'm being bitten by this as well. Furthermore, if there are other autovalue's that this.unset() based on other fields' values, they are not getting applied and are getting set anyways.

**Comment by Matthew-Heaphy** [comment]
In order to clear the field return null.
