### ISSUE TITLE
Customize template for input field

### ISSUE THREAD

**Issue by mazing** [Meteor-Community-Packages/meteor-autoform#1095]
I have created a template

```
<template name="afArrayField_customRows">
  ...
</template>
```

which is a customization of https://github.com/aldeed/meteor-autoform/blob/devel/templates/bootstrap3/components/afArrayField/afArrayField.html

I thought I could just swap this component template with my new template with

```
{{> afQuickField name="rows" template="afArrayField_customRows"}}
```

but it seems I can only swap the entire form template and not just this field's template.

How should this be done correctly? Do I have to create a new input type if I just want a slightly modified version of https://github.com/aldeed/meteor-autoform/blob/devel/templates/bootstrap3/components/afArrayField/afArrayField.html ?

**Comment by jholl** [comment]
I think the template name only needs to be 'customRows'  not the actual template name, just the part after the component name.

**Comment by aaronjudd** [comment]
this is correct: `template name="afArrayField_customRows"`
but the param on the field needs to be  `{{... Template="customRows"}}`
