### ISSUE TITLE
Name undefined for nested schema field in array object

### ISSUE THREAD

**Issue by sam-dieck** [Meteor-Community-Packages/meteor-autoform#1096]
Consider the following schemas were we have an schema that contains an array of another schema that contains a nested schema.

```
NestedSchema = new SimpleSchema({
    field1: {
        type: Number
    }
});

Schema2 = new SimpleSchema({
    NormalField: {
        type: String
    },
    NestedField: {
        type: NestedSchema
    }
});

Schema1 = new SimpleSchema({
    Array: {
        type: [Schema2],
    }
});
```

Now, in a template, I would expect to be able to render the "Nested" fields inside every array object as follows:

```
{{# afEachArrayItem name="Array" }}
    {{> afFieldInput name=this.current.NormalField }} <----- This works fine!
    {{> afFieldInput name=this.current.NestedField.field1 }} <----- This does not work!
{{/afEachArrayItem}}
```

If I  manually hard code the following:

```
{{> afFieldInput name="Array.0.NestedField.field1" }}
```

it correctly displays the input box for the first array element, which is evidence of a problem with "this.current" for nested fields.

In general, I can correctly access normal fields of every array element, but I cannot access nested field elements. Is this a bug? or is there another way of doing this? It looks to me that this should be the most natural way and the most obvious way of doing it given that it's the way to do it for normal fields.

Thanks

**Comment by solace** [comment]
+1 Have this problem as well.

**Comment by TimoRuetten** [comment]
+1 Same here. Sadly it seems that this package is not maintained anymore so dont know if there will be a official fix.

**Comment by alexandrzavalii** [comment]
+1 same  :(

**Comment by vkku** [comment]
+1: 
I also have same problem with schema :
coordsSchema = new SimpleSchema({
  XCoordinate: {
  	label: "X - Coordinate",
    type: String,
    max: 100
  },
  YCoordinate: {
  	label: "Y - Coordinate",
    type: String,
    max: 100
  },
});
And accessing it like :
X - Coordinate: {{ coords.XCoordinate }} <br/>
in *.html file
