### ISSUE TITLE
quickField within custom template does not inherit template default

### ISSUE THREAD

**Issue by jholl** [Meteor-Community-Packages/meteor-autoform#1102]
if I create a custom template `afArrayField_addresses` and call that in an autoForm.  Then within that template I may use `quickField` for each of the array fields.  Those `quickField`s do not inherit the default template, thus the template-specific `inputType`.  I notice this, because I'm initiating a dropdown within custom select input `afSelect_semanticUI` and although my default template is set to semanticUI, a plain/text afSelect template is rendered.  I'm guessing this has to do with a conflict started by the initial declaration of `template=addresses`, and I can work around by explicitly adding `template=semanticUI` to each of the `quickField` within the `afArrayField` ... but I'd rather it use the default and avoid the extra markup.

**Comment by aaronjudd** [comment]
I'm not sure if this is the same issue as I experienced.. but I had to use:

```
Template.afFormGroup_customTemplate.helpers
  afFieldInputAtts: ->
    return _.extend { template: 'bootstrap3' }, @afFieldInputAtts

````
To apply the defaults class to the inputs.
