### ISSUE TITLE
File path from Blueimp uploader to field in Autoform

### ISSUE THREAD

**Issue by filipblaauw** [Meteor-Community-Packages/meteor-autoform#1103]
This might be an odd request, but I'm hoping someone will have any inputs on this.

I have a basic CRUD-list made with Autoforms, similar to this: http://scotchio-meteor-car.meteor.com/cars/create

On the "Create" page, I've included the [Blueimp Bootstrap uploader](https://github.com/tomitrescak/meteor-uploads). So far, I'm able to upload images to users directories with unique names. Inside Meteor.startup function, I call the path of the uploaded image:

```
finished: function(fileInfo) {
    console.log(fileInfo.path);
}
```

This gives me the path for the image: Username/1437779550615_image.jpg

How can I send this path to one of my Schema-fields? As far as I can see, the fileInfo.path is only available on server-side. I want to pass it to something like this. This is defined in a client-side js:

```
uploadedImage: {
    type: String,
    autoValue: function() {
        return fileInfo.path
    }
}
```

This is my first attempt of a Meteor-app, so I'm a bit confused over the file structure and where different scripts are available. I would be very happy if someone has some input on this!

**Comment by jimmiebtlr** [comment]
If you want to display it on the form you'll need to get it back from the server somehow.  For this you'll probably use a Meteor.method.  Autoform offers some async support, but you'll have to read the docs on that.
