### ISSUE TITLE
Display custom schema field

### ISSUE THREAD

**Issue by Christilut** [Meteor-Community-Packages/meteor-autoform#1104]
I can't figure out how to do this. Let's say I have this schema:  

``` coffeescript
MyCollection.attachSchema new SimpleSchema
    title: {
      type: String,
      label: "Title",
      max: 200
      explanation: 'this explains the input'
    }
```

How can I show the explanation field in my html?  
I've already added

``` coffeescript
SimpleSchema.extendOptions
  explanation: Match.Optional String
```

so simple-schema is okay with this. But I simply can't figure out how to show the data in the html.

**Comment by abecks** [comment]
I dont believe the built in field types have support for "explanation".

https://github.com/aldeed/meteor-autoform/blob/8544c659ea5235bbbc9f737e170d405c11e23cac/templates/bootstrap3/components/afFormGroup/afFormGroup.html

Is the container for most of the fields that are rendered. It renders a label, the element, and a help-block for displaying the error message. That help block is not used for an explanation, only validation messages. However, you could extend AutoForm and add your own inputs that make use of this schema property.

See:
https://github.com/aldeed/meteor-autoform#defining-custom-input-types
