### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by chrisbutler** [Meteor-Community-Packages/meteor-autoform#1107]
Hey Eric,

I watched the Q&A with Josh and I was already thinking of volunteering when you mentioned having more contributors, helpers, etc.

I figured I'd create a place to talk about that, and I'd love to be able to help/give back/learn more about the internals of the package(s).

Let me know what, if anything, I can do... and hopefully others looking to contribute will chime in as well

**Comment by mordra** [comment]
This is something I've been thinking about as well, seeing the 200 odd open issues on the repo, but being pretty new to meteor and github, I'll be limited to pointing newbies in the right direction.
I'm watching the repo now and will try to answer questions here and on the forums when I can.
Keep up the great work!

**Comment by jimmiebtlr** [comment]
Maybe a good area to contribute to would be in the tests.  This would help us get more familiar with the internals, and I'm honestly always worried contributing code to another persons repository if it doesn't have solid test coverage.

**Comment by abecks** [comment]
I would agree on the tests. Only a few unit tests are present right now. I don't know if @aldeed wants to bring in some sort of end-to-end testing like Cucumber via Velocity (maybe based on the demo), but we definitely need something.

The reactivity and complexity of AutoForm can also be very difficult to understand at first. I was thinking it might be helpful to have some sort of flow chart/diagram that illustrates the package flow. Even though I've done a few PR's already, I still get very confused when trying to debug the reactivity of the components (especially afArrayField).

**Comment by jimmiebtlr** [comment]
I like the idea of using the direct package testing that is available via `sanjo:jasmine` at the moment.

    https://velocity.readme.io/v1.0/docs/jasmine-testing-a-meteor-package

**Comment by abecks** [comment]
Can we use webdriverio with jasmine? I've only been using it with cucumber
via Velocity so far.

Think you could throw together an example with autoform to get us started?

**Comment by jimmiebtlr** [comment]
Started on an example, probably shouldn't have picked a known bug though.  Result tests don't pass, but it will reactively run jasmine tests.

https://github.com/aldeed/meteor-autoform/compare/devel...jimmiebtlr:devel

Let me know what you think.
