### ISSUE TITLE
Question on calling function to get values from database for a Select control (drop down box)

### ISSUE THREAD

**Issue by wesyah234** [Meteor-Community-Packages/meteor-autoform#1110]
With the following schema, see that I'm doing a .find on the ChartDictionary for 2 different select controls, chartStatus and location. This is the recommended way of doing it based on much internet searching and research.

```
Chart.attachSchema(new SimpleSchema({
  demographics: {
    type: Object,
  }
  , 'demographics.chartStatus': {
    type: String,
    label: "Chart Status",
    autoform: {
      options: function () {
        var options = ChartDictionary.find({"lookup_type": "chartStatus"}, {sort: {"lookup_label": 1}}).map(function (c) {
          return {label: c.lookup_label, value: c.lookup_id};
        });
        console.log("getting chart status options found: " + options.length);
        return options;
      }
    }
  }
  , 'demographics.location': {
    type: String,
    label: "Location",
    autoform: {
      options: function () {
        var options = ChartDictionary.find({"lookup_type": "clinicLocation"}, {sort: {"lookup_label": 1}}).map(function (c) {
          return {label: c.lookup_label, value: c.lookup_id};
        });
        console.log("getting clinic locations options found " + options.length);
        return options;
      }
    }
  }
```

When I visit a route that displays the autoform, I see my console.log messages , but they are running an extreme number of times, and I'm confused as to why.  There seems to be something off.  It seems to be trying to .find the options but not getting them all at first, as the first ones show the number found to be 0, then next it shows a few more, and finally, the last one, shows 17 chart status found and 8 clinic locations found, which is the full amount.  Is there something wrong with the subscription... do I need to get it to wait for the subscription or something like that?  

See image below for the output of the browser console.  (this is what shows when the app reloads after a code change)
![screen shot 2015-07-29 at 11 31 07 am](https://cloud.githubusercontent.com/assets/66566/8963428/add8112a-35e5-11e5-9754-9c5ee4843cca.jpg)

**Comment by wesyah234** [comment]
I have put together a repo to demonstrate this.  Seems that it runs 4 times consistently. https://github.com/wesyah234/quickFormDemo/tree/28ed72b6f6d197bcf4077883f17ca577c82feb12

Some discussion has gone on at the forums on this:
https://forums.meteor.com/t/strange-behavior-when-using-a-function-with-autoform-simpleschema-to-pull-values-for-a-select-control/7669

One comment was "don't do expensive stuff in the autoform options function", but I am concerned about that, since my use case dictates that I need to be able to populate autoform select options from a Mongo collection.  (I would think this would be a common use case)

They thought I should address it with you directly here.

Thanks for looking!

**Comment by mordra** [comment]
Looks related to this issue: https://github.com/aldeed/meteor-autoform/issues/757#issuecomment-78297853

**Comment by aldeed** [comment]
Blaze in general can rerun stuff a lot, and there are likely some optimizations to be done in AF, too.

As for optimizing this specific case, ideally you don't display the template that contains the form until all the subs it needs are ready. Next best would be something like this at the top of each options function:

```js
if (! ChartDictionarySubscription.ready()) return;
```

**Comment by wesyah234** [comment]
ok, thanks...
