### ISSUE TITLE
Does Autoform work with select2/allowed Values?

### ISSUE THREAD

**Issue by victorhooi** [Meteor-Community-Packages/meteor-autoform#1113]
NB: This is probably a question.

I'm trying to use Autoform to provide an update form for a document, where the document in question is set based on a Meteor Session variable:

I have a template helper like so:

```
    Template.ratings.helpers({
        currentSport: function () {
            var currentSport = Session.get('currentSport')
            return Rating.findOne(currentSport);
        }
    });
```

Then my update form template:

```
<template name="updateRating">
    {{> quickForm collection="Ratings" doc=currentSport id="updateRatingForm" type="update"}}
</template>
```

For some reason, this just seems to produce a generic Add Autoform with a Submit button.

When I change the session variable (via a dropdown), the Autoform doesn't update, nor doe the Submit do anything.

Any ideas on what's going on?

**Comment by victorhooi** [comment]
Hmm, well, this is odd - I managed to get `quickForm` working, but not `AutoForm`. For the `Autoform`, all the String fields are blank, and when you go to set them, it says `No results found`:

![screenshot 2015-08-01 14 52 27](https://cloud.githubusercontent.com/assets/243499/9020655/f771c3c0-385c-11e5-8e5e-0ea224ba24e9.png)

These are my template helpers:

```
    Template.updateRating.helpers({
        currentSport: function () {
            return Ratings.findOne(Session.get('currentSport'));
        }
    });
```

And this is the HTML template:
```
<template name="updateRating">
    {{#if currentSport}}
        <p>Current sport is set</p>

        {{> quickForm collection="Ratings" doc=currentSport id="updateRatingForm" type="update" autosave=true}}

        {{#autoForm id="afUpdateDemo" type=update collection="Ratings" doc=currentSport autosave=true}}
            {{> afQuickField name="name"}}
            {{> afQuickField name="fooDate"}}
            {{> afQuickField name="Budget"}}
            {{> afQuickField name="staff"}}
        {{/autoForm}}

    {{else}}
        Please select a sport
    {{/if}}
</template>
```

And the schema:
```
Ratings.attachSchema(new SimpleSchema({
    name: {
        type: String,
        label: "Name of Sport",
        allowedValues: Sports,
        max: 200,
        autoform: {
            type: "select2"
        }
    },
    fooDate: {
        type: Date,
        label: "Date (What date?)"
    },
    Budget: {
        type: Number,
        label: "Budget"
    },
     staff: {
        type: String,
        label: "Coaching Staff",
        allowedValues: RAGG,
        max: 20,
        autoform: {
            type: "select2"
        }
    },
etc.
```

It seems to be something to do with the way that `autoForm` interacts with select2 and allowedValues. As soon as I remove the select2 opotion from the schema, `autoForm` renders correctly now:

![screenshot 2015-08-01 14 56 41](https://cloud.githubusercontent.com/assets/243499/9020666/a1810e20-385d-11e5-92ab-b078ef7ac496.png)

However, `autoForm` renders the string fields as text input boxes - whilst `quickForm` renders them as normal HTML selects.

Is this a limitation of `autoForm`, or is there some way to get it to behave with select2, or `allowedValues`?

**Comment by victorhooi** [comment]
Also, I should mention that the autosave option doesn't work on `quickForm` in the example above.

I've set `autosave=true` on both forms - `quickForm` still shows a Submit button, but `autoForm` does not.

However, when you change values on the `autoForm`, it doesn't actually appear to do anything.

**Comment by deeeed** [comment]
I am experiencing the same issue, did you figure out the reason ?
