### ISSUE TITLE
Display whatever string was returned from custom as the validation error message

### ISSUE THREAD

**Issue by rbabayoff** [Meteor-Community-Packages/meteor-autoform#1114]
Hey,

First off, love your packages. Amazing stuff. One thing, though, that I do find a bit tedious and time consuming is requiring to add a custom error message to every custom validation error type that I might have, in SimpleSchema. I think it would save everybody a lot of time if the string returned from custom could just be used as is in the UI for the field error message.

**Comment by zimme** [comment]
Adding configuration to support this might be an option?

**Comment by rbabayoff** [comment]
Sure, I'd love this, and enable option for this..

**Comment by timmygee** [comment]
Perhaps the default behaviour could be that if the error type doesn't exist then the string returned from custom is used instead?
