### ISSUE TITLE
Could I use "inputmask" with number (decimal) field of Simple Schema? 

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-autoform#1120]
I would like to use `inputmast` with `number (decimal)` field fo Simple Schema.

``` js
// Simple Schema
amount: {
    type: Number,
    label: "Amount",
    decimal: true
  },

// Template
Config inputmask (...000,000.00)
```

But have problem with type `Number`.
Please help me.

**Comment by Tim-W** [comment]
What's the problem?

**Comment by thearabbit** [comment]
My problem with the type on `schema` is `Number (decimal)` but the `input box` in the form is `Type = String/Text` with `inputmask`.

**Comment by Tim-W** [comment]
Ah.. I've experienced that too, I think you should use parseInt at insert/update to convert the string to number.

**Comment by jimmiebtlr** [comment]
Another option is to use the `formToDoc` and `docToForm` hooks to make the change before validation.

**Comment by carrot93** [comment]
I got this problem. Comma or Dot to view and sum total ...any solution now?
