### ISSUE TITLE
How to conditionally show sub-field of [Object] field?

### ISSUE THREAD

**Issue by brylie** [Meteor-Community-Packages/meteor-autoform#1121]
We have a schema containing a field with [Object] type. We want to conditionally show one of the sub fields of that field based on a sibling field. How can we conditionally show a sub-field of an [Object] field based on a sibling field of the object sub-field?

**Comment by brylie** [comment]
@elnzv, please provide us with a schema example here.

**Comment by devarashetty** [comment]
+1
