### ISSUE TITLE
Show/Hide leaving blank divs

### ISSUE THREAD

**Issue by dlodeprojuicer** [Meteor-Community-Packages/meteor-autoform#1130]
I am doing a show/hide by changing field type of `companyName` based on `customerType` answer
![nnnnn](https://cloud.githubusercontent.com/assets/2291356/9218469/1a54ed3a-40d3-11e5-87c0-cc93585c63dc.JPG)

![qqq](https://cloud.githubusercontent.com/assets/2291356/9218500/5ba210ec-40d3-11e5-9968-e441657c18c2.JPG)

It works but instead of hiding the entire div, it seems to just make the opacity 0, leaving a blank spaces like so
![ccc](https://cloud.githubusercontent.com/assets/2291356/9218689/c85c90c6-40d4-11e5-9a3f-5d2aa82af870.JPG)

When I inspect the elements it shows form group divs with no content
![blank](https://cloud.githubusercontent.com/assets/2291356/9218754/8b2c79cc-40d5-11e5-9947-9a81081b87ff.JPG)

**Is there a way to remove the blank divs if field is hidden?**

**Comment by jimmiebtlr** [comment]
Try using 

    https://github.com/aldeed/meteor-autoform#affieldvalueis-and-affieldvaluecontains

to hide the field as a whole.

**Comment by Simomultimedia** [comment]
Hi @jimmiebtlr 

I am trying to let thandle that on the schema instead of html

**Comment by adburke** [comment]
So is it just changing the CSS to visibility:hidden instead of display:none ?

**Comment by Polioli** [comment]
autoform:
        "formgroup-class": function() {...your condition to show class "hidden"...}
