### ISSUE TITLE
Validation of "min" with "type:Date" has off-by-one issue

### ISSUE THREAD

**Issue by lukasvan3l** [Meteor-Community-Packages/meteor-autoform#1134]
When my schema is this:

```
{
   name: {
      type: Date,
      min: new Date()
   }
}
```

When I select today (2015-08-14) I get the following error:

```
FieldName must be on or after 2015-08-14
```

While I would expect this to be a valid value, only 2015-08-13 should be invalid, date after that should be valid. 

test it out on the playground here: http://autoform.meteor.com/quickform

**Comment by jimmiebtlr** [comment]
You would be better off testing with a custom validation.  Keep in mind date type also includes time, so when you set the min to now, and your preferred date plugin set's the date as the beginning of today's date in UTC, you will fail the validation.

**Comment by lukasvan3l** [comment]
Yeah, i'm actually using min: function() { new Date() } so that should work OK.

I'd prefer not to use custom validation because the MIN option also gets passed to the datepicker so you can't pick a date before the min date.

**Comment by jimmiebtlr** [comment]
That makes sense, that still leaves the issue of the times being different.  So for instance at the moment
`new Date()` will reteurn `Tue Aug 18 2015 12:59:43 GMT-0500 (CDT)`. Most of your date plugins use start of the corresponding UTC date, so `Tue Aug 18 2015 00:00:00`.  This would still cause the min to disallow it, try adjusting your min to be start of date UTC.
