### ISSUE TITLE
AutoForm.getFieldValue don't return value after upgrade into 5.4.1

### ISSUE THREAD

**Issue by chompomonim** [Meteor-Community-Packages/meteor-autoform#1136]
I just upgraded autoform from 5.4.0 into 5.4.1 and now AutoForm.getFieldValue('field_name') returns undefined. After downgrade back into 5.4.0 everything works well.

**Comment by maxnowack** [comment]
same problem here...

**Comment by rclai** [comment]
Same problem here. It seems like putting the form Id into the last parameter helps for some reason.

Every instance where I use the global helper `afFieldValue` also broke.

**Comment by dard12** [comment]
Same behavior here. Breaking on version 5.4.1 but supplying formId works.

For context I'm calling ```AutoForm.getFieldValue``` via a template helper within the ```#autoForm``` block.

**Comment by abuddenb** [comment]
I can confirm that `afFieldValueIs` is broken in 5.4.1.

**Comment by serkandurusoy** [comment]
Yep, I do confirm, too.

I'm declaring autoform options within the schema. Since the schema is not aware of which form (insert/update) it is being called from, how do I obtain a valid formId to pass to getFieldValue so that I can work around the problem?

**Comment by rodcope1** [comment]
I also confirm the issue with 5.4.1.  Unsurprisingly, it's still broken in 5.5.0.

**Comment by serkandurusoy** [comment]
A rather not-so-elegant workaround is:

```javascript
var formId = Autoform.getFormId();
var fieldValue = Autoform.getFieldValue('field', formId);
```

**Comment by felberj** [comment]
For me it looks like it has a problem with getting the value on the first time its rendered (so 'afFieldValueIs/AutoForm.getFieldValue' returns undefined while the form is not fully rendered)

I removed two `!template.view._domrange` checks but now I am stuck as he is trying to read in the DOM what the current value of the field is.

I will look more into it, but unfortunately I don't know Blaze/Meteor very well yet, so if anyone knows how automatically rerun the function when the DOM is ready please answer ;-)

For now I will look more into Autoform and try to see if I somehow get to the form data.

**Comment by aldeed** [comment]
I've merged some PRs. Please see whether this is fixed for you with 5.6.0 release

**Comment by chompomonim** [comment]
Unfortunately it's still broken.

**Comment by chompomonim** [comment]
In 5.7.1 it's still broken. I have to use @serkandurusoy proposed workaround.

**Comment by maxnowack** [comment]
I can confirm that it is still broken.
I use the same workaround and my code looks messy :(

**Comment by chompomonim** [comment]
BTW, as an alternative in schema I use `@siblingField("field_name").value`

**Comment by tcastelli** [comment]
+1

**Comment by maxnowack** [comment]
@aldeed any updates on this?
