### ISSUE TITLE
Problem with "do something (long time)" before return "doc" in "before: insert" hook???

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-autoform#1139]
For example:

``` js
BranchCollection:
   _id: 00001,......
   _id: 00002,......
........
```

And then I insert new

``` js
before: {
            insert: function (doc) {
                doc._id = idGenerator.gen(BranchCollection);

                return doc;
            }
        },
```

So It will generate new `_id = 00003` (work fine).
But when it has many records, it can't generate the `_id`.
I want to wait until the generate is ready, and then do the `return doc`.
Please help me.

**Comment by abecks** [comment]
For generating new ```UUIDs```, I use ```Random.id()``` which is a core package you can add with ```meteor add random```

Is your ``idGenerator`` function asynchronous?

**Comment by thearabbit** [comment]
I have multiple branch (difference place ) for my project, so if I use random id I afraid duplicate for consolidate on head office.
