### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by mazing** [Meteor-Community-Packages/meteor-autoform#1144]
An alpha version of Bootstrap 4 has just been released. Are there any plans on supporting the alpha version of bootstrap v4 in meteor-autoform or will we have to wait until a v4 full release?

**Comment by imajus** [comment]
This is my humble attempt to provide Bootstrap 4 support: https://github.com/imajus/autoform-bootstrap4
WARNING: some of components are not converted from Bootstrap 3 to 4. I will accept PRs.

**Comment by Philip-Nunoo** [comment]
> This is my humble attempt to provide Bootstrap 4 support: https://github.com/imajus/autoform-bootstrap4
> WARNING: some of components are not converted from Bootstrap 3 to 4. I will accept PRs.

@imajus great stuff. Would do.
