### ISSUE TITLE
Best way to display complex nested Schema

### ISSUE THREAD

**Issue by mshamblott** [Meteor-Community-Packages/meteor-autoform#1145]
I publish a Report defined by a ReportSchema. The Reports contain several things like title and an array of findings defined by a FindingSchema, which are fairly complex themselves.  I want to update the report (which is working) so that one finding at a time is displayed and I can dynamically control which finding fields are displayed.
1. I can embed a template within a template and use {{with aFinding}} to pass a finding object to a non-autoform list of object properties (e.g.  {{findingNumber}}  ). Problem is no Autoform so no cool functionality.
2. I can make embed a template containing an autoform to display the findings (e.g. {{> afQuickField name='findingNumber'}} ).  I can get the collection= parameter to use the Finding Schema, but this is an update and I can't figure out what to put for doc=.   doc=this refers to the Report document passed as data from the router and displayed correctly in the report itself.  doc=this.findings could refer to the array of findings, but  nothing i've tried sets the data context of the embedded template autoform is displayed and validated.  It displays with the correct fields but no data?
3. I can iterate over each finding field with {{#each affieldNames}} {{afQuickField name=this.name}} {{/each}}.  this.name works to display each field but I cannot limit which finding fields are shown. All is the only option. fields='myFieldName" or omitFields is ignored.  name=this.name.myFieldName also fails.  The only way I can control field visibility is within the schema, which is then not dynamic on the client (?).

**Comment by abecks** [comment]
I would highly recommend avoiding array fields until the performance issues are fixed. When I have a schema that contains an array, I render the array manually:

```handlebars
<template name="report">
{{#autoForm doc=this type='update' collection='collection' }}
    {{> afQuickField name='someReportField'}}

    {{#each findings}}
        {{> finding }}
    {{/each}}
{{/autoForm}}
</template>
```

Now, you won't be able to use autoform components inside ```finding```, and you cannot nest AutoForms, so if you need form fields inside that template, move it outside the AutoForm block:

```handlebars
<template name="report">
{{#autoForm id='reportForm' doc=this type='update' collection='collection' }}
    {{> afQuickField name='someReportField'}}
{{/autoForm}}

{{#each findings}}
    {{> finding }}
{{/each}}
</template>
```

```handlebars
<template name="findings">
{{#autoForm id='findingForm' class='findingForm' doc=this schema='FindingSchema'}}
    {{> afQuickField name='someFindingField' }}
{{/autoForm}}
</template>
```

Use AutoForm hooks to add the finding array back to the document when the form is submitted.

```js
AutoForm.addHooks('reportForm', {
    docToForm: function(doc){
        // If each finding template contained an AutoForm of its own
        doc.findings = [];
        $('.findingForm').each(function(){
            // Get the values for this AutoForm
            var values = AutoForm.getFormValues($(this).attr('id'));
            doc.findings.push(values);
        });
    
        return doc;
    }
});
```

The idea is to split array items into their own AutoForm instances instead of allowing AutoForm to use it's array field, which suffers from performance issues when the array gets longer than 10-20 items.

**Comment by mshamblott** [comment]
Thanks. I had a feeling there was a problem with my approach. 






On Tue, Sep 1, 2015 at 7:42 PM -0700, "Andrew Becker" <notifications@github.com> wrote:












I would highly recommend avoiding array fields until the performance issues are fixed. When I have a schema that contains an array, I render the array manually:

<template name="report">
{{#autoForm doc=this type='update' collection='collection' }}
    {{> afQuickField name='someReportField'}}

    {{#each findings}}
        {{> finding }}
    {{/each}}
{{/autoForm}}
</template>



Now, you won't be able to use autoform components inside finding, and you cannot nest AutoForms, so if you need form fields inside that template, move it outside the AutoForm block:

<template name="report">
{{#autoForm id='reportForm' doc=this type='update' collection='collection' }}
    {{> afQuickField name='someReportField'}}
{{/autoForm}}

{{#each findings}}
    {{> finding }}
{{/each}}
</template>

<template name="findings">
{{#autoForm id='findingForm' class='findingForm' doc=this schema='FindingSchema'}}
    {{> afQuickField name='someFindingField' }}
{{/autoForm}}
</template>



Use AutoForm hooks to add the finding array back to the document when the form is submitted.

AutoForm.addHooks('reportForm', {
    docToForm: function(doc){
        // If each finding template contained an AutoForm of its own
        doc.findings = [];
        $('.findingForm').each(function(){
            // Get the values for this AutoForm
            var values = AutoForm.getFormValues($(this).attr('id'));
            doc.findings.push(values);
        });

        return doc;
    }
});



The idea is to split array items into their own AutoForm instances instead of allowing AutoForm to use it's array field, which suffers from performance issues when the array gets longer than 10-20 items.

**Comment by Gigacross** [comment]
You can try the following: 

```
  {{#autoForm id="reportForm" schema=schema type="insert" }}
    {{> afArrayField name='findings'}}
  {{/autoForm}}
```

It worked for single level complex schemas, hope it works for you.
