### ISSUE TITLE
adding/removing from array causes id/for values on all array elements to change

### ISSUE THREAD

**Issue by literalsands** [Meteor-Community-Packages/meteor-autoform#1146]
![idchangebug](https://cloud.githubusercontent.com/assets/2459837/9410443/422f404a-47ee-11e5-86bd-5cb45ec82fc7.gif)

**Comment by ryanbuiltthat** [comment]
I just came across this too. I'm having to reference the schema.key since this is happening. Looks like it's just an arbitrary ID for the labels???? I'm trying to dynamically add items to the field but so far no luck. That's how I noticed all the ID's change.
