### ISSUE TITLE
Question | Ability to send Multiple Emails

### ISSUE THREAD

**Issue by rwatts3** [Meteor-Community-Packages/meteor-autoform#1150]
Is it possible to send multiple emails to several people in one click. 
Let's say I want to send a newsletter and I have a collection of emails. I would like to be able to send all the emails instead of having to send on email to every user.

**Comment by dandv** [comment]
How is this question about autoform?

**Comment by rwatts3** [comment]
Because there is an example of how to send emails in the read me docs.  Do you have a solution ?
