### ISSUE TITLE
Radio Button Problem

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Meteor-Community-Packages/meteor-autoform#1152]
Hi, I'm using a template where the radio buttons must be defined like this:

```
<div class="radio radio-success">
<input type="radio" value="yes" name="optionyes" id="yes">
<label for="yes">Agree</label>
<input type="radio" checked="checked" value="no" name="optionyes" id="no">
<label for="no">Disagree</label>
</div>
```

So I Created a template called "teste"

```
<template name="afRadioGroup_teste">
  <div class="af-radio-group radio radio-success" {{dsk}}>
  {{#each this.items}}
    <input type="radio" value="{{this.value}}" {{atts}} id="{{this.value}}">
    <label for="{{this.value}}">{{this.label}}</label>
  {{/each}}
  </div>
</template>
```

And I'm changing the template on Simpleschema definition:

```
  aluguel:{
    type:String,
    allowedValues: ['direto','indireto'],
    autoform: {
      template: "teste",
      type: 'select-radio',
      options: [
        {value:"direto", label:"Direto",id:"direto"},
        {value:"indireto", label:"Indireto",id:"indireto"}
      ]
    }
  },
```

The problem is: the radio button only works when the input id is exactly equals the "value" attr
like here: `<input type="radio" value="yes" name="optionyes" id="yes">`

How can achieve this? will it compromise autoform's functionalities?

**Comment by TravisDart** [comment]
This is really more of a StackOverflow question than a GitHub issue, but I think what you want to do is change the field type to Boolean and use the `boolean-radios`:

`{{> afQuickField name="aluguel" type="boolean-radios" trueLabel="Direto" falseLabel="Indireto"}}`
