### ISSUE TITLE
Value attribrute on afArrayField

### ISSUE THREAD

**Issue by charlesvestur** [Meteor-Community-Packages/meteor-autoform#1156]
Hi,

I have a document and I want to insert its values in an form created by an autoform.
Let's say my doc is like :
doc = {name: "string", array: ["string1","string2"]};

The form works with a db called "Activities" with the following schema:
Activities.attachSchema(new SimpleSchema({
  array: {
  type: [String], 
  },
  name: {
  type: String, 
  },
}));

when I write :
{{> afQuickField name="name" id="name" value=name}}
I have "string" as a default value in the input and it works fine.

However, when I write
{{> afArrayField name="array" value=array}}
"string1" and "string2" do not appear in the input field

How can I make it work?

Thanks!

**Comment by BackSpaceTech** [comment]
+1

**Comment by SantoshSrinivas79** [comment]
@charlesvestur did you figure out how to make this work! I seem to have run into a similar issue
