### ISSUE TITLE
Template.rendered runs before AutoForm actually adds elements to DOM

### ISSUE THREAD

**Issue by tothand** [Meteor-Community-Packages/meteor-autoform#1157]
I have a user schema which has a multiple checkbox select in it:

``` javascript
  roles: {
      type: [String],
      optional: true,
      autoform:{
        type: "select-checkbox",
        options : function(){
          return Roles.getAllRoles().map(function(c){
            return {label: c.name, value: c.name};
          });
        }
      }
  }  
```

I have a template like this

``` html
<template name="userForm">
    <div class="centerform">
    {{#autoForm collection="Meteor.users" id="userForm" type="method-update" meteormethod="updateUser" doc=getUserData}}
        <fieldset>
          <legend>Edit user</legend>
          {{> afQuickField name="username"}}
          {{> afQuickField name="profile.name"}}
          {{> afQuickField name="profile.company"}}
          {{> afQuickField name="profile.department"}}
          {{> afQuickField name="profile.building"}}
          {{> afQuickField name="roles"}}
        </fieldset>
        <button type="submit" class="btn btn-primary">Save changes</button>
    {{/autoForm}}
    </div>
</template>
```

and I have a function like this (this is just a debug function to show the problem)

``` javascript
    Template.userForm.rendered = function(){
        console.log($('input[type=checkbox]').length);
            Meteor.setTimeout(function(){
                console.log($('input[type=checkbox]').length);
            }, 1000);
    };
```

The result is 1 and 4 on the console, except on the first render it is 4 and 4 after a page reload but after navigating in the app back and forth (FlowRouter.go(...) ) its 1 ad 4 all the time.

I am far from being an expert on the subject (I am only using Meteor for a few weeks now) but it seems that the Template.rendered function runs before AutoForm adds the elements to the DOM. The first render is slower (my guess is that Blaze is doing something) so in that case the DOM is ready by the time the rendered function runs.

Anyway you guys are much better at this than me so I hope you can figure out what is happening here.

For the time being I am using a 100ms delay that seems to do the job. Hackish but working.

I am using `aldeed:autoform - 5.4.1`

**Comment by wesyah234** [comment]
I have a feeling this might be related to my issue #1163 ... try just for kicks backing off to 5.4.0:

```
meteor remove aldeed:autoform
meteor add aldeed:autoform@=5.4.0
```

**Comment by tothand** [comment]
This is what I was thinking first when I've found your issue but I didn't try downgrading so thanks for the suggestion.

Unfortunately it didn't help so I'll stick to the setTimeout solution until someone finds out what is happening.

**Comment by serkandurusoy** [comment]
@tothand I don't quite understand where you place the timeout so that you can work around the checkbox issue. Would you mind sharing the actual snippet instead of the debugging code?

**Comment by tothand** [comment]
It is almost the actual snippet the only difference that instead of the console.log() I'm using an external JS to beautify the checkbox.

**Comment by serkandurusoy** [comment]
hmm in that case I'm having a different problem because the dom itself does
bot contain the raw information

Sent from my iPhone



On Sep 3, 2015, at 11:34, tothand <notifications@github.com> wrote:

It is almost the actual snippet the only difference that instead of the
console.log() I'm using an external JS to beautify the checkbox.

—
Reply to this email directly or view it on GitHub
<https://github.com/aldeed/meteor-autoform/issues/1157#issuecomment-137378717>
.

**Comment by micant** [comment]
I'm having the same issue and have been attempting a workaround for some time, with no success. Interested in a solution if anyone has one.
