### ISSUE TITLE
Conditional omit field

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Meteor-Community-Packages/meteor-autoform#1158]
Hello. I have two roles in my app: admin and store-owner
each "Customer" is related to a store... when a store-owner registers a customers, it's automatically related to the owner's store.
when an admin registers a customer, he can select to which store that customer will be related
So, when admin access the autoform field to insert customers, there must be the Store selection field
When store-owner access, there must be no Store selection field because any customer he adds will be automatically related to his store (im using before.insert hook to do that, is that ok?)
I know i can do {{if}} on template.. but is there an ellegant way?

Thanks

**Comment by abecks** [comment]
I do ```{{if}}``` on the template. Doing it in the schema gets messy and makes the schema responsible for view rendering logic (it should really just be validation logic). As long as your ```allow``` or ```deny``` rules are properly secured to prevent store owners from setting the store of a customer. I generally find that is much cleaner to do it in the template if possible.
