### ISSUE TITLE
Select2 destroy error

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [Meteor-Community-Packages/meteor-autoform#1160]
Hi, when my select2 element is destroyed (it's rendered inside a if statement, so when it turns false, it is destroyed) i get the error on console:
The select2('destroy') method was called on an element that is not using Select2.

Do u guys know how to solve it? thanks

**Comment by lynchem** [comment]
+1

**Comment by jpbourgeon** [comment]
+1

**Comment by thearabbit** [comment]
I have the same problem +1.

**Comment by JulianBurz** [comment]
+1

**Comment by ralph-fuechtenkort** [comment]
+1

**Comment by akashdeepshah** [comment]
I have the same problem

**Comment by deeeed** [comment]
+1

**Comment by puddicombe** [comment]
+1

**Comment by tomyo** [comment]
+1

**Comment by zorch** [comment]
+1

**Comment by zreiby** [comment]
+1

**Comment by ankitappuria** [comment]
Anyone got fixed up this issue?

**Comment by joaolboing** [comment]
+1

**Comment by thearabbit** [comment]
Now I cloned and custom via `PR`, then use it in local package.

**Comment by Lazarencjusz** [comment]
+1
