### ISSUE TITLE
Reactive Sub-Schemas

### ISSUE THREAD

**Issue by jamgold** [Meteor-Community-Packages/meteor-autoform#1174]
I have a collection that contains objects with slight differences. During 3.x days of autoform I posted a similar question, ultimately found a workaround and implemented it. The other week I was cleaning up my code a bit and decided that it was too convoluted.

Here is what I want to achieve. I have a collection "Pets". Each pet has a name and a birthdate, but one is a dog, the other a bird and the third snake, three different species.

The Pet schema has a field kindof that determines what kind of pet it is. I invented the type **Schema** that would allow me to define one of the schemas. 

How could I possibly implement something like this?

```
Schema.Reptile = new SimpleSchema({
 length: {
  type: Number;
 },
 venomous: {
  type: Boolean;
 }
});
Schema.Mammal = new SimpleSchema({
 legs:{
  type: Number,
  allowedValues: [2,4],
 }
});
Schema.Bird = new SimpleSchema({
 carnivorous: {
  type: Boolean;
 }
});
Schemas.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 kindof: {
  type: Schema,
  allowedValues: [ Schema.Reptile, Schema.Mammal, Schema.Bird ]
 },
});
Pets.attachSchema(Pet);
```

**Comment by serkandurusoy** [comment]
+1

**Comment by abecks** [comment]
This appears to work:

```js
Schema.Reptile = new SimpleSchema({
 length: {
  type: Number
 },
 venomous: {
  type: Boolean
 }
});
Schema.Mammal = new SimpleSchema({
 legs:{
  type: Number,
  allowedValues: [2,4],
 }
});
Schema.Bird = new SimpleSchema({
 carnivorous: {
  type: Boolean
 }
});
Schema.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 kindof: {
  type: SimpleSchema,
  allowedValues: [ Schema.Reptile, Schema.Mammal, Schema.Bird ]
 },
});
```

Proved with:
```js
var ctx = Schema.Pet.newContext();
ctx.validate( { name: 'success', kindof: Schema.Reptile }) // returns true
ctx.validate({ name: 'fail', kindof: new SimpleSchema() }); // returns false, this schema is not in the list of allowedValues
```

**Comment by jamgold** [comment]
This is awesome. Did I miss this in the documentation?

**Comment by abecks** [comment]
I don't think using other types is documented. But this would be in the SimpleSchema repo instead of AutoForm.

**Comment by jamgold** [comment]
Of course. Now let's check if collection2 can deal with this

**Comment by serkandurusoy** [comment]
:clap:

**Comment by jamgold** [comment]
Hmm, this doesn't work here. Meteor@1.1.0.3
```
aldeed:autoform     5.5.0  Easily create forms with automatic insert and update, and automatic reactive validation.
aldeed:collection2  2.5.0  Automatic validation of insert and update operations on the client and server.
autopublish         1.0.3  Publish the entire database to all clients
insecure            1.0.3  Allow all database writes by default
iron:router         1.0.9  Routing specifically designed for Meteor
meteor-platform     1.2.2  Include a standard set of Meteor packages in your app
```
as soon as I render `{{>quickForm collection="Posts" id="insertPost" type="insert"}}` it throws errors.

It doesn't like `allowedValues: [Schema.First, Schema.Second]` and as soon as try to define the autoform part it fails with

```
[Log] Exception from Tracker recompute function: (meteor.js, line 888)
[Log] Error: Unexpected object in htmljs in toText: [object Object] (meteor.js, line 888)
```

**Comment by jamgold** [comment]
Looks like SimpleSchema can handle this just fine, but I can not get AutoForm to deal with this.

**Comment by serkandurusoy** [comment]
I think quickform is a little too opinionated to get this working. A full autoform with afQuickField's seems to be the solution.

**Comment by jamgold** [comment]
Did you get this to work? If so, can you post an example?

**Comment by serkandurusoy** [comment]
Not yet, I'm working on it, but will do as soon as I get it to work.

**Comment by jamgold** [comment]
Thanks. Currently I am using the afFieldValueIs, but it relies on statically defining the sub schemas like
```
Schema.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 kindof: {
  type: String,
  acceptedValues: ['mammal','bird','reptile']
 },
 mammal: {
  type: Schema.Mammal,
  optional: true
 },
 bird: {
  type: Schema.Bird,
  optional: true,
 },
 reptile: {
  type: Schema.Reptile,
  optional: true
 }
}
```
and then using the following in my `#autoForm collection="Pets"`
```
{{#each species}}
 {{#if species_check current=kindof value=value}}
  {{>afQuickField name=field value=data}}
 {{/if}}
{{/each}}
```

**Comment by serkandurusoy** [comment]
Well, in fact this is what I'm leaning on so that I have more control over the structure of the generated form.

**Comment by jamgold** [comment]
but that means your document in mongodb will allways have the fields mammal, bird and reptile. You also need to hack autoform to enforce validation of sub-schemas because they have to be optional by default. I have all of that working, but it seems so hacky.

I much rather have the kindof and data in my document, and have the system deal automatically with it. We just need to figure out how we can get autoform deal with it

**Comment by serkandurusoy** [comment]
No, why? I'm making top level of each sub type optional so that they end up in a doc only if they are actually present. But I'm not making the inner levels optional, therefore if the object exists, it must contain the values.

Also, I'm defining autoform rules and options along with the schema.

I'll see how it turns out.

I'm kind of on a schedule so I'm hacking away, but if you have the time, you might want to check out how telescope uses autoform. As far as I know, they are generating the forms on the fly based on dynamically generated schemas. So that could give a clue.

**Comment by abecks** [comment]
Ok I see the problem.

AutoForm is trying to turn the value of the options (the schema definitions) into an HTML attribute for the <option> markup. You will need to use a translation technique to convert from string values to the actual schema.

You know, now that I think about it, using ```type: Schema.Mammal``` is not a good idea because it will store the schema with every document in the collection.

A pet document would be a lot bigger than it would need to be:

```js
var pet = {
   name: 'Some Name',
   kindof: {
      // the whole schema definition would be stored here with every document
      // instead you probably just want a string to validate it against Schema.whatever
   }
}
```

I like:

```js
Schema.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 kindof: {
  type: String,
  acceptedValues: ['Mammal','Bird','Reptile'],
  autoform: {
     afInputField:{
        type: 'select',
        options: function(){
           return [
                {label: "Reptile", value: 'Reptile' },
                {label: "Bird", value: 'Bird' },
                {label: "Mammal", value: 'Mammal' }
           ];
        }
     } 
  }
 },
});
```

Is there any reason you want the schema definition associated with the document? Since its a global, you can always take the string value of ```kindof``` and use it to lookup the schema:

```js
Schema[pet.kindof]    // Reptile, Mammal, Bird, etc.
```

I think you are also trying to store the document representing Mammal, Bird, or Reptile with the Pet document. And your ```mammal: { type: Schema.Mammal }``` approach may work but is obviously not very maintainable. 

I've done this before using the blackbox property, so something like this:

```js
Schema.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 kindof: {
    // same as above
 },
 data: {
    type: Object,
    blackbox: true
 }
});
```

and then put the type-specific properties under meta, and validate them separately against the appropriate schema as defined by kindof. (in a SimpleSchema custom validator function, or in a server method, or in allow/deny, etc)

Try not to use quickForm too much. It's a crutch and you'll almost always have to rip them out for autoForms in order to have control over what is rendered.

**Comment by jamgold** [comment]
> You know, now that I think about it, using type: Schema.Mammal is not a good idea because it will store the schema with every document in the collection.

it doesn't in my current implementation. It just automatically validates with autoform/collection2. It uses the type to know how to validate the data provided and to know what to render with autoform. Otherwise it would store `String` when defining `type: String` as well.

I was shying away from the blackbox approach and custom validators and also liked the automatic autoform rendering when adding the sub Schema.

The ability to provide an Object (SimpleSchema) as type has potential. I just need to figure out how to teach autoform how to handle it.

**Comment by abecks** [comment]
Can you show an example document? It has to store some value for ```kindof```, whats in there?

**Comment by abecks** [comment]
I see how your current method uses afFieldValueIs to show the subfields. Something you have to edit every time you want to show fields for a new type. It also requires you have those pesky top-level mammal, bird, reptile, etc. schema properties.

I would consider doing two forms. One for the common pet data, and another for the sub-schema data. Change the second form's schema to the appropriate type when the kindof select box changes.

I'd render them both on the same page, and only have a submit button for the main pet form. Use the formToDocHook in AutoForm to stitch in the second form's values.

This way you won't have to maintain a list of if's for each type in the form template. Let me know if you need a hand with the custom validator but it shouldn't be too hard.

**Comment by jamgold** [comment]
> This way you won't have to maintain a list of if's for each type in the form template. Let me know if you need a hand with the custom validator but it shouldn't be too hard

I don't. In the example below `kindof` contains a structure
```
{name:'Schema.Mammal', value: 'mammal'}
```

```
  Template.addAutoForm.helpers({
    renderField: function() {
      return Session.get('kindof')
    },
  });

<template name="addAutoForm">
  {{#autoForm collection="Pets" id="insertPost" type="insert"}}
    {{>afQuickField name="name"}}
    {{>afQuickField name="kindof" value=renderField.name}}
    {{>afQuickField name=renderField.value}}
    <button>Submit</button>
  {{/autoForm}}
  <a href="/">Cancel</a>
</template>
```

**Comment by jamgold** [comment]
Here are the documents, btw
```
meteor:PRIMARY> db.pets.find().pretty()
{
	"_id" : "TazXZHNQN36ATkfFJ",
	"name" : "Fido",
	"kindof" : "Schema.Bird",
	"bird" : {
		"carnivorous" : true
	}
}
{
	"_id" : "rh7XKdLQJiMAz2r4m",
	"name" : "Luke",
	"kindof" : "Schema.Mammal",
	"mammal" : {
		"legs" : 4
	}
}
```

**Comment by serkandurusoy** [comment]
I finally finished up the schema and I can say that defining the complete schema and using autoform field type as a function that returns hidden if not selected works good.

```javascript
function checkVisibility(kind) {
  var formId = AutoForm.getFormId();
  var kindof = AutoForm.getFieldValue(kindof, formId);
  return kindof !== kind && hidden;
}

Schema.Pet = new SimpleSchema({
  name: {
    type: String,
  },
  kindof: {
    type: String,
    acceptedValues: ['Mammal','Bird','Reptile'],
    autoform: {
      afInputField:{
        type: 'select',
        options: function(){
           return [
             {label: "Reptile", value: 'Reptile' },
             {label: "Bird", value: 'Bird' },
             {label: "Mammal", value: 'Mammal' }
           ];
        }
      } 
    }
  },
  mammal: {
    type: Schema.Mammal,
    optional: true,
    autoform: checkVisibility('Mammal')
  },
  bird: {
    type: Schema.Bird,
    optional: true,
    autoform: checkVisibility('Bird')
  },
  reptile: {
    type: Schema.Reptile,
    optional: true,
    autoform: checkVisibility('Reptile')
  }
});
```

And you can use a quickform. No need to fiddle around with autoform and afField's.

This could be further improved (if you are adding new kinds dynamically) to _.extend(Schema.pet, newKindSchema) as required and the form would be updating itself.

**Comment by jamgold** [comment]
@serkandurusoy thanks, great to see a different approach. How is your's dealing with non-optional elements?

What I am ultimately after is just a `data` structure in my documents, no matter which schema was used. So my initial question about how autoform handles dynamic sub-schemas is still standing.

>AutoForm is trying to turn the value of the options (the schema definitions) into an HTML attribute for the markup. You will need to use a translation technique to convert from string values to the actual schema.

this seems to be one of the first hurdles to be tackled.

**Comment by abecks** [comment]
Nice work guys!

AutoForm turns all of the properties in the schema under  ```autoform``` into HTML attributes. I think it also does this for the ```value``` property of the field (hence your error up there).

I made a PR for passing data structures through the schema using a special property. Check #1133 to see if it might be of any help.

**Comment by jamgold** [comment]
@abecks thank you for taking the initiative :) I will check out your PR as soon as I can

**Comment by serkandurusoy** [comment]
@jamgold I'm writing custom validations for all the schema keys, first checking if it is a part of the selected schema.

**Comment by jamgold** [comment]
@serkandurusoy so this will be difficult for dynamically defined schemas. Currently I have a web UI with forms guiding a user through creating new Schemas. They are stored in mongo and dynamically added to the Schemas used to autoform/collection2 validate.

**Comment by serkandurusoy** [comment]
Oh I see, but again, isn't validation a part of the schema definition? So custom validations are a part of that as well, but could be used opt-in.

Granted, simple-schema has some [hard-to-grasp validation rules](https://github.com/aldeed/meteor-simple-schema#optional) when it comes to optional.

**Comment by jamgold** [comment]
Based on @abecks comment from Sept 1st I am revisiting this. He stated that SimpleSchema can be defined with the `type: SimpleSchema`, which seemed to be the answer.

According to autoform documentation I can actually specify a schema with #autoForm that is different from the schema associated with the collection. 

So here is my abbreviated Schema definition
```
.
.
.
Schema.Bird = new SimpleSchema({
 carnivorous: {
  type: Boolean,
 }
});
Schema.PetBird = new SimpleSchema({
  name: {
   type: String,
  },
  data: {
    type: Schema.Bird
  }  
});
Schema.Pet = new SimpleSchema({
 name: {
  type: String,
 },
 data: {
  type: SimpleSchema,
  allowedValues: [ Schema.Reptile, Schema.Mammal, Schema.Bird ],
 },
});
Pets.attachSchema(Schema.Pet);
```
I associate the Schema.Pet with the collection, but for autoForm's sake I create a separate schema Schema.PetBird and then render the form with
```
  {{#autoForm collection="Pets" schema=kindof id="insertPost" type="insert"}}
    {{>afQuickField name="name"}}
    {{>afQuickField name="data"}}
    <button class="btn btn-info">Submit</button>
  <a href="/" class="btn btn-danger">Cancel</a>
  {{/autoForm}}
```
with a helper function
```
  Template.registerHelper('kindof', function() {
    return Schema['PetBird'];
  });
```
which reactively renders the form correctly, but upon submit resultCallback in autoform-events.js 258 barfs. Am I reading this right that collection2 complains?
```
Error: Data must be a 
column: 24
invalidKeys: [{name: "data", type: "expectedConstructor", value: {}}] (1)
line: 460
message: "Data must be a "
sourceURL: "http://localhost:3000/packages/aldeed_collection2.js?0e1a8fd75edeeb40b3ae5b365c9e75d0dc45d9a0"
stack: "getErrorObject@http://localhost:3000/packages/aldeed_collection2.js?0e1a8fd75edeeb40b3ae5b365c9e75d0dc45d9a0:460:24↵doValidate@http://localhost:3000/packages/aldeed_collection2.js?0e1a8fd75edeeb40b3ae5b365c9e75d0dc45d9a0:443:27↵http://localhost:3000/packages/aldeed_collection2.js?0e1a8fd75edeeb40b3ae5b365c9e75d0dc45d9a0:212:35↵http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:3085:26↵runHook@http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:7727:15↵runBeforeHooks@http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:7757:14↵onSubmit@http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:3081:24↵autoFormSubmitHandler@http://localhost:3000/packages/aldeed_autoform.js?019cba9c67d18d17c34ea48a455d8956ded05487:7833:22↵http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3705:25↵_withTemplateInstanceFunc@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3679:16↵http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:3704:50↵http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2565:35↵_withCurrentView@http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2219:16↵http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:2564:42↵http://localhost:3000/packages/blaze.js?695c7798b7f4eebed3f8ce0cbb17c21748ff8ba8:841:29↵dispatch@http://localhost:3000/packages/jquery.js?bd30605bc9f8429d01bae2d29081902d10a6c400:4699:14↵handle@http://localhost:3000/packages/jquery.js?bd30605bc9f8429d01bae2d29081902d10a6c400:4367:33"
validationContext: SimpleSchemaValidationContext {_simpleSchema: Where, _schema: Object, _schemaKeys: ["name", "data"], _invalidKeys: [{name: "data", type: "expectedConstructor", value: {}}], _deps: Object, …}
```
