### ISSUE TITLE
select-checkbox not populating checked status on update quickform

### ISSUE THREAD

**Issue by serkandurusoy** [Meteor-Community-Packages/meteor-autoform#1179]
I'm on version 5.5.0 and using a quickform (insert/update) to generate a form that contains the following schema key:

``` javascript
var tags = ['tag1','tag2','tag3'];

tags: {
  type: [String],
  minCount: 1,
  autoform: {
    type: 'select-checkbox',
    options: function() {
      return _.map(tags, function(tag) { return { label: tag, value: tag }; });
    }
  }
}
```

An array of tags are persisted using `type="insert"` but on the update form, the checkboxes don't appear checked.

**Comment by tothand** [comment]
It sounds familiar. Maybe I'm wrong but check if it is related to this issue https://github.com/aldeed/meteor-autoform/issues/1157

**Comment by serkandurusoy** [comment]
Yikes! Looks ugly.

**Comment by tothand** [comment]
If you have a better solution your welcome to share it :)
Also it is entirely possible that your problem is completely unrelated.

**Comment by serkandurusoy** [comment]
Nope, I'm now quite fit for your workaround, which I did not actually get :)
