### ISSUE TITLE
Autosave form change event function variable lastKeyVal issue

### ISSUE THREAD

**Issue by spotla** [Meteor-Community-Packages/meteor-autoform#1188]
Auto save form doesn't get submit, if the same input field changed to the same value as previously loaded form's field.

We have list of documents in a screen.  User will click on a item to view a auto save form with item's data to edit. User open's Item#1 and edits a Field#1 with value 'xyz', form gets saved. Subsequently if user open's Item#2 and edits a Field#1 to be same as previous value 'xyz', form doesn't get saved.  

autofrom-event.js  -  'change form' function has  if (keyVal === lastKeyVal)  return;  keyVal is getting compared with lastKeyVal of previous form.  

It would be great help if any of you can help me in resolving the issue.

**Comment by dshitik** [comment]
++ Yep. Same problem.
