### ISSUE TITLE
Autoform subtracts 1 day on update

### ISSUE THREAD

**Issue by dnish** [Meteor-Community-Packages/meteor-autoform#1190]
Hey guys,
I'm having a strange issue with autoform when updating a collection. I've the following validation for a birthdate:

```
birthday: {
    type: Date,
    optional: (this.isInsert) ? true : false,
    max: moment().subtract(10, 'years').toDate(),
    min: moment().subtract(65, 'years').toDate()
}
```

This is in my template:

```
<div class="item-title">{{> afFieldInput name='profile.birthday'}}</div>
```

When I submit, he updates all changes, but also subtract 1 day from the date. This happens on every update.

I've checked it with current Chrome version.

//Can be closed, becuase I didn't see the UTC issue.

**Comment by jm1200** [comment]
I am having this problem too. Would you mind pointing to your solution? I have been looking up UTC issue and can't find the fix. Thanks.
