### ISSUE TITLE
Bug: ssIsOverride seems to be inverted

### ISSUE THREAD

**Issue by dalgard** [Meteor-Community-Packages/meteor-autoform#1191]
My `method-update` autoform uses a collection and a separate schema. But the submission fails, because autoform tries to use a schema on the collection.

The code says `useCollectionSchema: c.ssIsOverride`.

So – if `ssIsOverride` is true, AutoForm expects to use a schema on the collection (which doesn't exist, in my case). The way I read the documentation, it should be the other way around:

> this.ssIsOverride: This is true if this.ss is an override schema, meaning it's coming from a schema attribute on the autoForm or quickForm, but there is also a collection attribute pointing to a collection that has its own schema attached.

Things finally fail here:

https://github.com/aldeed/meteor-autoform/blob/396bbcd198000a1dbefc145eabe5b3ff40459070/autoform-events.js#L100

**Comment by aldeed** [comment]
As the documentation says, `ssIsOverride` should only be true if the collection has a schema and there is also a form `schema`. I don't think the logic for which schema to use is wrong, but `ssIsOverride` shouldn't be `true` in the first place if your collection does not have a schema attached.
