### ISSUE TITLE
afArrayform autosave on 'remove' item event, not implemented?

### ISSUE THREAD

**Issue by lpgeiger** [Meteor-Community-Packages/meteor-autoform#1208]
```
{{#autoForm collection="Hours" doc=cursor id="hoursFormUpdate" type="update" autosave=true}}
{{> afArrayField name='list'}}
```

Seem that 'add' and 'remove' events on an array does not trigger the 'autosave'  function. (Updating items works perfectly with autosave).

Seems to me 'remove' should be implemented. Am I missing something?

**Comment by aldeed** [comment]
Yes, needs to be fixed.

**Comment by aviadbd** [comment]
Now at 6.0 and still not fixed?
