### ISSUE TITLE
[FR] Collection.attachForm(formDefiniton)

### ISSUE THREAD

**Issue by serkandurusoy** [Meteor-Community-Packages/meteor-autoform#1210]
When I use autoform, I use it extensively and that's usually for CRUD type applications where I need lots of forms.

And when I do, I try my best to fit the whole form definition and rules within the schema contained in `autoform` properties of each schema key. This allows for me to keep most of the app definitions and rules in a single place and make use of `quickform` one line templates.

This is especially good during until we achieve feature-freeze and we know that the schema/form won't change much after that point and it may be desirable to play around with the form layout. 

It so happens, I leave most of the forms in their original quickform form.

But then I have projects, especially those that have different front end and back end UI's where autoform makes sense for the backend and not front end or front end form may require a different definition than its counterpart on the backend.

It would just be great if instead of keeping the autoform definitions within the schema itself, I could keep a separate object describing the form and attaching it to the collection, or the schema as needed. It would also make the code much easier to read and follow.

**Comment by aldeed** [comment]
Can you post some example code for how you think the API would work?
