### ISSUE TITLE
Display Meteor.Method errors on autoForm automatically

### ISSUE THREAD

**Issue by MichaelJCole** [Meteor-Community-Packages/meteor-autoform#1214]
What is the simplest way to get errors from a Meteor.Method on to a quickForm?

I'm using a quickform with type="method"

```

  {{> quickForm
    id="insertOther"
    schema="Schema.Other"
    type="method"
    meteormethod="insertOther"
    fields="email, title, description, invitationMessage"
    buttonContent="Invite"
  }}
```

Then on the server I'm checking the email:

```
Meteor.methods({
  'insertOther': function(obj) {
    if (! SimpleSchema.RegEx.Email.test(obj.email) ) {
      throw new Meteor.Error('regEx email');
    }
    ...
});
```

And in the AutoForm.hooks:

```
  onError: function(formType, error) {
    if (error.errorType && error.errorType === 'Meteor.Error') {
      this.addStickyValidationError('email', error.error);
      AutoForm.validateField(this.formId, 'email');
    }
  },
```

[Here](https://github.com/aldeed/meteor-simple-schema#customizing-validation-messages) explains how to add validation messages on the client.  

```
SimpleSchema.messages({
  'regEx email': 'You can\'t use your email here',
  'cantCreateAccount': 'We couldn\'t create an account for this email',
  'cantInviteSelf': 'You can\'t invite yourself by email',
});
```

I'm just not getting the design of how to move errors from server to client via the Meteor.Method's return value.

Thanks!

(there may be better ways to check if the email is valid, it just a simple example here)

**Comment by Kostanos** [comment]
+1 I'm with the similar problem here, trying to pass Unique Key error from server to Client. Any luck here?

**Comment by aldeed** [comment]
Collection2 does this seamlessly here: https://github.com/aldeed/meteor-collection2/blob/master/collection2.js#L451-L474

Basically it puts an identifiable string in the error message and stringifies the invalidKeys array in the error details. Then on the client, it detects the identifiable string and parses the invalidKeys, and then adds them to the client list.

It also separately transforms mongo unique key errors into corresponding SS errors.

It would be nice to come up with a pattern around this, allowing it to be reused in the autoform method situation, too. For example, calling `check(obj, mySchema)` at the top of your function could do this by default, allowing autoform to display the errors automatically.

**Comment by mazing** [comment]
+1

**Comment by serkandurusoy** [comment]
This may prove even more useful given that the new meteor guide promotes the use of methods and autoform together and discourages direct inserts/updates. Furthermore, the new meteor validationerror might help.

**Comment by patte** [comment]
I use AutoForm extensively in a science project, I need to do schematic and manual validations, so I use type="method-update" most of the times. I've come up with the following hook to display validation errors inside the (Auto)Form.

```
# show errors from method-update schema check
AutoForm.addHooks null,
  beginSubmit: ->
    AutoForm.templateInstanceForForm(@formId)._stickyErrors = {}
  onError: (formType, error) ->
    try
      fieldErrors = JSON.parse(error.details)
    catch e
      # don't care
    finally
      if !fieldErrors? or fieldErrors.length is 0 
        throwError error
        return
    form = @
    JSON.parse(error.details).forEach (e) ->
      form.addStickyValidationError(e.name, e.type)
```

This works pretty nice for schema validation errors (except for uniqueness checks, but this is another story https://github.com/aldeed/meteor-collection2/issues/218). In case I want to display an error based on my manual validations (over multiple collections) I do something like this:
```
  updateQuestion: (modifier, docId) ->
    if modifier['$set'].code is "asdf"
      details = EJSON.stringify [
        name: "code"
        type: "expectedObject" #orWhatEverTypeYouWant
        value: ""
      ]
      throw new Meteor.Error(400, "validationError", details)
```

@aldeed I'm more than happy to submit a pull request. Is a default hook, like the one I pasted the way or do what would be a better approach? Your link to C2 is broken, can you point me to the code where these errors are generated and where AutoForm evaluates them?

**Comment by brylie** [comment]
We would also like to display an error message from a Meteor.Method within an AutoForm. Our use case is not related to field validation, but rather an environmental variable. If the environmental variable has not been set, our Meteor method throws an error. I would like to catch this error and display it to the end user directly within the form. Is there a way to set a form template text, e.g. from within the `onError` callback?
