### ISSUE TITLE
[FR] Support help text

### ISSUE THREAD

**Issue by philipmjohnson** [Meteor-Community-Packages/meteor-autoform#1215]
I recently finished a sample Meteor app using AutoForm to illustrate basic features and to support comparison with a similar app I created previously using the Play Framework. 

This process seems to indicate that AutoForm would benefit from built-in support for help text. Please see the last section (called "Issues: Form Help Text") of the following page for a more detailed explanation and sample code:

http://ics-software-engineering.github.io/meteor-example-autoform/

**Comment by thebarty** [comment]
+1 for this one... maybe even in a schema like 
```
  note: {
    type: String,
    label: 'Notes',
    labelHelp: 'Place for your note - use markup if you want to',
    }
```

**Comment by thebarty** [comment]
@philipmjohnson: Did you manage to access your schema field in the form template?

**Comment by philipmjohnson** [comment]
@thebarty No, I'm crossing my fingers that support for help text will be added to the schema.
