### ISSUE TITLE
Question : Rendering Input Fields based on Selection

### ISSUE THREAD

**Issue by rwatts3** [Meteor-Community-Packages/meteor-autoform#1244]
What is the best way to render input fields based on a user selection. 
EX: 
- Dropdown selection contains options for items. 
- If Item A is selected in the dropdown, render Two Options tailored to that selection.
- If Item B is selected in the dropdown, render 3 Options tailred to that selection.

**Comment by deepu12** [comment]
I want the same which you have asked. Are there any other options to do so while using autoform?

**Comment by marktomm** [comment]
One way is: http://autoform.meteor.com/fieldvalues
