### ISSUE TITLE
Autovalue not added to form when formtype is "update-pusharray"

### ISSUE THREAD

**Issue by quisse** [Meteor-Community-Packages/meteor-autoform#1249]
Meteorpad: http://meteorpad.com/pad/5RSEtMwZpTFKkopMy/Autoform%20autovalue

I created a schema for tracks and each track can have comments. When adding comments to a track (by using a "update-pushArray" form with scope "comments"), the validation fails because the autoValue value are empty (see collection2.js line 357 invalidkeys "value: null". I don't know if this is a bug or if its just me?

Thanks in advance!

**Comment by quisse** [comment]
anyone?

**Comment by ShockiTV** [comment]
I am also facing this issue, I dont care about client side, but my use case is populating object with information based on zip_code. If I add new record to array autoValue runs and fill in correct info.
But when I update existing array field, autoValue function dont trigger at all.

**Comment by thebarty** [comment]
got a similar experience with type="method". Have you guys come up with a solution?
