### ISSUE TITLE
``AutoForm.getFieldValue`` in helper: problems after submit or error

### ISSUE THREAD

**Issue by thebarty** [Meteor-Community-Packages/meteor-autoform#1250]
Hi guys,

just for your info: it seems like `AutoForm.getFieldValue` looses it's reference to the view/template when being called from outside within a helper function.
I tested this in autoform 5.6 and 5.7.1.

I have a form-template where I want to dynamically show/hide elements.
This helper **does NOT WORK after I hit the submit button.**

```
Template.name.helpers{
  showElements: function() {
    // THIS IS BUGGY: it does NOT WORK after an submit or error event
    return AutoForm.getFieldValue('booleanFieldName', 'formId')
  }
}
```

As a workaround this **does work**, BUT I'd love to use a helper to keep it more readable: 

```
.html template
{{#if afFieldValueIs name='booleanFieldName' value=true}}
   // this one works, but I'd like to use a helper to keep it more readable
{{/if}}
```

**Comment by thebarty** [comment]
Summerized this is the current state:

1) When I write a custom helper (and use ``AutoForm.getFieldValue``) it DOES have problems AFTER hitting the SUBMIT button (just as described above). It then looses reference and I need to reload the page.
2) When I use ``afFieldValueIs``(in html template) it **does NOT show initial data onLoad**, BUT still shows data **correctly after hitting the SUBMIT button**.

**Comment by tcastelli** [comment]
+1
