### ISSUE TITLE
``afFieldValueIs`` does not seem to read default values from schema

### ISSUE THREAD

**Issue by thebarty** [Meteor-Community-Packages/meteor-autoform#1251]
Hi guys,

I have a form in `insert`-mode hooked up to a schema like this:
Within the template I want to show stuff depending on the `choice`.

**The problem is that within the template `afFieldValueIs` does NOT see the default value,
so altough "option1" is initially selected, `afFieldValueIs` acts as if it was NOT selected.**

**This happens when the form is `type=insert`.** It works correctly in `type=update` mode.

This is the schema:

```
  // Schema
  choice: {
    type: String,
    optional: false,
    allowedValues: ['option1', 'option2'],
    defaultValue: 'option1',
    autoform: {
      defaultValue: 'option1',  // force ui-element to show default-value
      afFieldInput: {type: 'select-radio-inline'},
    }
  },
```

Template:

```
{{#autoForm id='choiceForm' collection='Choices' type=insert doc=null}}

  {{> afQuickField name='choice'}}

  {{#if afFieldValueIs name='choice' value='option1'}}
    <!-- BUGGY: option1 is NOT shown initially, altough 'option1' is selected. I appears ONLY after clicking on 'option1' in the above choice-Field. -->
    option1
  {{/if}}
  {{#if afFieldValueIs name='choice' value='option2'}}
    <!-- option2 -->
    option2
  {{/if}}

{{/autoForm}}
```

**Any ideas how to fix this?**

**Comment by tcastelli** [comment]
+1

**Comment by obiwarn** [comment]
+1

**Comment by obiwarn** [comment]
I tried to circumvent this by using 
 AutoForm.getFieldValue
in a helper (as suggested somewhere else). But it didn't work either.

This is really bad for me. Since so far I had a preselected stored payment method for my customers.

Is there a workaround?
