### ISSUE TITLE
Meteor Session to Autoform

### ISSUE THREAD

**Issue by mikegani** [Meteor-Community-Packages/meteor-autoform#1255]
Hi Aldeed, 

First of thank you for creating the great autoform package! 

I am building a e-commerce website using meteor but I am currently stuck in building the check out page. I was wondering if you can help me on this.

Here are the steps I am thinking to build:
1) users click "add-to-cart" on items they're interested in
2) the items are populated in a string array on their browser Session.cart
3) users click "Pay Now" button to proceed to check out
![image](https://cloud.githubusercontent.com/assets/9816610/10573559/645ff2b2-767a-11e5-99f1-04b110a5263e.png)
4) users will be redirected to a check out html page which is an autoform to insert shipping details, payment details, and review the items. Their orders will be finally submitted to Order Mongo collection after they click the "Place Order" button.
![image](https://cloud.githubusercontent.com/assets/9816610/10573572/7692af6a-767a-11e5-9193-03b02751e7be.png)
Here is the Checkout html page where I wish I could programmatically loop the Session.cart and add the order array.
![image](https://cloud.githubusercontent.com/assets/9816610/10573426/9a3ccfdc-7679-11e5-8da5-6be7aadee63f.png)
I have tried calling (pseudo code):
Session.carts --> Array [ {sku,name,qt,price} ]
{{#each Session.carts}}
   {{> afQuickField name="Schema.order.orderList" doc=this}}
{{/each}}

But this doesn't work. Do you have any guidance for me?

Thanks,

Michael

**Comment by seanfcarroll** [comment]
I'm not really sure how to help, but perhaps this would be better logged in StackOverflow or the Meteor forums?
