### ISSUE TITLE
afFormGroup label- prefix does not seem to apply attribute when using boolean-checkbox type

### ISSUE THREAD

**Issue by aghalarp** [Meteor-Community-Packages/meteor-autoform#1261]
```
{{> afFormGroup name="someName" type="boolean-checkbox" formgroup-class="someClass" label-class="anotherClass"}}
```

This should add "anotherClass" to the class attribute of the form label, but it does not seem to.
Interestingly though, the formgroup- prefix seems to work just fine. It will properly add "someClass" to the wrapping formgroup div's class attribute.

**Comment by bySabi** [comment]
it seen related to this: https://github.com/aldeed/meteor-autoform/issues/869

`label-class`only can use, on aldeed words, "label-class is only for setting the column classes on horizontal theme."
