### ISSUE TITLE
String array not removing strings that are deleted from the top of the list

### ISSUE THREAD

**Issue by mi1971** [Meteor-Community-Packages/meteor-autoform#1263]
Hi. If I use a quick field for an array of strings, the automatic form fields allow adding and deleting of strings for the field. If a string is deleted from the top of the list, it reappears in the list again as a blank string, so it appears that it cannot be removed. Is this a bug?

See quick sample video

https://youtu.be/_8VaH_ukupE

**Comment by xhh** [comment]
having the same issue, any plans on the fix?
