### ISSUE TITLE
Error not pushed to UI, getting Error Invalid [400] instead

### ISSUE THREAD

**Issue by xpluscal** [Meteor-Community-Packages/meteor-autoform#1267]
Hi!

Im trying to update the User Profile when the user submits a request but I dont see the Validation Errors pushed to the UI. Instead I get the following error:

``` javascript

errorClass {error: 400, reason: "INVALID", details: "[{"name":"profile.gender","type":"required","value":null}]", message: "INVALID [400]", errorType: "Meteor.Error"}details: "[{"name":"profile.gender","type":"required","value":null}]"error: 400errorType: "Meteor.Error"message: "INVALID [400]"reason: "INVALID"stack: (...)get stack: ()set stack: ()__proto__: Middle

```

When signing up, not all the Profile Details will be inserted, so I made them optional on insert with this function:

``` javascript

profile: {
        type: Schema.UserProfile,
                optional: function() {
            return this.isInsert
        }
},

```

So when a validation on a field on update fails, I only receive this error.
Any help is highly appreciated.

Cheers

**Comment by drtomasso** [comment]
I'm experiencing similar problem when using simple-schema and autoform for `Meteor.users` collection (used on a "my profile"-page). On other pages and collection, is displays the errors correctly in the form.

```
errorClass {error: 400, reason: "INVALID", details: "[{"name":"emails.0.address","type":"regEx","value":"user@fake"}]", message: "INVALID [400]", errorType: "Meteor.Error"}
```
