### ISSUE TITLE
afFieldInput Radio controls do not call Custom function in Update Mode

### ISSUE THREAD

**Issue by aadamsx** [Meteor-Community-Packages/meteor-autoform#1270]
The basic problem is, for radio controls only, on insert the custom function in the schema runs fine, but on update, it never runs -- no matter what I put in the custom.  At first I thought maybe it doesn't run in update mode if somehow the custom conditions are not met, but even if I just return a 'required', it sill will not run.  

For all other types of controls custom runs as it should in update mode.

A simple 'select-radio' afFieldInput:

```
{{> afFieldInput name=name type="select-radio-inline" class=classes}}
```

In my schema, my radio control looks like this, and runs the custom function if I'm inserting:

```
  radioControlTest1: {
    type: String,
    optional: true,
    autoform: {
      options: function () {
        return [
          {label: "Yes", value: "Yes"},
          {label: "No", value: "No"}
        ];
      }
    },
    custom: function () {
      if (Meteor.isClient) {
        if ((this.field("otherControl").value === "Yes")
          && (this.value === null || this.value === "" || this.value === undefined)) {
            return "required";
          }
      }
    },
    defaultValue: null
  }
```

The radio control custom runs if the form is in insert mode; and if 'otherControl' value is 'Yes' and 'radioControlTest1' value is not set, the 'required' string is returned as it should. 

If the form is in update mode, custom will not run no matter what is inside.  

For the form, I'm passing in the doc and type like so:

```
{{#autoForm collection="testCollection" id="testCollectionForm" doc=doc type=type class="form-horizontal" }}
 ... controls inside ...
{{/autoForm}}
```

In the same schema, this input control custom function will run in both modes:

```
  inputControlTest1: {
    type: String,
    optional: true,
    max: 32,
    custom: function () {
      if (Meteor.isClient) {
        if ((this.field("otherControl").value === "Yes")
          && (this.value === null || this.value === "" || this.value === undefined)) {
            return "required";
          }
      }
    },
    defaultValue: null
  },
```

aldeed:autoform               5.4.0
aldeed:autoform-select2       2.0.2
aldeed:collection2            2.3.3
Meteor 1.1.0.3

I found this issue to be occurring in v5.7.1 too.

**Comment by VobyD** [comment]
aldeed:autoform@5.7.1
aldeed:autoform-bs-datetimepicker@1.0.6
aldeed:autoform-select2@2.0.2
aldeed:collection2@2.5.0
aldeed:simple-schema@1.3.3
aldeed:template-extension@3.4.3

Meteor 1.2.1

When i set type as 'select-radio' in update form, values never cheked(with native checker).
```
{{#autoForm id="editContractorModalForm" collection="Contractors" type="update" doc=.}}
.............
 {{> afQuickField name ="status" template="bootstrap3-horizontal" options="allowed" type="select-radio"}}
.............
{{/autoform}}
```
in Schema definition(coffeescript):
  status:
    type: String
    label: 'Status'
    allowedValues:[
      'One',
      'Two',
      'Three',
      'Four']


In insert form all ok.
