### ISSUE TITLE
Adding an updatedAt field to the user collection results in a 403 Access denied message

### ISSUE THREAD

**Issue by derwaldgeist** [Meteor-Community-Packages/meteor-autoform#1276]
I want to track changes on the users. Hence, I've set-up an updatedAt field at the user collection schema:

``` js
updatedAt: {
    type: Date,
    autoValue: function() {
      return new Date();
    },
    optional: true,
    autoform: {
      omit: true
    }
  }
```

This works for normal updates and inserts. But if I use an autoform to fill-out the user profile, I get an "Access denied [403]" message in the client console (the server does not print out an error log).

This does not occur if I remove the autoValue(), so this seems to be the root cause.

**Comment by gabrielem** [comment]
+1

**Comment by kwuite** [comment]
+1

defaultValue will not solve this problem but will only guarentee a single update on the field which breaks the reason for adding an updatedAt field.

Made an issue in the collection2-core project: https://github.com/aldeed/meteor-collection2-core/issues/27
