### ISSUE TITLE
BUG: ``{{#autoform}}`` looses css-styles when used in combination with ``Template.dynamic``

### ISSUE THREAD

**Issue by thebarty** [Meteor-Community-Packages/meteor-autoform#1282]
Hi guys,

I am pretty sure that I found a bug in autoform: When using `{{#autoform}}` in combination with `Template.dynamic` (to load it's dynamic content), the form itself starts to look really weird - it seems like it is loosing some css styles.

This is a **screenshot of the bug-demo**:
![autoform dynamic loading](https://cloud.githubusercontent.com/assets/3011897/10998547/22099754-8496-11e5-9197-9275afc99a44.png)

This is how you can reproduce this:

``` bash
meteor create test;
meteor add aldeed:autoform;
meteor add aldeed:collection2;
meteor add twbs:bootstrap;
meteor update;
```

This is the js file:

``` js
Books = new Mongo.Collection("books");
Books.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  author: {
    type: String,
    label: "Author"
  },
  copies: {
    type: Number,
    label: "Number of copies",
    min: 0
  },
  lastCheckedOut: {
    type: Date,
    label: "Last date this book was checked out",
    optional: true
  },
  summary: {
    type: String,
    label: "Brief summary",
    optional: true,
    max: 1000
  }
}));

if (Meteor.isClient) {
  AutoForm.debug();
}

if (Meteor.isServer) {
}
```

this is the html:

``` html
<head>
  <title>autoform-dynamic-loading</title>
</head>

<body>
  {{> test}}
</body>

<template name="test">
  <h1>Autoform with dynamic loading</h1>
  <div>
    {{#autoForm collection="Books" id="insertBookForm" type="insert"}}
      {{! BUG: FORM STARTS TO LOOK BUGGY!!}}
      <h2>"Template.dynamic" (BUGGY)</h2>
      {{>Template.dynamic template="dynamicTemplate"}}

      <hr/>

      <h2>"Direct template inclusion" works correctly:</h2>
      {{>dynamicTemplate}}
    {{/autoForm}}
  </div>
</template>

<template name="dynamicTemplate">
  <fieldset>
    <legend>Add a Book</legend>
    {{> afQuickField name='title'}}
    {{> afQuickField name='author'}}
    {{> afQuickField name='summary' rows=6}}
    {{> afQuickField name='copies'}}
    {{> afQuickField name='lastCheckedOut'}}
  </fieldset>
  <button type="submit" class="btn btn-primary">Insert</button>
</template>
```

Am I doing something wrong here?

**Does anyone know a workaround?**

**Comment by mazing** [comment]
+1

**Comment by ddanna** [comment]
+1

**Comment by ddanna** [comment]
my work around was to manually add ```class='form-control' ``` to the afQuickField in the dynamic templates

**Comment by ababba15** [comment]
Yes, I have the same problem.

**Comment by solace** [comment]
+1

**Comment by solia** [comment]
+1

**Comment by aaronjudd** [comment]
Probably broken because the variable that autoform uses is: ` template="bootstrap3"` and the dynamic templates use the `template=` variable to specify the dynamic template...

**Comment by marcuswubi** [comment]
I know that the bug exist yet, but as an alternative you can use some CSS to make it work.

`     .dataTables_length select,
      .dataTables_filter input {
        display: block;
        width: 100%;
        height: 30px;
        padding: 5px 10px;
        font-size: 13px;
        line-height: 1.42857143;
        color: #555;
        background-color: #fff;
        background-image: none;
        border: 1px solid #ccc;
        border-radius: 4px;
        -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
        -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        -o-transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
        transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
      }`
