### ISSUE TITLE
X-editable in AutoFrom

### ISSUE THREAD

**Issue by ashishapy** [Meteor-Community-Packages/meteor-autoform#1297]
Hi,
I am looking to implement X-editable (http://vitalets.github.io/x-editable/ ) as template with AutoForm. Demo of X-editable forms here (http://vitalets.github.io/x-editable/demo-bs3.html?c=inline)

How can I achieve it with quickform/autoform ? Help.

**Comment by leizard** [comment]
Hi, I have the same need too. Any progess on this ?
