### ISSUE TITLE
Select firstOptions as reactive function 

### ISSUE THREAD

**Issue by MartinBucko** [Meteor-Community-Packages/meteor-autoform#1315]
Hi,
"firstOption" in Select field can be defined as only string type. I think we need to allow define also as function for reactivity. For example it is not possible to translate "(Select one)" with meteor-autoform-i8n package.

Reference code:
https://github.com/aldeed/meteor-autoform/blob/devel/inputTypes/select/select.js#L29

Many thanks for fix!

**Comment by takahser** [comment]
I'm not sure if it's the right place for this, if not I apologize.

I have 2 collections `Categories` and `SubCategories` which can be set using select options.
Now, the values `SubCategories` to be displayed depend on the already selected `Categories` item.
I define the schema as follow:

    category: {
        type: String,
        optional: true,
        autoform: {
            options: function () {
                return ObjectCategories.find().map(function(c) {
                    return {label: c.name, value: c.code}
                });
            }
        }
    },
    subCategory: {
        type: String,
        optional: true,
        autoform: {
            options: function () {                
                var docId = AutoForm.getFieldValue('category');
                
                // TODO: pre-select currently stored sub category on update form
                
                return Subcategories.find({code: docId}).map(function(c) {
                    return {label: c.german, value: c.nr}
                });              
            }
        }
    },

While this works for the `insert` autoform, it won't pre-select any value for the `SubCategories` for the `update` autoform. How can I fix this?
