### ISSUE TITLE
remove asterisk form radio option

### ISSUE THREAD

**Issue by macroramesh6** [Meteor-Community-Packages/meteor-autoform#1322]
I have an autoform with select-radio-inline' type. the required asterisk shows in all the options. I want to remove it from the radio box. How to achieve?

![screenshot-localhost 3000 2015-12-17 13-49-08](https://cloud.githubusercontent.com/assets/1827233/11867013/9a5fd9e4-a4d4-11e5-9185-fa15589ec229.png)

Here my schema:

```
name: {
  type: String,
  autoform: {
    type: 'select-radio-inline',
    label: "Sex",
    afFieldInput: {
      options: function() {
        return [{
          label: "male",
          value: "male"
        }, {
          label: "female",
          value: "female"
        }];
      }
    }
  }
}
```

**Comment by aldeed** [comment]
Maybe

```
[data-required] > label:after {content: '*'}
```
