### ISSUE TITLE
How to set custom error message with addStickyValidationError()?

### ISSUE THREAD

**Issue by renehernandez** [Meteor-Community-Packages/meteor-autoform#1338]
When the form process the error it shows the following sticky message: 
"Unknown validation error"

Even if I put some value as third parameter in the addStickyValidationError call it doesn't change anything.

Any idea how to deal with this?

Thanks in advance

onError hook code:

``` javascript
onError: function(formType, err) {
            var self = this;

            if(err){
                if(err.reason){
                    if (err.reason.indexOf('User') > -1){
                        self.addStickyValidationError('email', 'notFound');
                    }
                    else if (err.reason.indexOf('password') > -1){
                        self.addStickyValidationError('password', 'invalid');
                    }
                }

                AutoForm.validateForm(self.formId);
            }
        }
```

**Comment by jclay** [comment]
I just ran into this issue as well and managed to track down what is going on.

Let's say you have a snippet like this that you're using to notify that user that they're trying to create an account with a duplicate email:
```javascript
AutoForm.hooks({
  insertUser: {
    onError: function (formType, error) {
      if (error.errorType && error.errorType === 'Meteor.Error') {
        console.log(error)
        if (error.reason.match(/exists/)) {
          AutoForm.addStickyValidationError(this.formId, 'email', 'duplicate');
        }
      }
    }
  }
});
```

Our error type is set to `duplicate`. Tracking down the way this is handled reveals that `messageForError` in `SimpleSchema` is eventually called. [Here](https://github.com/aldeed/meteor-simple-schema/blob/11a688d64eb16db570dc534c531500a12e916ac1/simple-schema.js#L960), we can see that it searches for the `errorType` in it's list of known types to try and resolve it to a message. If it cannot find one that matches, this gets called:

```javascript
  if (!message) {
    return "Unknown validation error";
  }
```

The documentation mentions that we can create custom error types [here](https://github.com/aldeed/meteor-simple-schema#customizing-validation-messages).

Now, we see that adding this message to our Schema should solve our problem (and it does!):
```javascript
Schema = {};
Schema.user = new SimpleSchema({
    email: {
        type: String,
        optional: false
    },
    password: {
        type: String,
        optional: false
    }
});

Schema.user.messages({
  "duplicate email": "You're trying to use an email that already exists."
})
```

It's not very clear that this is required from the `auto-form` documentation, so I will look into a fix.
