### ISSUE TITLE
AutoForm.getFieldValue gets wrong data

### ISSUE THREAD

**Issue by sylvix** [Meteor-Community-Packages/meteor-autoform#1344]
Hi!
At first, let me thank @aldeed for his great package. We're using it in our project a lot.
But I encountered a problem while trying to get some advanced functionality working.

Basically, when you call `AutoForm.getFieldValue()` with field name which is a field of an object in an array, it returns wrong value when some of the items in the form are removed.

It returns value based on cleaned form data which removes empty values from an array. But template is not modified when you remove items, and names of fields remain.

For example, you have 5 items in array, and you remove one element in the form (pressed "-" button) at index 2. Then you have templates that have field names containing 0, 1, 3, 4. But the cleaned data is 0, 1, 2, 3. When you try to get value for a field that is indexed at 3, you'll get fourth value.

I've created a demo repository that displays the bug:
https://github.com/sylvix/demo-autoform-getfieldvalue-bug
Demo of it is available here: http://autoform-getfieldvalue-bug.meteor.com/

For now I use workaround which just gets the data of corresponding field, finding it among siblings of current element, but it leads to unnecessary additions to code. I'd wanted to use just the AutoForm API.

If I am utterly wrong, or I'm not using some obvious method to get the data, please point me in the right direction.

Thanks!

**Comment by Sojourneer** [comment]
+1
getFieldValues(xxx.n.yyyy) uses the actual current value for "n" to index the array.
However, "this.current" uses the index before the deletion, so the names don't match.

**Comment by dladiguna** [comment]
+1
