### ISSUE TITLE
Combo Box

### ISSUE THREAD

**Issue by BackSpaceTech** [Meteor-Community-Packages/meteor-autoform#1357]
Any way I can implement a combo box to allow for selecting from either a list or text input instead?
Something like:
https://jqueryui.com/autocomplete/#combobox

**Comment by lmaddio** [comment]
You can use something like this:

`autoform: {`
	`   options: function () {`
	       `     return Collection.find().map( function(d, i, c){`
	       `     return {label: d.name, value: d.name};`
	    `    });`
	`   }`
`  }`
