### ISSUE TITLE
quickform default button

### ISSUE THREAD

**Issue by prakas25** [Meteor-Community-Packages/meteor-autoform#1375]
can change the default submit button's(of quickform) position(which is extreme left)?

**Comment by Tim-W** [comment]
I'd suggest using the {{#autoForm}}{{/autoForm}} helper and write your own submit button. You could also set the "buttonClasses" parameter on quickForm and use CSS to move the button more to the right.
Checkout the buttonClasses documentation: https://github.com/aldeed/meteor-autoform#quickform
