### ISSUE TITLE
Executing getFieldValue in a helper that is setting a field value fails if the form also contains a datetimepicker

### ISSUE THREAD

**Issue by puddicombe** [Meteor-Community-Packages/meteor-autoform#1376]
`<input type="text" class="form-control" value={{clientName}} disabled>`

refers to helper clientName, which itself uses AutoForm to read the value for a different part of the form:

`var clientId=AutoForm.getFieldValue("client_");`

but this errors because a different field on the form uses datetimepicker and has yet to be rendered:

> Exception in template helper: TypeError: Cannot read property 'getDate' of undefined
>     at AutoForm.addInputType.valueOut (http://192.168.2.189:3000/packages/aldeed_autoform-bs-datetimepicker.js?11323374fa5ee2f1f864b4cb66a6df51cfbb2cd3:88:40)
>     at Object.autoFormGetInputValue [as getInputValue](http://192.168.2.189:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:2277:28)
>     at HTMLInputElement.<anonymous> (http://192.168.2.189:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:1515:35)
>     at Function.jQuery.extend.each (http://192.168.2.189:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:410:23)
>     at jQuery.fn.jQuery.each (http://192.168.2.189:3000/packages/jquery.js?1015953f785c9b76503e2ecb391507dce965f357:162:17)
>     at getFlatDocOfFieldValues (http://192.168.2.189:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:1514:10)
>     at Object.autoFormGetFormValues [as getFormValues](http://192.168.2.189:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:2075:11)
>     at Object.autoFormGetFieldValue [as getFieldValue](http://192.168.2.189:3000/packages/aldeed_autoform.js?b3aa1a45a8c57d1da1124520538d2cb9fa458509:2190:22)
>     at Object.Template.enquiry.helpers.clientName (http://192.168.2.189:3000/app/client/templates/enquiry.js?86f4df7bd2ea3a3859664207f73105e6a10d405b:39:33)
>     at http://192.168.2.189:3000/packages/blaze.js?9391df93ba5076c2cfc61ee68724eb79b65f00d9:2986:16

**Comment by serkyen** [comment]
Hey @puddicombe, 
Did you find a solution to this issue?
Thanks
