### ISSUE TITLE
allowed values doesn't work

### ISSUE THREAD

**Issue by janat08** [Meteor-Community-Packages/meteor-autoform#1383]
{
  favoriteColor: {
    type: String,
    allowedValues: ['red', 'green', 'blue']
  }
}

This is trash it would appear at which point you're almost doing as much work doing things "manually"

**Comment by Tim-W** [comment]
What is the issue? Please explain...

**Comment by janat08** [comment]
Apparently using this syntax, I put space after each value at which point it wouldn't accept any of the options as allowed values since these spaces where lost in translation.

**Comment by janat08** [comment]
Also had a label there.
