### ISSUE TITLE
Plan to support React JS?

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-autoform#1395]
Now I try to use `Meteor 1.3, React on Mantra`.
`AutoForm` plan to support React JS or Not?
Should I waiting `AutoForm React` or using `React Form Pakcage`?

**Comment by evilboss** [comment]
+1

**Comment by anderson916** [comment]
+1

**Comment by adriancbo** [comment]
+1

**Comment by cyclops24** [comment]
Guys you can use https://github.com/vazco/uniforms it also support simple schema.
