### ISSUE TITLE
Hidden, optional, blackbox field causing quickform generated update form not to submit.

### ISSUE THREAD

**Issue by termax** [Meteor-Community-Packages/meteor-autoform#1418]
{{> quickForm collection="TwitterAccounts" doc=this id=formId type="update"}}

AccountsSchema = new SimpleSchema({
    login: {
        type: String,
        label: "Twitter Login",
        index: true,
        unique: true,
        sparse: true
    },
    pass: {
        type: String,
        label: "Twitter Pass"
    },
    email: {
        type: String,
        label: "User e-mail"
    },
    emailPass: {
        type: String,
        label: "Email Pass"
    },
    status: {
        type: String,
        label: "User status"
    },
    used: {
        type: Number,
        optional: true,
        autoform: {
            type: "hidden"
        }
    },
    phoneNumber: {
        type: String,
        label: "User Phone Number (optional)",
        optional: true
    },
    data: {
        type: Object,
        blackbox: true,
        optional: true
        //autoform: {
        //    type: "hidden"
        //}
    }
});

When i comment out the autoform type hidden it works. When data filed is hidden and debug mode on i get this error : 

SimpleSchema invalid keys for "AccountUpdateForm-5kzAMKpPiBZKCYw8T" context: [Object]0: Objectname: "data"type: "expectedObject"value: "[object Object]"**proto**: Object__defineGetter__: **defineGetter**()**defineSetter**: **defineSetter**()**lookupGetter**: **lookupGetter**()**lookupSetter**: **lookupSetter**()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get **proto**: get **proto**()set **proto**: set **proto**()length: 1__proto__: Array[0]

**Comment by soitech** [comment]
I was able to get rid of these errors by replacing 
```
autoform:{
    type:"hidden"
}
```
with
```
autoform:{
    omit:true
}
```

**Comment by paulina-grunwald** [comment]
I still have error using above mentioned syntax. any ideas how o solve it in 2018 versions?

**Comment by chrobakos** [comment]
According to meteor-autoform documentation
( https://github.com/aldeed/meteor-autoform#quickform )

You should not define hidden fields in simple schema anymore, but at the place where you generate the quickForm.

you can define either fields you want to show up:
`{{> quickForm collection="Recipes" id="insertRecipeForm" type="insert" class="new-recipe-form" fields="name,description"}}`

or fields you want to hide:
`{{> quickForm collection="Recipes" id="insertRecipeForm" type="insert" class="new-recipe-form" omitFields="author,createdAt"}}`
