### ISSUE TITLE
ELSE or afFieldValueIs value!= (deferent)

### ISSUE THREAD

**Issue by neutron92** [Meteor-Community-Packages/meteor-autoform#1427]
Please i want to know how to do else or afFieldValueIs value!= (deferent) in the autoform

**Comment by hich-em** [comment]
i found it 

it works
{{#if afFieldValueIs name="parent_account" value="0"}}

{{else}}

 {{/if}}

**Comment by seanmavley** [comment]
Blaze has the {{# unless }} tag, if that's what you're looking for.
