### ISSUE TITLE
Manually override 'optional' schema parameter from afFieldInput inclusion

### ISSUE THREAD

**Issue by mynameiskyleok** [Meteor-Community-Packages/meteor-autoform#1435]
I would like to be able to manually override a field's optional parameter on the simple-schema definition from the field afFieldInput inclusion, like so:

schema:

``` javascript
email: {
  type: String,
  optional: true,
  autoform: {
    afFieldInput: {
       type: "email"
    }
  }
},
```

Field definition:

``` javascript
{{> afFieldInput name="email" optional=false}}
```

I would like to create a single schema that multiple autforms use; however, not every autoform uses every field. The only way to accomplish this is to make every field defined in the schema as optional:true, but be able to override it from the front end based on a parameter passed. 

I'm building a large application with many forms and fields and this approach of having a single schema definition for all the forms will allow me to reuse as many fields as possible without duplication for the forms that use the same fields (e.g., email).

**Comment by rgnevashev** [comment]
+1

**Comment by felipesmendes** [comment]
+1

**Comment by ddiazUNSJ** [comment]
Interesant, I would like if you have been able you to get results with this idea, because I start working with  software product lines on meteor js and it is a case of variability implementation. 
Thank in advance
