### ISSUE TITLE
Seprate panel title for nested objects in quickForm

### ISSUE THREAD

**Issue by cyclops24** [Meteor-Community-Packages/meteor-autoform#1437]
Hi @aldeed,
I have below schema:

```
this.Schemas.Poll = new SimpleSchema({
    question: {
        label: "Question",
        type: String
    },
    options: {
        label: "Options",
        type: [Object],
        minCount: 1,
        maxCount: 4
    },
    "options.$.text": {
        label: "Option Text",
        type: String
    },
    "options.$.answersBy": {
        type: [String],
        defaultValue: [],
        autoform: {
            omit: true
        }
    }
});

```

It create form for me well with quickForm but I have a little UI issue.
In quickForm output, title of childs object always equal with parent label but I want to use separate panel title for each childs. I need more clear title for each object for example "Option" for all or more better if we can use index of each object for example "Option 1", "Option2", ...

Please see below image for more clear information:

![autoform panel title](https://cloud.githubusercontent.com/assets/8266479/14355497/615eb640-fcf6-11e5-8e24-a6d9368007b5.png)

Excuse me for my bad English.
Thanks for your attention.

**Comment by cyclops24** [comment]
I finally handle this in CSS like below:

```
ul.list-group {
    counter-reset: array-index;
}
.autoform-array-item-body>.panel.panel-default>.panel-heading>h3.panel-title:after {
    content: counter(array-index);
    counter-increment: array-index;
}
```
It convert inner object panel title to "Option 1", "Option 2", ...
But I think that if it's possible to handle this by autoform it's more better.
@aldeed If you have any suggestion I'm here to know.

Thanks for your attention.

**Comment by gwendall** [comment]
+1
