### ISSUE TITLE
Pass mongodb object id to autofrom

### ISSUE THREAD

**Issue by ivan133** [Meteor-Community-Packages/meteor-autoform#1448]
I have a form with auto update. 

```
        {{#autoForm id="actFilterForm" collection="ServicesList" type='update' doc=this schema="ServicesListSchema" autosave=true}}
            {{> afQuickField name='_id' type="hidden" value=_id}}
            {{> afQuickField name='String'}}
        {{/autoForm}}
```

My schema looks like this

```
@ServicesListSchema = new SimpleSchema
  _id:
    type: Meteor.Collection.ObjectID
  custom_services_ids:
    type: [String]
    optional: true
    autoform:
      afFieldInput:
        multiple: true
      options: ->
        clinicId = AutoForm.getFieldValue('clinic_id')
        _id = AutoForm.getFieldValue('_id')
        if clinicId
          ServicesList.find(clinic_id:  clinicId, status: 'DONE', _id: $ne: _id).map (el) ->
            label: el.invoice_number
            value: el._id.toHexString()
        else
          []
```

I need current objectId in options to filter it from results so I added field _id to my schema.
I work with native mongo ObjectIDs.
First time this works, but after first autoupdate it breaks. Just stop updating.
If I look at html form with dev-tools I see
`<input type="hidden" value="ObjectID(&quot;570e411e0253f3280e49933c&quot;)" name="_id" required="" data-schema-key="_id">`
Is it a bug? Or maybe I'm wrong somewhere?

**Comment by shyal** [comment]
This is a contentious subject, and one of the reasons many developers are feeling away from MeteorJS. Lack of interoperability between string ids and native MongoIDs is a big show stopper for a lot of people in the community.
