### ISSUE TITLE
Show empty array closed

### ISSUE THREAD

**Issue by perusopersonale** [Meteor-Community-Packages/meteor-autoform#1450]
Maybe it's a very easy question, but I can't find a solution. I have an array field.
I'm displaying it using quickForm, the problem is that when the array is empty, I see the first element open with all the field empty (it is a very long form), I'd like to only see the plus icon. How can I achieve this?

**Comment by stefanve** [comment]
Did you find a way to show it closed? It is quite annoying since they take up a lot of space

**Comment by stefanve** [comment]
Found it:
 {{> afQuickField name="attachments" initialCount=0}}

You can also set that in the schema:

` attachments: {
        type: Array,
        optional: true,
        autoform: {
            initialCount: 0
        }
    },`
