### ISSUE TITLE
date value disappears once we click on add-on-button 

### ISSUE THREAD

**Issue by sairamdevarashetty** [Meteor-Community-Packages/meteor-autoform#1452]
schema related to the error mentioned :

`{
   items: {
      type: Array,
      optional: true,
      minCount: 0,
      maxCount: 5
 },
   "items.$": {
      type: Object,
      optional: true
   },
   "items.$.name": {
      type: String,
      optional: true,
      autoform: {
         afFieldInput: {
            type: "bootstrap-datetimepicker"
         }
      }
   }
}`

![datetimpickerissuecreate](https://cloud.githubusercontent.com/assets/12096450/14779103/0f7c589e-0af4-11e6-86bd-5ca0730d2fc3.gif)

**Comment by devarashetty** [comment]
@aldeed please check over this once

**Comment by thearabbit** [comment]
I have the same too for `select2`.
+1
