### ISSUE TITLE
AutoForm.resetForm doesn't work

### ISSUE THREAD

**Issue by epileptic** [Meteor-Community-Packages/meteor-autoform#1459]
Hello,

I'm trying to reset the validation of a form after an unsuccessful submit, but it's not working. I'm doing `AutoForm.resetForm('#myForm')`. The error messages on the invalid fields are still there after the call. How can I get rid of them all?

**Comment by Harry97** [comment]
Try removing the '#' and type in the id straight away. `AutoForm.resetForm('myForm')`
