### ISSUE TITLE
autoform.omit doesn't seem to work

### ISSUE THREAD

**Issue by demiters** [Meteor-Community-Packages/meteor-autoform#1460]
I have the following field in my schema:

```
  notes: {
    type: String,
    label: 'Admin Notes',
    optional: true,
    autoform: {
      omit: function(){
        return !_.contains(Meteor.user().roles, 'admin');
      }
    }
  }
```

I have checked that the omit function returns false for admin and true for everyone else but the field is still always visible to everyone, what could be the reason?

**Comment by mozfet** [comment]
I can confirm this is still not working in v6.3.0. The function is executed, but the result is ignored when its true... and the field is always shown. I would so love this to work reactively.

Becuase I dynamically generate schemas, I have to contain all autoform logic in schemas (which are generated procedurally from my database) and thus template based solution do not help...
