### ISSUE TITLE
Enable/disable autoform fields based on user roles.

### ISSUE THREAD

**Issue by itsaks3** [Meteor-Community-Packages/meteor-autoform#1467]
I want to set some user roles to Add/edit the records so based on the user roles i need to disable/enable some autoform fields.
I have tried to check user roles while creating the schema to disable the form field but no success.
Please guide me how i can disable the form fields accordingly user roles.

Thanks.

**Comment by mibcadet** [comment]
+!

**Comment by johnmarty** [comment]
I just did something similar for super-admin fields. Nice for debug purposes but in the way for normal users.

Step 1. Identify the fields with a class in the schema eg:
```
adminData:
    autoform:
      class: 'super-admin-field hide'
```
Step 2. Hide the fields using jquery from the Template.name.onRendered hook eg:
```
      if (!Roles.userIsInRole(Meteor.userId(), 'super-admin')) {
        $('.super-admin-field').each(function() {
          // parent is expected to be a .form-group container
          $( this ).parent().addClass('hide');
        });
      }
```
