### ISSUE TITLE
Submit button will not work

### ISSUE THREAD

**Issue by dmkaner** [Meteor-Community-Packages/meteor-autoform#1477]
I am using a couple of packages in a meteor web app, including aldeed:autoform and aldeed:collection2. Together I made a schema and attached it to a database. I then auto generated a form for it, which includes a submit button. The submit button worked perfectly when I first generated it, but not when I run my meteor app, the submit button does nothing. I checked the git linked to the folder and it doesn't look like there have been any changes made that would effect this. I'm not sure what to do, any help would be great. (PS I've tried debugging it and no errors were there, and I also saw on the troubleshooting that if this was the case then check the syntax, but everything seems to be fine)

**Comment by raphaelalejandro** [comment]
I had a similar issue - in the end it turned out it was because I added a the 'check' package (which you don't actually need to add).

Best advice would be to check your packages/changes you made there.
