### ISSUE TITLE
Extending Mongo.Collection causes issues

### ISSUE THREAD

**Issue by ExcelNet-Public** [Meteor-Community-Packages/meteor-autoform#1480]
There are two issues that I have observed, first a **quickForm** of type **insert** will insert the record, but never seems to have the button become "unghosted".  Second and I am certain related this will then cause hooks not to be fired.  The most basic example of this would be:

```
class NewCollection extends Mongo.Collection {
  constructor(collectionName) {
    super(collectionName);
  }

  insert(list, callback) {
    // Allows for insert logic / massaging here
    return super.insert(list, callback);
  }

  remove(selector, callback) {
    // Useful here to potentiall remove relationship items
    return super.remove(selector, callback);
  }
}
export const NewCollection = new NewCollection('NewCollection');

```

This does NOT work, but change the last line to:

`export const NewsPosts = new Mongo.Collection('NewsPosts');
`

Then it works fine and hooks are called.

**Comment by kibao** [comment]
If you are using collection2 pkg with SimpleSchema then insert method gets 3 arguments.

Look at the source of `insert` form type 
```
      // Perform insert
      if (collectionHasSchema) {
        // If the collection2 pkg is used and a schema is attached, we pass a validationContext
        collection.insert(doc, c.validationOptions, c.result);
      } else {
        // If the collection2 pkg is not used or no schema is attached, we don't pass options
        // because core Meteor's `insert` function does not accept
        // an options argument.
        collection.insert(doc, c.result);
      }
```

so your overridden `insert` method should be get three arguments and then pass them to `super.insert` .
