### ISSUE TITLE
this.docId is null after inserting a document

### ISSUE THREAD

**Issue by Bandit** [Meteor-Community-Packages/meteor-autoform#1505]
I'm using a method in AutoForm (version 5.8.1) for the insertion. Is this something to do with client vs server method simulation perhaps?

`{{#autoForm collection=staff id="insertStaffForm" type="method" meteormethod="staff.insert" }}`

I've got an onSuccess hook setup:

```
AutoForm.addHooks('insertStaffForm', {
    onSuccess: function staffSuccess(formType, result) {
      console.log(this);
    }
});
```

The output of `this` from the hook:

```
currentDoc: undefined
docId: null
insertDoc: Object
```

`insertDoc` is fine and has all the details of the inserted document. Checking Mongo the document is correctly inserted.

Any ideas?

**Comment by anderoy** [comment]
I had a the same issue and it took some digging. But I was able to get the _id of the newly inserted item by using the result from the after: property in the hook. This also required me to return what was inserted from the method. (Sorry my coding language game is not so strong).

To add to the hook:
```
after: {
      method: function(error, result) {
        console.log(result);  //should display the inserted docs _id
    }
  },
```

Make sure the method returns the insert result:
```
insertCollection:function(doc){
  if (!this.userId){
    return;
  }
  else {
    return Collection.update(doc);
  }
},
```
If you don't include the return, the insert will still work but the after: property in the hook will not have the _id to use in the client.
```
insertCollection:function(doc){
  if (!this.userId){
    return;
  }
  else {
    Collection.update(doc);
  }
},
```

**Comment by currychern** [comment]
Thanks @anderoy, your solution worked! I had the same issue as @Bandit, the document was successfully inserted, but I couldn't get the document id. I was missing the return statement in my method.

The following worked for me:

`{{#autoform collection=staff id="insertStaffForm" type="method" meteormethod="staff.insert" }}`

With the onSuccess hook using the result:

```
AutoForm.addHooks('insertStaffForm', {
	onSuccess: function(formType, result) {
		console.log(result);
	}
});
```

And the staff.insert method using the return statement:

```
export const insert = new ValidatedMethod({
	name: 'staff.insert',
	validate(args) {
		Staff.simpleSchema().validate(args);
	},
	run(args) {
		return Staff.insert(args);
	}
});
```

**Comment by frankwo1** [comment]
Hi,
This string is a bit old but I'm having a problem where the Autoform.addHooks no longer returns the _id of the new item on the after: hook --- may be a problem starting with 1.8. Does insert into the collection but returns an error indicating there is no id

Autoform is pretty standard
                    {{#autoForm id="taskNew" collection="Tasks" doc=task type="insert" }}{{>taskFields}}
                        <div>
                            <button type="submit" class="btn btn-primary"> Continue to post</button>
                        </div>
                    {{/autoForm}}

My Hook
AutoForm.addHooks('taskNew', {
  after: {
    insert: function(error, result) {
      if (error) {
        console.log("Insert Error:", error);
      } else {
        analytics.track("Task Created");
        Router.go('task', { _id: result });
      }
    }
  }
});

any insights on how to get Autoform to return id
