### ISSUE TITLE
*** Is this project dead or does it just needs maintainers ? ***

### ISSUE THREAD

**Issue by gregory** [Meteor-Community-Packages/meteor-autoform#1508]
I've seen a lot of open issues & open PRs. Looks like @aldeed is still actively working on other stuff, so i wonder if this project is still maintained or if it needs maintainers?

**Comment by thearabbit** [comment]
+1

**Comment by c9s** [comment]
hello??

**Comment by zcrowe** [comment]
![giphy](https://cloud.githubusercontent.com/assets/3855267/19533479/d5aaf466-9637-11e6-8067-d0271d822240.gif)

**Comment by cyclops24** [comment]
@gregory I think it's better to switch to React and [Uniforms](https://github.com/vazco/uniforms) package. Also you can use new @aldeed package [node-simple-schema](https://github.com/aldeed/node-simple-schema)

**Comment by apienczy** [comment]
This is a great package; it would be too bad if it was dead; @aldeed please kindly let us know what are your plans here.

**Comment by Murukaen** [comment]
+1

**Comment by cyclops24** [comment]
+1

**Comment by thearabbit** [comment]
waiting for `aldeed` to reply!!!!!!

**Comment by U54** [comment]
+1 - Would love to hear what the future plans are with this package.

**Comment by Netherdrake** [comment]
+1

**Comment by mgebundy** [comment]
I really appreciate @aldeed's work on all these amazing packages, but was sad to find the updates to collection2 and the new simpl-schema node package aren't implemented in autoform. What's happening with this project?

**Comment by Netherdrake** [comment]
It needs some people to step up and contribute as maintainers. Maybe this would motivate @aldeed as well. The 464 open issues page looks daunting as is.
