### ISSUE TITLE
After insert autoform afquickfields are all empty?

### ISSUE THREAD

**Issue by lehtu** [Meteor-Community-Packages/meteor-autoform#1509]
I have autoform with `afQuickField`s and everytime I save my `insert` form, something automatically clears the whole form. I mean it doesn't even show default values anymore?

Am I missing something or is this a bug? Anyways, is there any workaround for this one?

**Comment by cornelisonc** [comment]
Is it possible your form is being saved, and you are being shown a new blank form? Check your database for the submitted form data. If it's not showing your default values either, are you sure they are set up correctly?

**Comment by raphaelarias** [comment]
@lehtu Add resetOnSuccess=false attribute on your autoForm. It will prevent the reload of the form, and will display the value typed by the user.

I would recommend not to use the `insert` type. Use the `normal` and treat the insertion through a method call.
