### ISSUE TITLE
jquerry Datepicker's dateFormat is overwritted by autoform

### ISSUE THREAD

**Issue by ghost** [Meteor-Community-Packages/meteor-autoform#1524]
Hello,

My problem is that when i use the jquery datepicker in an autoform, autoform seems to overwrite on the jquerry datepicker and my dateFormat isn't good ... I just want my date to be on "YYYY-MM-DD" format so I used bs-datepicker as the documentation told to, "String: Value is stored as a string representation of the selected date in ISO format, e.g., "2014-11-25"." but this isn't working for me, the format is "MM/DD/YYYY", I think that is the default browser's format.

**Comment by Gancar-d** [comment]
i just want my date to be on "YYYY-MM-DD" format and the documentation says " String: Value is stored as a string representation of the selected date in ISO format, e.g., "2014-11-25"." but this isn't working for me, it seems to be the default browser's format and I want to change it
