### ISSUE TITLE
Hooks to run a process after validation, but before submission

### ISSUE THREAD

**Issue by zcrowe** [Meteor-Community-Packages/meteor-autoform#1527]
Hello :)

From what I understand from the docs:

> The before hooks are called after the form is deemed valid but before the submission operation happens

Yet the forms validation never seems to fire.

My hook looks like this:

`AutoForm.hooks({
  createDevice: {
  before: {
    insert: function(doc){       
    }
   }
  }
});`

I'm trying to run an operation _after_ the forms been submitted and passed validation, but before the doc is inserted into mongo.

Any one have any pointers?

**Comment by drewlsvern** [comment]
I have this issue as well. Is there any resolution for this?

**Comment by drewlsvern** [comment]
I found a resolutions for my use case, I am using the method formType. It appears there was a change in v5.1.0 that causes prevalidation only if you have schema AND collection values set. Read the changelog here for more info [https://github.com/aldeed/meteor-autoform/blob/master/CHANGELOG.md](url)

**Comment by mehrdadarvin** [comment]
Just ran into the same issue and had to come up with a workaround.
For anyone interested:
```
AutoForm.hooks({ 
  createDevice: { 
    before: { 
      insert: function(doc){
        if (!AutoForm.validateForm(this.formId)) {
          return this.result(doc); // continue with normal submission which will fail due to validation
        }
        // validation passed
        // logic, logic, logic
        // ... eventually
        return this.result(doc);
      } 
    } 
  } 
});
```
