### ISSUE TITLE
access denied when using autoform

### ISSUE THREAD

**Issue by mphmelsen** [Meteor-Community-Packages/meteor-autoform#1538]
I'm trying to use autoform with meteor validatedmethod simple schema and collection2. However when I enter values in the textfields I get:

`undefined
error
:
403
errorType
:
"Meteor.Error"
message
:
"Access denied [403]"
reason
:
"Access denied"
stack
:
"Error↵    at Connection._livedata_result (http://localhost:3000/packages/ddp-client.js`

My code uses the following template:

`
  {{#autoForm collection=club id="insertClubs" type="insert"}}
  <fieldset>
    <legend>Add a Club</legend>
    {{> afQuickField name='name'}}
    {{> afQuickField name='number'}}
    {{> afQuickField name='updated'}}
    {{> afQuickField name='created'}}
  </fieldset>
  <button type="submit" class="btn btn-primary">Insert</button>
  {{/autoForm}}
`

then I'm using an event helper to listen to the submit and invoke a validatedmethod:

`'submit .btn btn-primary'(event, instance) {
    console.log('test');

     insert.call( {
      name: 'test',
      number: 3,
      updated: new Date(),
      created: new Date()
    }, (err, res) => {
       console.log(err);
      if (err) {
        if (err.error === 'validation-error') {
        }
      }
     });
  
  }`

and this is the insert call itself:

`export const insert = new ValidatedMethod({
  name: 'Clubs.methods.insert',
  validate: Clubs.simpleSchema().validator(),
  run(newClub) {
    // In here, we can be sure that the newClub argument is
    // validated.
console.log('insert new club');
    if (!this.userId) {
      throw new Meteor.Error('Clubs.methods.insert.not-logged-in',
        'Must be logged in to create a club.');
    }

    Clubs.insert(newClub)
  }
});`

I think that this setup does not actually invoke my insert method as I don't see the console.log but meteor comes back with the error. Any idea what could be the problem?

**Comment by stefanve** [comment]
How did you set your allow/deny?
