### ISSUE TITLE
Autoform Update with flowrouter

### ISSUE THREAD

**Issue by estock** [Meteor-Community-Packages/meteor-autoform#1547]
I'm trying to update and entity using autoform, I have the following code

Meals.allow({
	insert: function(userId) { return true; },
	update: function(userId) { return true; }
});

Template.UpdateMeal.helpers({
	getDocument: function () {
		console.log("test:")
		console.log(FlowRouter.current());
		var theItem = Meals.findOne({_id: FlowRouter.current().params.itemId});
		console.log("the item:"+JSON.stringify(theItem));
		return theItem
	}
});

                    <div class="col-xs-12">
                        {{#with getDocument }}
                        <div>
                            {{name}}
                            {{this}}
                            {{> autoForm collection="Meals" id="updateMealForm"  doc=getDocument class= "new-recipe-form" type="update"}}
                        </div>
                     {{/with}}
                    </div>

but nothing seems to work. I've tried doc = this,  doc = getDocument, I can't figure out where it's failing.

**Comment by raphaelarias** [comment]
Probably your Meals.findOne is not returning nothing. As far as I saw the syntax and usage of AutoForm is okay. By the way, it would be better not use Allow and Deny functions, and do that through a method.

By the way 2: Your sintax for FlowRouter is outdated: FlowRouter.getParam('idemId');
