### ISSUE TITLE
Select not showing the saved value while updating the form

### ISSUE THREAD

**Issue by ankitv89** [Meteor-Community-Packages/meteor-autoform#1556]
Hi,

While using select, the saved option is not highlighted. I am using methods to update the form. It selects the default first option.

**Comment by dazzyon** [comment]
+1

**Comment by JulianKingman** [comment]
+1

Mine just shows "Select option"

Related issues:
https://github.com/aldeed/meteor-autoform/issues/1482
https://github.com/aldeed/meteor-autoform/issues/1333
https://github.com/aldeed/meteor-autoform/issues/234

**Comment by JulianKingman** [comment]
My issue was using an array type (`[String]`) for a select field
