### ISSUE TITLE
Not receiving object with _id and modifier with singleMethodArgument=true

### ISSUE THREAD

**Issue by franciscohanna92** [Meteor-Community-Packages/meteor-autoform#1566]
I have a form with the following options: 

```
{{
	#autoForm 
	collection=articulosColecction 
	id="articulos_modificar" 
	doc=articuloToModificar
	singleMethodArgument=true
	type="method-update"
	meteormethod="areas.update"
}}
```
and `areas.update` looks like this:

```javascript
export const update = new ValidatedMethod({
	name: 'areas.update',
	validate: null,
  	run(doc) {
  		console.log(doc)
  		Areas.update({ _id: doc._id	}, doc.modifier)
  	}
});
```
But `console.log(doc._id);` is outputting undefined and I've tried `console.log(doc)' and it outputs a modifier object.

What is going on? Shouldn't `doc` be a object containing  the `_id` of the doc beign updated and the `modifier` object? Note the option `singleMethodArgument=true` in the form.

**Comment by FranciscoHanna** [comment]
Solved. It was a mistake from my part.

**Comment by FranciscoHanna** [comment]
Solved. Was a really bad mistak from my part. I was adding the `singleMethodArgument=true` to another form and not the one that I was interested in.

Sorry for opening this issue, will pay more atention next time.
