### ISSUE TITLE
Autoform 6 autosave problem

### ISSUE THREAD

**Issue by peardigital** [Meteor-Community-Packages/meteor-autoform#1576]
Hi 
When using autosave for Autoform 6 it is really slow with page load times of 15-20 seconds.

Without autosave everything runs quick, like in a few seconds, as the forms have around 50-80 fields.

What I've noticed is that with Autosave my helpers (3 of them) are called multiple times (about 30-50) before on render even happens.

Please can you investigate the issue.

Thanks

**Comment by aldeed** [comment]
@peardigital Please create a repo with an app that minimally reproduces this issue, and post a link to it.

**Comment by peardigital** [comment]
Here is the slow copy with autosave turned on. https://bitbucket.org/libertyapps/node/commits/6c143526fc826d271712cade9750d8601d4b6500

The working copy without Autosave:
https://bitbucket.org/libertyapps/node/commits/03452f9aef5dd021dffa38fc02ca621e81e3bd08

This is the route / page that is problematic

FlowRouter.route('/user/view/:id', {
    name: 'user-view',
    action() {
        BlazeLayout.render('MainLayout', {main: 'ViewUser'});
    }
});
