### ISSUE TITLE
Hooks not called. Before hooks called but After & EndSubmit hooks not called. Data saved

### ISSUE THREAD

**Issue by fortunes-technology** [Meteor-Community-Packages/meteor-autoform#1580]
#autoForm collection=Collections.Students id="singleStudentForm" type="insert"

I'm using auto form using above, but hooks are not called. Data saved correctly but can't get hooks work. Before hooks all works fine, but After Hook not called. OnSuccess, EndSubmit also not called.

After Hooks not even called from your sample application. In Your sample application, after hooks seems called though. Can you help me?

**Comment by fortunes-technology** [comment]
I just found out what is causing the issue.
I'm using collection hook.
  insert(doc, callback) {
    const ourDoc = doc;
    ourDoc.createdAt = ourDoc.createdAt || new Date();
    const result = super.insert(ourDoc, callback);
    return result;
  }

and this one is causing the issue. not generating call back for completion. 
Right now, I've commented out to work, but I need this to work.

**Comment by jankapunkt** [comment]
Don't know if this is the same issue as the one I am facing, but I can't get the after hooks (as well as onSuccess and onError) to work, even not with the examples. I am using af 6.0.0. Are there new settings to enable/disable hooks or something?

**Comment by jankapunkt** [comment]
@fortunes-technology 

I found out, that my collection's update method was not passing the callback to it's super method. After changing it to:

```
class MyCollection extends Mongo.Collection {
//...
	update(query, modifier, options, callback) {
		//... custom stuff ...
		return super.update(query, modifier, options, callback); // now it passes also the callback
	}
//...
}
```
All hooks are back again. Of course I had to do that for insert and remove, too. If this solves your problem, too, then it is not a bug and the issue can be closed.

@aldeed Should I add a small hint in the README, that hooks only work proper on collections where the insert/update/remove methods have been overridden properly?

**Comment by jankapunkt** [comment]
@fortunes-technology okay you were right, on the INSERT method there is no callback passed, instead the following object is passed to the collection's insert method:

```
{
    validationContext: "myInsertFormId", 
    filter: {...},
    autoConvert: {...}, 
    removeEmptyStrings: {...},
    trimStrings: {...}
}
```
Which is why there is no callback to be called.

@aldeed is this expected behavior for insert forms?

**Comment by fortunes-technology** [comment]
Thanks for getting back to me on the issue. I'm currently working with a workaround, removing all the insert hooks. and I think you are right about callback. I will check it when I have time. Thanks

**Comment by jankapunkt** [comment]
@fortunes-technology did you find anything?

**Comment by GM-Alex** [comment]
For insert there is the options parameter missing:

```js
insert(doc, options, callback) {
  //Do stuff
  return super.insert(doc, options, callback);
}
```
