### ISSUE TITLE
Access denied. Operator $setOnInsert not allowed in a restricted collection. [403]

### ISSUE THREAD

**Issue by fuatsengul** [Meteor-Community-Packages/meteor-autoform#1582]
Hello @aldeed 
Thanks for great packages!

I'm just upgrading into Autoform 6.0.0 release and I just stuck on this error. 
Please let me know if you have any idea I can pursue here.
Note that I've already installed simpl-schema npm package and collection2-core package.

**Access denied. Operator $setOnInsert not allowed in a restricted collection. [403]**

This is my simple update form: 
```
{{#autoForm
	id="book_editor_form1"
	collection=BookDB
	type="update"
	doc=book
	schema=BookDB.schema
	autosave=true
	autosaveOnKeyup=true
	trimStrings=false
	validation="keyup"}}

	{{> afQuickField name='grade'}}
	{{> afQuickField name='lesson'}}
	{{> afQuickField name='title'}}	
{{/autoForm}}
```

This is my simplified schema and I've also removed unrelated array data here in schema, please ignore them.
```
BookDB.schema = new SimpleSchema({
	_id: {
		type: String,
		optional: false,
		defaultValue: function() {
			return Random.id();
		},
		regEx: SimpleSchema.RegEx.Id
	},
	_authorId: {
		type: String,
		optional: false
	},

	title: {
		type: String,
		optional: false,
		autoform:{
			label: false,
			leftLabel: function() {
				return TAPi18n.__('BookSchema.title');
			},
			options :[
			    ....
			]			
		}
	},
	lesson: {
		type: String,
		optional: false,
		autoform:{
			label: false,
			leftLabel: function() {
				return TAPi18n.__('BookSchema.lesson');
			},
			options :[
			    ......
			]
		}
	},
	grade: {
		type: Number,
		optional: false,
		autoform:{
			label: false,
			leftLabel: function() {
				return TAPi18n.__('BookSchema.grade');
			},
			options : [
			    ......
			]
		}
	},
    
	categories: {
		type: Array,
		optional: true
	},
	"categories.$": {
		type: BookDB.schema.category
	}
}
```

**Comment by fuatsengul** [comment]
Hello @aldeed 
I'm sorry for opening this issue in wrong place, I believe I found its root cause in simpl-schema package. Somehow defaultValue leads this error.

**Comment by sgelbart** [comment]
I'm having issue too

**Comment by fuatsengul** [comment]
Hello @sgelbart,
Have you take a look into defaultValue attributes in your schema? I had to remove all of them to get it work

**Comment by sgelbart** [comment]
Removing defaultValue fixed it!! Now I see what you said above :-) 👍 Thanks!

**Comment by copleykj** [comment]
I'm having this same issue. I'm guessing this is a bug in node-simpl-schema? defaultValue fields are kind of an integral part of my schemas, and removing them all isn't really an option. I guess I could convert them all to autoValues that only return on insert but what a mess..

**Comment by copleykj** [comment]
https://github.com/aldeed/node-simple-schema/blob/3eca0e858ba318d4764d3dea29380c8555531159/lib/SimpleSchema.js#L754

**Comment by copleykj** [comment]
Hopefully we can verify if this is a bug or not soon and possibly a fix if it is. @fuatsengul this is probably best filed on the node-simpl-schema repo. For now as a workaround I have used an IIFE closure which returns a function that only returns the value if the operation is an insert and the field isn't set.

```javascript
const defaultValue = value => function autoValue() {
  if (!this.isUpdate && !this.isUpsert && !this.isSet) {
    return value;
  }
};

// Schema field definition
fieldName: {
  type: Number,
  autoValue: defaultValue(10),
}
```

**Comment by mgebundy** [comment]
Thanks for the workaround @copleykj 

I'm having this exact issue, which is a little painful considering all the schemas I'm working with.

**Comment by akiarostami** [comment]
I am having the same issue, and I'm not even using defaultValue in the schema. Any idea why?

**Comment by gaupoit** [comment]
Thanks for @copleykj to figure it out. I also had the same problem.

**Comment by imajus** [comment]
Had to change it a bit, as the solution didn't work for upserts:
```js
const defaultValue = value => function autoValue() {
  if ( this.isSet ) return;
  if ( this.isInsert ) {
    return value;
  } else if ( this.isUpsert ) {
    return { $setOnInsert: value };
  }
}
```
Haven't tested it well yet, but upserts start to work just fine.
