### ISSUE TITLE
Hide label of afInputField when using boolean datatype

### ISSUE THREAD

**Issue by mklueh** [Meteor-Community-Packages/meteor-autoform#1584]
I´m using an afInputField with a Boolean datatype.

I don´t know why, but using Boolean always shows a label and I can´t get rid of it.

What I´ve tried was:

`{{>afFieldInput name="field1" label=false}}`

and

`{{>afFieldInput name="field1" label=""}}`

and

    new SimpleSchema({
        field1: {
            type: Boolean,
            optional: true,
            label: ""
        }
    });

and

    new SimpleSchema({
        field1: {
            type: Boolean,
            optional: true,
            label: false
        }
    });

and

    new SimpleSchema({
        field1: {
            type: Boolean,
            optional: true,
            autoform: {
                label: false
            }
        }
    });

and

    new SimpleSchema({
        field1: {
            type: Boolean,
            optional: true,
            autoform: {
                label: ""
            }
        }
    });

None of those are working! But I´ve figured out that with this solution you can change the label, if the string is not empty. Wtf

```
new SimpleSchema({
        field1: {
            type: Boolean,
            optional: true,
            label: "new label"
        }
    });

```

Is there any working solution for simply hiding that field label?

**Comment by thebarty** [comment]
the workaround solution is to use a blank like `label: ' '` OR hide via css
