### ISSUE TITLE
Autoform options reactivity

### ISSUE THREAD

**Issue by macsj200** [Meteor-Community-Packages/meteor-autoform#1593]
I'm having trouble with reactivity in the computed `options(...)` method feature. Here's a sample of my code
```javascript
        options:() => {
          let opts = this.categoriesQuery.fetch().map((category) => {
            return {
              label: category.name,
              value: category._id,
            }
          });
          return opts;
        },
```
I'm using [grapher](http://grapher.cultofcoders.com/index.html) to run my queries, and I'm also doing this inside a react component using [TrackerReact](https://github.com/ultimatejs/tracker-react).

Do you have any idea why this options method isn't behaving reactively?

**Comment by aldeed** [comment]
It looks fine, though you could try switching to `options() {}` instead of the arrow func to rule out that. Otherwise you'll need to post a link to a repo with a minimal reproduction of this issue.

**Comment by mozfet** [comment]
I've also tried using reactive code inside options in V6 and failed to get it working. It would show the initial values, but would not react to changes. I think schema options are not reactive, or there is a bug somehow.

However I understood [from the docs](https://github.com/aldeed/meteor-autoform#use-a-helper) that if you want reactivity then you need to create a custom autoform and pass the options...
