### ISSUE TITLE
Does Autoform work with Meteor 1.5?

### ISSUE THREAD

**Issue by formspoint** [Meteor-Community-Packages/meteor-autoform#1601]
Does anyone know if Autoform works with Meteor 1.5?

**Comment by robertdavid010** [comment]
Had other issues with 1.5, didn't see any with Autoform yet.

**Comment by formspoint** [comment]
What other issues?

**Comment by narigondelsiglo** [comment]
I'm having troubles with autoform6 collection2-core y NPM's simpl-schema with meteor 1.5

**Comment by formspoint** [comment]
@narigondelsiglo @robertdavid010 What troubles/Issues?

**Comment by narigondelsiglo** [comment]
sorry, my previous comment was submitted icomplete. now is editted

**Comment by narigondelsiglo** [comment]
Reproduce like this:
`
cd /tmp
meteor create autoformtest
cd autoformtest
meteor add aldeed:collection2-core aldeed:autoform 
meteor npm install --save bcrypt simpl-schema
#follow https://github.com/aldeed/meteor-autoform#a-basic-insert-form
`
Maybe I'm forgetting to do something obvious that it's not explicitly detailed.. I'm pretty new to Meteor, this is my first experience.
This example leaves autopublish on BTW...

Thanks to all for this great community!

**Comment by narigondelsiglo** [comment]
For the record: 
I did a:
`meteor update --release METEOR@1.4.4`
And it works (doesn't) without any difference

**Comment by narigondelsiglo** [comment]
Ok, I tried the autoform demo provided by @aldeed 
```
git clone https://github.com/aldeed/autoform-demo
cd autoform-demo
meteor update --all-packages
meteor npm install --save simpl-schema babel-runtime meteor-node-stubs select2 select2-bootstrap-theme jquery bcrypt
meteor
```
test insert on the browser and... it works!

Although I really don't know how to make my project work for now... for the topic of this issue I can say this can be closed:  **IT IS COMPATIBLE WITH METEOR 1.5**

**Comment by Pushplaybang** [comment]
@formspoint I can also confirm that it does, please close.  Thanks.

**Comment by formspoint** [comment]
What version of simpleschema, collection, and autoform work together with 1.5?

**Comment by narigondelsiglo** [comment]
@formspoint you should use collection2-core and npm's simpl-schema (note the missing e)
Look at the packages I've installed before in a meteor from scratch.
The last version of autoform is 6.2.0 I think

**Comment by formspoint** [comment]
It's working for me as well.  Going to close this.

**Comment by Pushplaybang** [comment]
You need to be using the latest.

**Comment by YusifKhalilov** [comment]
@narigondelsiglo have the same issue. I tried Meteor methods same problem. I can't insert form. Method inser not found. And i followed tutorial and got same issue.

**Comment by narigondelsiglo** [comment]
My problem was related to the files loading order or something like that.
Try to get started from aldeed's autoform-demo project.
Good luck!

**Comment by aessig** [comment]
I have a strange error when trying to use Metoer 1.5 and Autoform 6 #1617
