### ISSUE TITLE
Problems displaying objects in an array

### ISSUE THREAD

**Issue by fdmansilla333** [Meteor-Community-Packages/meteor-autoform#1603]
Hello! I have a problem displaying the objects in an array. I'm following the example on the page (http://autoform.meteorapp.com/qfdetails) but it only shows me the input of a field. My sketch is the same as the example, and my template is this:

`<template name="prueba">
{{> quickForm id="demo" schema='schemas'}}

</template>`

And the render capture is:
![image](https://user-images.githubusercontent.com/2333241/27108057-bdfad788-5071-11e7-9c74-2e49bfb4d4c8.png)

Sorry for the inconvenience. regards

**Comment by ziedmahdi** [comment]
@fdmansilla333 I m facing the same problem with autoform 6.2.0 and Meteor 1.6.1.
Have you found a solution?
