### ISSUE TITLE
Autoform update with nested fields in Schema

### ISSUE THREAD

**Issue by marcoschwartz** [Meteor-Community-Packages/meteor-autoform#1607]
Hello,

I searched the web for this issue but couldn't solve the problem. I have the following schema:

Schemas.Pages = new SimpleSchema({
    name: {
        type: String,
        label: "Name"
    },
    url: {
        type: String,
        label: "Url"
    },
    model: {
        type: String,
        label: "Model"
    },
    brandId: {
        type: String,
        label: "Brand"
    },
    userId: {
        type: String,
        label: "User ID"
    },
    header: {
        type: Object,
        label: "Header"
    },
    'header.title': {
        type: String,
        label: "Title"
    },
    'header.headline': {
        type: String,
        label: "Headline"
    },
    'header.subheadline': {
        type: String,
        label: "Sub Headline"
    },
    'header.disclaimer': {
        type: String,
        label: "Disclaimer"
  });

And the following autoform:

{{#autoForm collection="Pages" doc=this id="updatePageForm" type="update" autosave=true}}
    <fieldset>
        {{> afQuickField name='name'}}
        {{> afQuickField name='url'}}
        {{> afQuickField name='brandId' type='select' options=brandOptions}}
        {{> afQuickField name='header'}}
</fieldset>
{{/autoForm}}

When I just have non-nested fields (like name) it works fine, but when I also try to update the header it doesn't save anything anymore. How can I solve that? Thanks!

**Comment by bhavikbhavsar** [comment]
+1 I am too facing this.
