### ISSUE TITLE
prepend icons to form fields

### ISSUE THREAD

**Issue by thisthatother** [Meteor-Community-Packages/meteor-autoform#1622]
Hello, 

I am trying to get the icons in my form field to prepend to the field, i.e. resolve to this

`<i class="icon-prepend fa fa-envelope">`

I am using the following code

`{{> afFormGroup type="text" name="email" placeholder="Email Address" icon="envelope" template="smartAdmin"}}`

which resolves the icon to this:

`<i class="icon-append fa fa-envelope">`

I imagine there is an extra parameter I need to add to my code, akin to `type="prepend"` but I can't find the syntax anywhere in this repo, or elsewhere online.

Does anyone know how to do it?

**Comment by rikyperdana** [comment]
I suggest you to use jQuery for a quick fix
```
$(':text[name="email"]').prepend('<i class="icon-append fa fa-envelope">')
```
