### ISSUE TITLE
autoform validation errors do not display with simpl-schema, collection2 and variants

### ISSUE THREAD

**Issue by jamgold** [Meteor-Community-Packages/meteor-autoform#1624]
I am using quickform for a simple auto form. As soon as I add a variant, it doesn't show any validation errors in the UI anymore.
```
import { Mongo } from "meteor/mongo";
import SimpleSchema from "simpl-schema";
import { Tracker } from "meteor/tracker";

export const Pages = new Mongo.Collection("pages");

SimpleSchema.extendOptions(["autoform"]);

Pages.attachSchema(new SimpleSchema({
  type: {
    type: String,
    allowedValues: ["simple", "variant"],
    autoform: {
      // type: 'hidden'
    }
  },
  title: {
    type: String,
    label: "Title",
    max: 200
  }
}, { tracker: Tracker }),{
 selector: {
  type: "simple"
 }
});
```
the actual template is simple
```
<template name="af">
  {{>quickForm collection=Pages doc=doc id="insertPageForm" type="insert"}}
</template>

Template.af.helpers({
  doc() {
    return { type: "simple" };
  },
  Pages() {
    return Pages;
  }
});
```
The form renders properly, but when hitting submit without entering anything into title, it does not reflect the validation error in the UI. I am using mrt:bootstrap-3. As soon as I remove the selector, validation errors are properly reflected again.

**Comment by jamgold** [comment]
I was able to work around this by explicitly providing the schema when calling `{{>quickForm collection=Pages schema=Schema doc=doc id="insertPageForm" type="insert"}}`.

**Comment by Abhimanyu-Jana** [comment]
I had the same issue but it was due to missing `{tracker: Tracker}` in the schema definition
