### ISSUE TITLE
AutoForm Creates Elements with Duplicative IDs

### ISSUE THREAD

**Issue by micchickenburger** [Meteor-Community-Packages/meteor-autoform#1629]
This seems to happen for select-checkbox and boolean-radios; perhaps also for others.

Steps to reproduce:
1.  Navigate to [http://autoform.meteorapp.com/types](http://autoform.meteorapp.com/types)
2.  For input type choose `select-checkbox`
3.  Look at the label elements in your browser's console

![screen shot 2017-12-10 at 3 55 40 pm](https://user-images.githubusercontent.com/4521230/33809831-a3c1ae94-ddc2-11e7-91ce-21f418ec5ce1.png)

The IDs for all the checkboxes are the same.  This is contrary to the HTML specification.  Browsers like Google Chrome will throw console errors about these duplicate IDs.

**Comment by olexandrbig** [comment]
got same problem with "select-radio"
`[DOM] Found 4 elements with non-unique id #d8t4krbtW538vprRA`
![image](https://user-images.githubusercontent.com/1343484/36738755-fde7f998-1be6-11e8-9b4f-61eb2130cbfd.png)

**Comment by aniskhan001** [comment]
Getting the same error for radio input types.

**Comment by jkutianski** [comment]
The same happens with `required` that exists on all the inputs radio or checkbox.

I use this as workaround
```
Template.afRadio_bootstrap3.helpers({
  atts: function selectedAttsAdjust() {
    var atts = _.clone(this.atts);
    if (this.selected) {
      atts.checked = '';
    }

    // remove id & required for accesibility issues
    delete atts.id;
    delete atts.required;

    return atts;
  }
});
```
