### ISSUE TITLE
Unique validation

### ISSUE THREAD

**Issue by zimme** [Meteor-Community-Packages/meteor-autoform#236]
I have a minor problem with unique validation.

I'm using a quickForm.
Clicking submit validates all input and the unique validation gets run,
stops submit but when the error message is presented the form resets
and the message displays '[label] is required' instead of notUnique
message because all inputs are empty

**Comment by otroboe** [comment]
Any news about this issue ?

**Comment by zimme** [comment]
Nah, I've got a reprod for it but I haven't had the time or need to look into this more... it has something to do with latency compensation if I remember correctly.

Hopefully I will come up with a smart solution for this some day, in the meantime I hope someone else will come up with instead :smile:

**Comment by otroboe** [comment]
I think the quick solution is to create a custom validation, and look for yourself a duplication :)
