### ISSUE TITLE
Button name and value

### ISSUE THREAD

**Issue by partus** [Meteor-Community-Packages/meteor-autoform#303]
hi, on the submission of the form I want to have several buttons with different value, seems like it's not possible currently, (the button is not considered as an input element).
### EXAMPLE

`<button name="subject" type="submit" value="HTML">HTML</button>
  <button name="subject" type="submit" value="CSS">CSS</button>`
from my point of view,  if `subject` is in simple schema, the value from the button must be gathered together with other fields (if first button is clicked then subject  is equal to "HTML" and if the second one is clicked then subject  is equal to  "CSS"). 

Certainly, there could be other implementations, but the main requirement is to have ability to gather the value of the button in `autoform` way .

**Comment by Maxhodges** [comment]
Same problem I want a `SAVE` button and a `SAVE & CLOSE` button. They both submit, but if the second one is clicked, in the OnSuccess event I want to call `history.go(-1);`

Having trouble determining which button was clicked. Can I call submit from a custom method? i.e. I "submit" to a customer function "type='submitAndClose'" then I can call autoForm's submit because I have a way to set a flag regarding the need to close after OnSuccess

**Comment by Maxhodges** [comment]
I think an easy fix would be to propogate the button id though the event chain so it's available in OnSuccess i.e. 
template
` <button type="submit" id="saveClose" class="btn btn-primary "> . . . `

hook
...`onSuccess: function(operation, result, template, callerId)`...

**Comment by Maxhodges** [comment]
or is there some way to query the template or event to retrieve the `clicked` element?

**Comment by Maxhodges** [comment]
i'd recommend passing ID not value as it should be unique. Then you can used the ID to get VALUE or any other attribute via jquery

**Comment by aldeed** [comment]
Make "Save and Close" a `type="button"` instead of submit. In the event handler for that button, set a variable to indicate it should close, and then call `$('form#formId').submit()`. In onSuccess, check the variable to see if you should close.

**Comment by Maxhodges** [comment]
awesome! This is the missing piece `$('form#formId').submit()`

Thank you! Is there a donate button for this package?

**Comment by aldeed** [comment]
[Gratipay](https://gratipay.com/aldeed/) contributions are welcome. :)

**Comment by Konafets** [comment]
@aldeed: I followed your advise to use ```$('form#formId').submit();``` and this works. I my code I route after sending to another page. Now, if the validation fails, the router kicks in. Is there a way to get the validation results inside the event handler?

```
if (validationErrors == false) {
   // Route home
}
```
