### ISSUE TITLE
view jumps to top after update when multi select contains a value

### ISSUE THREAD

**Issue by mxab** [Meteor-Community-Packages/meteor-autoform#537]
Hi,
I have an issue when I have a multi select in my form with type update.
When I select at least one value in the select and submit it it jumps to the top, if I leave it empty and just update other fields I don't have this behaviour.
Initially I thought it might be an iron router problem but I have it also if I don't use it
See this example with iron-router:
https://github.com/mxab/autoform-ironrouter-jump-to-top-issue
and this one without it
https://github.com/mxab/autoform-ironrouter-jump-to-top-issue/tree/without-ironrouter

Is there anything I could to prevent this jumping?

Thanks in advance
Max

**Comment by mxab** [comment]
I check if it might be an meteor related issue with an "pure" meteor
https://github.com/mxab/autoform-ironrouter-jump-to-top-issue/tree/without-autoform
this seems not to cause jumping.

**Comment by stbaer** [comment]
any thoughts on this?

**Comment by dohomi** [comment]
Hi @aldeed do you have an idea what could cause this? I also realized that all my multi-selection let the page jumps to top. Thanks

**Comment by aldeed** [comment]
This seems to be a side effect of the workaround that's in place until https://github.com/meteor/meteor/issues/2431 is fixed (we completely destroy and recreate any form that has a `doc` attribute). I can't think of any solution at the moment.

**Comment by mxab** [comment]
Ok, thanks for the confirmation

**Comment by dohomi** [comment]
Hi @aldeed, I changed all multiselect fields into ```noselect: true```and the behaviour is gone. It seems only select with ```multiple=true```is causing it
