### ISSUE TITLE
Is there any way to check if an unsubmitted form is "dirty"?

### ISSUE THREAD

**Issue by jfly** [Meteor-Community-Packages/meteor-autoform#548]
"dirty" meaning it has unsaved changes? This would be nice for enabling/disabling submit and reset buttons. I imagine this could be fairly easily implemented in terms of [Autoform.getFormValues()](https://github.com/aldeed/meteor-autoform/blob/master/api.md#autoformgetformvaluesformidclient), but it seems useful enough that it should be a part of meteor-autoform proper.

If this doesn't already exist, and there's interest, we can try submitting  a PR with this feature. How does `Autoform.isFormDirty()` sound? I like the term dirty from the world of caching, but perhaps there's a better word?

**Comment by jcheroske** [comment]
Angular has this as $dirty and $pristine flags on the form. It also has $valid and $invalid flags at the form level as well as the field level. My wishlist would be a complete set of helpers: afFormIsInvalid, afFormIsValid, afFormIsDirty, afFormIsPristine. Oh, and fantastic package, btw. Thanks for all the hard work.

**Comment by mxab** [comment]
Hi I started working this issues, see the PR #710

for now you can call ```AutoForm.getFormState('theFormId')``` which will return clean/dirty/pristine, also you can call isDirty("formId"), isClean("formId")

further there is a template helper ```afHasFormState 'clean'```optional you can pass ```formId='theFormId'```

**Comment by maxnowack** [comment]
+1

**Comment by poojabansal** [comment]
+1

**Comment by babin93** [comment]
![image](https://cloud.githubusercontent.com/assets/5667458/9839553/ea8647d8-5a4b-11e5-84f6-cd60fbb10cae.png)

**Comment by wilau2** [comment]
+1

**Comment by Lidofernandez** [comment]
+1

**Comment by jfly** [comment]
@jankapunkt, just curious: why did you close this?

**Comment by jankapunkt** [comment]
Similar to the other issue I commented. If you feel this still to be important please reopen.
