### ISSUE TITLE
Dynamic options inside object arrays

### ISSUE THREAD

**Issue by craig-l** [Meteor-Community-Packages/meteor-autoform#585]
Related to #553, except we are doing this inside an array.
We're generating dynamic options inside autoform.options as follows

```
color: {
    type: String,
    optional: true,
    label: 'Color',
    autoform: {
        options: function() {
            var model = AutoForm.getRelativeFieldValue('selectedCars.$.model');
            return Cars.findOne(model).colors.map(function (color) {
                return {
                    label: color.name,  //.name is human readable
                    value: color.dbName //.dbName has spaces stripped and camel cased
                }
            });
            }
    }
}
```

This works and the select options are reactive, even when inside a deeply embedded array and looking somewhere other than a sibling.
Related to #584.. this.field('selectedCars.$.model') would be helpful/more slick

We made `getRelativeFieldValue` like so

```
AutoForm.getRelativeFieldName = function getRelativeFieldName (field) {
    var thisField = Template.parentData(1);
    if (!thisField || !thisField.name) {
        return field;
    }
    var source = thisField.name.split('.');
    var target = field.split('.')
    var name = _.map(target, function (token, index) {
        if (token === '$') {
            return source[index] || token;
        }
        return token;
    }).join('.');
    return name;
}

AutoForm.getRelativeFieldValue = function getRelativeFieldValue (field) {
    var value = AutoForm.getFieldValue(AutoForm.find().formId, AutoForm.getRelativeFieldName(field));
    return value;
}
```

**Comment by aldeed** [comment]
I think something like this can be added, but still need to think a bit on how best to do it.

**Comment by BradRyan** [comment]
+1 on reactive way to grab other field values in an array of objects and dynamically set autoform.options.  Thanks @craig-l for the suggestion.  I'll give it a shot.

**Comment by BradRyan** [comment]
This worked for trying to set options, but not when trying to use the getRelativeFieldValue function in an autoValue function.  Looks like I might want to try a custom template like noted on #202... would be nice to keep all the settings in the schema.

**Comment by craig-l** [comment]
Did you try 
var field = AutoForm.getRelativeFieldName('xx.$.xx');
var value = this.field(field).value

**Comment by BradRyan** [comment]
I just tried, but no luck. I actually don't see my autovalue function getting called at all. Hmmm

~Brad

**Comment by BradRyan** [comment]
Ah it's waiting for an insert/update I believe. I'm looking to try and have default values populate as you fill the form, but can still change them. Maybe autovalue is the wrong place to do this.

~Brad

**Comment by aldeed** [comment]
In autoform 5.0, `this.name` is set within the options function, so you should be able to do

```js
var model = AutoForm.getFieldValue(this.name.replace('.color', '.model'));
```

We can continue to think of how this might be made easier, but it's a bit better anyway.

**Comment by nQk2** [comment]
Neither craig-l's nor aldeed's method works for me, tested both autoform 4 and 5:

<code>Exception in template helper: TypeError: Cannot read property 'colors' of undefined</code>

Any ideas? Is there any way to debug this? I tried console.log(model) but nothing appeared.
