### ISSUE TITLE
Bulk Editing

### ISSUE THREAD

**Issue by aramk** [Meteor-Community-Packages/meteor-autoform#641]
I'm working on an app that edits a bunch of documents where the user may want to edit properties in bulk. It's easy to create a custom AutoForm which accepts `docs` in its data and then use the `onSubmit` hook to perform the actual updates.

I thought it might be useful to add this as a topic for debate on whether a form could be generated systematically. Here are some simple brainstorming points:
- Fields should be empty if the docs contain different values for that field, or the common value if they don't.
- Some fields are not be appropriate for bulking, such as unique fields.
- If `docs` is passed it could be assumed that onSubmit is going to be used, so any common logic for submission could take place before this hook is called.

Anyway, just a thought. I doubt I'll have time to actually implement this unless I need it for more than one type of form in my app, but I think it'd be reasonably easy to add and quite useful for certain cases.

**Comment by aldeed** [comment]
We can leave it open as a possibility. It may just be a matter of documenting how to do it rather than any direct support for it.

**Comment by aramk** [comment]
That sounds good to me.
