### ISSUE TITLE
Can't reset date value after form submit

### ISSUE THREAD

**Issue by laran** [Meteor-Community-Packages/meteor-autoform#682]
I have an autoform with a date field that defaults to today, and is editable by a user. After submitting the form I want to reset the date field to today. When I try to do this though, the date is just always left empty after submitting the form.

I'm trying this:

```
 Template.tasks.events({
   'submit form': function(event, template) {
     event.target.due.value = moment().format("YYYY-MM-DD");
   }
 });
```

I also tried this:

```
 AutoForm.addHooks('newTaskForm', {
   onSuccess: function(operation, result, template) {
     template.$('[due]').first().val(moment().format("YYYY-MM-DD"));
     // Incidentally, this focus doesn't work either. 
     // Trying to reset focus to the first input field after submit.
     // template.$('[summary]').first().focus();
   }
 });
```

I also have the field defined with the value set from a helper:
    {{> afQuickField name="due" value=today}}

... where today looks like this:

```
  Template.tasks.helpers({
    today: function() {
      return moment().format("YYYY-MM-DD");
    });
```

Nothing has worked so far. Am I doing this wrong? Or is this not supported?

**Comment by aldeed** [comment]
Try wrapping with `setTimeout` at 0ms:

```js
AutoForm.addHooks('newTaskForm', {
   onSuccess: function(operation, result, template) {
     setTimeout(function () {
       template.$('[due]').first().val(moment().format("YYYY-MM-DD"));
       // Incidentally, this focus doesn't work either. 
       // Trying to reset focus to the first input field after submit.
       // template.$('[summary]').first().focus();
     }, 0);
   }
 });
```

**Comment by laran** [comment]
Nope. Didn't work. Any suggestions of insight or context that you think would be helpful in understanding what/why this isn't working?

**Comment by aldeed** [comment]
Please provide a full reproduction in the form of a cloneable repo or MeteorPad so we can figure out a solution.

**Comment by ronyislam** [comment]
I got this to work by setting the timeout to 100.
