### ISSUE TITLE
Multiple=true not reactively updated on client while removing all values

### ISSUE THREAD

**Issue by dohomi** [Meteor-Community-Packages/meteor-autoform#690]
Hello,

I have an issue with `multiple=true`on a select field. I need to remove the multiple values on the server manually:

```

Schema:

"teamIds": {
      type: [String],
      optional: true,
      autoform: {
        multiple: true,
        noselect: true,
        options: function () {
          return [{value:"val",label:"label"}, {value:"val2",label:"label2"}];
        },
        placeholder: "schemaLabel"
      },
```

```
On server method:

      // hack to remove teamIds
      if(modif.$unset && modif.$unset.teamIds === ''){
        delete modif.$unset.teamIds;
        modif.$set.teamIds = [];
      }
```

Without this hack, the client doesn't remove the values, even the server side saved it correctly. Only on page reload the behaviour is correct.

Any thoughts on this? Thanks!

**Comment by aldeed** [comment]
I haven't seen this bug. Please provide a full reproduction in the form of a cloneable repo or MeteorPad.
