### ISSUE TITLE
Add more complete examples to docs

### ISSUE THREAD

**Issue by wmodes** [Meteor-Community-Packages/meteor-autoform#697]
In the [autoform docs](https://github.com/aldeed/meteor-autoform), there are many snippets of examples, but I cannot get any of them to work. Principally because autoform, meteor, and finally JS are new to me.

However, I am good at adapting examples, but couldn't find any full simple examples. [This is one](https://github.com/aldeed/meteor-autoform#example) I struggled with. Can I get a working full example of a simple autoform (or quickform) using collections?
- Assume I have aldeed:autoform and aldeed:collection2 installed.
- Let's say my files are divided up into
  - both/testform.js
  - server/testform.js
  - client/testform.js
  - client/testform.js
- And let's say I'm using a template called "testTemplate" and a collection called "testCollection"

Thanks for the help.

**Comment by aldeed** [comment]
Did you check out the [demo app](http://autoform.meteor.com/) and [its code](https://github.com/aldeed/autoform-demo)?

Right now the demo source is based on autoform 5.0, which is not yet released. There are a few backwards-incompatible changes, but the general principle is the same. Hoping to release 5.0 soon.

**Comment by wmodes** [comment]
@aldeed, I did. The demo is beautifully impressive, but hopelessly confounding to me since it does so much with so little. What might help a bit (though this seems like a goodly bit of work), is to have the source available for each feature that is being demoed. For instance, the creator of scrollmagic differentiated the [demo](http://janpaepke.github.io/ScrollMagic/) (crazy impressive) from [examples](http://janpaepke.github.io/ScrollMagic/examples/index.html) (ridiculously simple and illustrative). 

I think what I was needing was something that broke down that particular example -- quickform + collection -- in terms of how to structure the finicky meteor files. I asked a similar question on stackoverflow. Here's the satisfactory answer I received: http://stackoverflow.com/questions/28554221/meteor-autoform-example-requested

Lastly, thank you for all your work on this package. Now that I'm moving forward, I'm excited to do more with it.

**Comment by wmodes** [comment]
I'll include it here so it helps others who find this issue. Thanks to [Ethaan](http://stackoverflow.com/users/3961546/ethaan) for the example:

First create the project and remove the `autopublish and insecure` packages

Second on the `server/testform.js` put this.

    TestCollection.allow({
      insert:function(){return true;},
      remove:function(){return true;},
      update:function(){return true;},
    })

and the [publish][1] function 

    Meteor.publish("TestCollection", function () {
      return TestCollection.find();
    });

More about [allow][2]/[deny][3] rules 

Instead of `both/testform.js` put the collection declaration in `/lib/collections.js` as per meteor best practice.

    TestCollection = new Mongo.Collection("TestCollection");

and the [subscription][4].

   

    if(Meteor.isClient){
         Meteor.subscribe('TestCollection')
       }

now on `client/testform.html`

put this.

    <template name="testForm">
      {{> quickForm collection="TestCollection" id="insertBookForm" type="insert"}} 
    </template>

now on `client/testform.js` put the schema

    TestCollection.attachSchema(new SimpleSchema({ //take this from docs.
      title: {
        type: String,
        label: "Title",
        max: 200
      },
      author: {
        type: String,
        label: "Author"
      },
      copies: {
        type: Number,
        label: "Number of copies",
        min: 0
      },
      lastCheckedOut: {
        type: Date,
        label: "Last date this book was checked out",
        optional: true
      },
      summary: {
        type: String,
        label: "Brief summary",
        optional: true,
        max: 1000
      }
    }));

**Comment by aldeed** [comment]
I can maybe create MeteorPads for some of the simple readme examples. While I'm sympathetic to what you're saying, it seems your confusion is more related to unfamiliarity with Meteor, and I don't think there's benefit in documented a lot of aspects that one might reasonably expect a Meteor developer to already know.
