### ISSUE TITLE
Submit, Multi-second delay

### ISSUE THREAD

**Issue by cpalanzo** [Meteor-Community-Packages/meteor-autoform#713]
I have completed my complicated AutoForm - using all your helpful suggestions, but am finding that the form submission is taking many seconds to complete.

I tried #autoForm with autosave both true and false - to see if that made a difference, to see if validation was an issue - but no - even a manual save takes 5-10 seconds.. I'm not sure why. There are a lot of fields to be sure - but I must be doing something wrong. I did not setup an onSubmit callback or anything since I'm using standard type="update".

In addition to the code below ... I have two screen-cap movies to show the delay.

With Autocomplete=True see:
https://dl.dropboxusercontent.com/u/46066961/AutoForm%20AutoSave%20True.swf

With Autocomplete=False and using manual Submit see:
https://dl.dropboxusercontent.com/u/46066961/AutoForm%20AutoSave%20False.swf

You assistance or suggestions are greatly appreciated.

![screen shot 2015-02-23 at 8 23 32 pm](https://cloud.githubusercontent.com/assets/9503630/6341586/0d3f73cc-bb9a-11e4-81f4-1d35f732ffc0.png)

**Comment by aldeed** [comment]
Please retest using autoform 5.0, now released, and if it is still an issue, provide a simple reproduction app or MeteorPad showing the issue. The only reason for delay I can think of is if the update itself is taking that long, which might happen with a remote database on a slow network connection, but probably not running locally.
