### ISSUE TITLE
How to find out if a field has even been validated yet?

### ISSUE THREAD

**Issue by jcheroske** [Meteor-Community-Packages/meteor-autoform#714]
Is there an easy way to do this? `afFieldIsInvalid` simply returns `false` before a field has been validated, which is correct, but is a bit misleading. The `false` value of `afFieldIsInvalid` combines two states: 1) the field is actually invalid, or 2) the field has not even been validated. Is there a helper that can tease out the second state?

Thinking about it some more, I think having an `afFieldIsValid` helper that would return `true` when the field is valid and `false` when the field is either invalid or has not yet been validated would do the trick.

**Comment by aldeed** [comment]
Not really. What's the reason for needing to know?

**Comment by jcheroske** [comment]
I am working on a form, where fields have three states:

Not validated: Display them as a neutral color
Invalid: Display them with an 'error' class and show the error message
Valid: Display them with a 'success' class and print 'OK' or a checkmark message.

The dirty/pristine concept overlaps with the not validated state, but I'm thinking that maybe just knowing if a field has been validated could be enough. Your helper is simply:

```
regHelper('afFieldIsInvalid', function autoFormFieldIsInvalid(options) {
  options = parseOptions(options, 'afFieldIsInvalid');

  return options.ss.namedContext(options.formId).keyIsInvalid(options.name);
});
```

How does this helper interact with the `{{#autoForm validation=""}}` attribute? Does the `valdation=` setting prevent the helper from being called in the first place? I'm a bit confused as to how these two pieces fit together.

**Comment by aldeed** [comment]
Validation is not attempted until the validation event happens, which depends on your `validation` attribute. If it's key up, it will be validated when the key is pressed and on blur and on change, but before any of that happens it will be "valid by default" as you point out.

So you could approximate by listening to the same event(s) and setting your own flag indicating whether each has been validated yet.

Will have to think more about whether this can be implemented in a generic way in the package. Seems slightly different from dirty/pristine.

**Comment by jcheroske** [comment]
Yeah, I think it is a slightly different concept, but that it could be used to address some of the same use cases. They are both useful. Another useful concept is 'blurred', which is kind of like dirty, but reflects if a user has simply clicked into and out of a field. The Angular team felt it was necessary to add both dirty and blurred to the core library, fyi.

I am using the 'keyup' validation setting. When you say, "valid by default" how does that affect the `afFieldIsInvalid` helper? Is the schema context valid by default?

**Comment by aldeed** [comment]
Yes, context is valid by default until validated.

**Comment by jcheroske** [comment]
Could you possibly explain briefly how I can build my own version of simple-schema and autoform? I've cloned the repos, but don't know how to get them to build or how to tell my meteor project to use my local versions. Thanks for any help.

**Comment by aldeed** [comment]
If you either clone them directly into /packages in your app, or clone them elsewhere and then symlink them into /packages, your app should see them and use them instead of the published packages automatically.

**Comment by ganySA** [comment]
Hi

I was wondering if there is anymore on this one - i would like to add a has-success class, however its not as simple as just checking afFieldIsInvalid as all fields are initially successful.

Is there a work-around for this - to add a has-success class?

**Comment by lugaru90** [comment]
+1 for has-success class on validated Form Inputs!

**Comment by egoldblum** [comment]
+1.  I'd like to conditionally disable submit buttons until the form fields are all valid (but also not cause reactive validation errors to appear until values are entered).  The current valid-by-default-until-validation-is-run makes it hard to build what should be an easy feature.
