### ISSUE TITLE
onReset hook

### ISSUE THREAD

**Issue by shkomg** [Meteor-Community-Packages/meteor-autoform#735]
Hi,

i'm using [bootstrap-tokenfield](https://github.com/sliptree/bootstrap-tokenfield) in autoform - all works great except Reset button. That's realted to https://github.com/sliptree/bootstrap-tokenfield/issues/111
and may be easily solved by adding `onReset` hook.

Please, consider.

Thank you.

**Comment by aldeed** [comment]
It seems like that solution should work fine as written, without needing an onReset hook. You could replace the `setTimeout` call with `Tracker.afterFlush` for a little cleaner Meteor solution, but it should work.

In general, we should probably have `onReset` for custom input types, though, in which case you could define this as a custom input type.

**Comment by atoy40** [comment]
Hi, I'll be very happy with a onReset method in custom type :) .
I'm currently writing a set of input types to edit geojson data (point, linestring, etc...) based on leaflet, but i haven't found a way to catch form reset inside the custom type. For exemple, even if I hide some inputs tag in the template to store values, there is no "change" event to catch the value reset when a form reset his fired.

Have you an idea to go arround with a onReset handler ?

Anthony.
