### ISSUE TITLE
Theme Templates: Accept `div-` prefixed attributes on `afFormGroup` and add them to the div

### ISSUE THREAD

**Issue by Pushplaybang** [Meteor-Community-Packages/meteor-autoform#779]
Hey there 

I was wondering if its at all possible to add custom classes to the form-group wrapper around each form thats generated, directly from the schema, as this would make layout on quick forms incredibly easy.

Had a quick go, but can't seem to get it to work, and can't find any docs mentioning it.  Is it all possible?

thanks and regards

Paul

**Comment by elGusto** [comment]
You can just do something like this:

```javascript
bio: {
    type: String,
    max: 500,
    autoform: {
      afFieldInput: {
        type: 'textarea',
        class: 'test'
      }
    }
  },
```

**Comment by aldeed** [comment]
I don't think the built in form group template supports classes on the div, but it's easy enough to make your own template that does.

**Comment by Pushplaybang** [comment]
Okay cool, would be a pretty sweet feature though in terms of doing the form layout incredibly quickly, used nth-child classes in a prototype I'm building but I its not ideal.
