### ISSUE TITLE
Getting page reload in AutoForm update form after upgrade into 5.0

### ISSUE THREAD

**Issue by chompomonim** [Meteor-Community-Packages/meteor-autoform#809]
Any ideas why after upgrade into 5.0 in `type="update"` forms (both with quickForm and autoForm) I'm getting page reload when clicking on submit button?

**Comment by mologie** [comment]
Something in your form or its hooks probably throws an exception. The code which catches the click event on the submit button is never run, causing the browser to do what browsers do: Submit the form. This looks like a page reload.

Navigate to the form, [enable breaking on exceptions](https://developer.chrome.com/devtools/docs/javascript-debugging#pause-on-exceptions), then hit the submit button.

**Comment by MichaelJCole** [comment]
Nice!  Thanks!
