### ISSUE TITLE
Autoform.resetForm doesn't work in iron router onStop hook

### ISSUE THREAD

**Issue by ripdog** [Meteor-Community-Packages/meteor-autoform#812]
Iron router runs its onStop hook before the rendered templates are torn down, which makes it the perfect place to reset the form I'm using. I reuse the same form for both editing and creation of objects, so in the onStop hook for my edit route, I run the following code:

``` javascript
    onStop: function() {
        console.log("edit onstop");
        Session.set("formForInsert", true);
        Session.set("currentlyEditingDoc", null);
        AutoForm.resetForm("insertAppointmentFormInner");
    }
```

formForInsert sets the autoform to insert mode and currentlyEditingDoc is, well, the doc ID being edited. The resetForm call doesn't do anything, for some reason. Switching from the edit route to the insert route will leave the form populated with the old edited item values, despite the fact that the form has been reset, has no assigned document, and is in insert mode.

No error is thrown, like what happens if I run resetForm too early.

Is this supposed to work? If not, is there a recommended pattern? (Also, is it intentional that resetForm doesn't insert default and auto values? Is there a way to reset the form and then insert those values?)

**Comment by aldeed** [comment]
`resetForm` does not mean "clear form", it means reset to initial values, which for an update form means it resets to the values from the `doc` attribute. You are setting the doc to `null` before resetting, but you are calling `resetForm` before Tracker flushes. Try

```js
onStop: function() {
        Session.set("formForInsert", true);
        Session.set("currentlyEditingDoc", null);
        Tracker.afterFlush(function () {
          AutoForm.resetForm("insertAppointmentFormInner");
        });
    }
```

**Comment by ripdog** [comment]
Thank you! That does indeed work. However, when I navigate from the edit
route to the insert route, the form is now completely blank, devoid of
the default values. I need these values in there.

Heres the schema declaration:

```javascript length: { type: Number, label: "Appointment length", min:
5, autoform: { value: 15 }, defaultValue: function() { //blahblah return
provObject.appointmentLength; }, }, ``` Neither the autoform value nor
defaultValue are respected. The form: ``` {{> afQuickField name='length'
step=5 value=length}} ``` Length is correctly provided.

If resetForm is supposed to reset to initial values, why do none of my
defaults get set?

On Tue, Mar 24, 2015, at 02:24 AM, Eric Dobbertin wrote:
> resetForm does not mean "clear form", it means reset to initial
> values, which for an update form means it resets to the values from
> the doc attribute. You are setting the doc to null before resetting,
> but you are calling resetForm before Tracker flushes. Try


> onStop: function() {
        Session.set("formForInsert", true);
        Session.set("currentlyEditingDoc", null);
        Tracker.afterFlush(function () {
        AutoForm.resetForm("insertAppointmentFormInner"); }); }
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/aldeed/meteor-autoform/issues/812#issuecomment-84995582

**Comment by ripdog** [comment]
Thank you! That does indeed work. However, when I navigate from the edit route to the insert route, the form is now completely blank, devoid of the default values. I need these values in there.
 
Heres the schema declaration:
 
```javascript
    length: {
        type: Number,
        label: "Appointment length",
        min: 5,
        autoform: {
            value: 15
        },
        defaultValue: function() {
            //blahblah
            return provObject.appointmentLength;
        },
    },
```
Neither the autoform value nor defaultValue are respected. The form:
```
{{> afQuickField name='length' step=5 value=length}}
```
Length is correctly provided.
 
If resetForm is supposed to reset to initial values, why do none of my defaults get set?

**Comment by aldeed** [comment]
The `value=length` will take precedence over `autoform.value` and `defaultValue`. I'm not sure why it would be cleared. I might have to test this case, but I'm pretty sure it usually works.
