### ISSUE TITLE
afQuickField is always text Input with autoform

### ISSUE THREAD

**Issue by huvber** [Meteor-Community-Packages/meteor-autoform#821]
Probably after update i noticed that `afQuickField` doesn't seem to adapt to the type of field in the schema as before. I have a field with options defined but the `afQuickField` is still a text input. I will paste the schema fragment and the definition.

``` javascript
...
  io_type: {
    type:   String,
    label:  'Categoria',
    autoform: {
      options:{input:'Input',output:'Output',io:'I/O'}
    }
  },
...
```

This is a part of a Schema and I want to use the `foreach` statement to create automatically the fields. Here the spacebars template:

``` handlebars
....
{{#autoForm  id="ctypeform" schema=ctypeSchema doc=this}}
     {{#each afFieldNames omitFields="icon"}}
         {{> afQuickField name=this.name options=afOptionsFromSchema }}
     {{/each}}
     {{> afQuickField name="icon" type="cfs-file" collection="ctypeicons" template="bootstrap3"}}
     <div><button type="submit">Submit</button></div>
{{/autoForm}}
....
```

and here is the generated html

``` html
<div data-required="true">
    <label for="c4wPYFkRGnsiS2Gwa">Categoria</label>
    <input type="text" name="io_type" id="c4wPYFkRGnsiS2Gwa" required="" data-schema-key="io_type"> 
    <span></span>
</div>
```

**Comment by aldeed** [comment]
I know this usually works, but maybe there is a slight difference with yours. Some things you could try:

- Make `options` in the schema be a function that returns that value instead of setting to the value itself.
- Use `afQuickField: { options: //etc... }` or `afFieldInput: { options: //etc... }` in the schema instead of just `options`.

**Comment by huvber** [comment]
Ok I tried all three solution you gave:
* Make `option` a function: unfortunately didn't change anythings
* `asQuickField` with plain `option` parameter: didn't work too
* `asQuickField` with  `option` as function: didn't work too
* `afFieldInput` with plain `option` parameter: nope :(
* `afFieldInput` with  `option` as function: nope :'(

**Comment by aldeed** [comment]
@huvber I'm having trouble reproducing this. Please link to a repo with a simple reproduction app so I can clone and investigate.

**Comment by aldeed** [comment]
Please retest with AutoForm 5.1.0 and close if your issue is resolved.
