### ISSUE TITLE
AutoForm.getFieldValue('someField', 'someId') does not rerun reactively when form with the id become available

### ISSUE THREAD

**Issue by koszta** [Meteor-Community-Packages/meteor-autoform#822]
When I call
`AutoForm.getFieldValue('someField', 'someId');`
it throws
`"AutoForm.viewForForm: Unable to find autoForm view"`
but when the form finished rendering, it does not rerun.

**Comment by miri-am** [comment]
Does using it without the formID work for you? ```AutoForm.getFieldValue('someField')```

**Comment by koszta** [comment]
I tried it previously, but unfortunately, it did not work.

**Comment by BradRyan** [comment]
I'm having a similar issue.  My helpers are outside of the the autoForm so I am including form Id.  I get the following error:

Exception in template helper: Error: No form with ID tripType is currently rendered. If this call originated from within a template event or helper, you should call without passing a formId to avoid seeing this error

If I use it without form Id (contrary to what the docs suggest) I get the same error as koszta was getting.

**Comment by BradRyan** [comment]
Is there some way to get the function to wait for the page to render or run again as koszta suggested?  I'd prefer for it to wait rather than rerunning and filling the log with errors until it finds it.

**Comment by BradRyan** [comment]
So I have a workaround for this at the moment, but I think it's less than ideal.  For the templates which I am getting this error, I'm wrapping the helper functions in something like 

```
{{#if templateRendered}}
  <!-- helpers whose AutoForm.getFieldValue functions fire too early here -->
{{/if}}
```

Where templateRendered is essentially a session variable that is being set to true when the template is rendered, and false when it is destroyed.

```
Template.MyTemplate.onRendered(function() {  
	Session.set("MyTemplate", true);
});

Template.MyTemplate.onDestroyed(function() {  
	Session.set("MyTemplate", false);
});

Template.MyTemplate.helpers({
	templateRendered: function() {
		return Session.get("MyTemplate");
	}
});
```

Let me know if anyone knows of a better way to handle this.  Thanks!

**Comment by sirpy** [comment]
same issue, i think it used to work in previous versions....

**Comment by aadamsx** [comment]
Looks close to mine: #877, and also #876, and #875

**Comment by bmanturner** [comment]
Finding a workaround for template subscriptions based on a field value was a pain. I used an event handler to change a session variable every time the value changed.

**Comment by aadamsx** [comment]
Thanks for that @bmanturner, do you mind sharing a little code to help out?

**Comment by bmanturner** [comment]
@aadamsx So sorry I didn't see this sooner. I hope this is still relevant!

    Template.myTemplate.onCreated(function() {
      var self = this;

      self.autorun(function() {
        var formFieldValue = Session.get('autoFormFieldValue');
        if (!!formField) {
          self.subscribe('publicationBasedOnFormFieldValue', formFieldValue);
        }
      });
    });

    Template.myTemplate.events({
      'change #form-field-id': function(e, tmpl) {
        e.preventDefault();
        Session.set('autoFormFieldValue', tmpl.$(e.currentTarget).val());
      }
    });

**Comment by aadamsx** [comment]
Thanks.  I was able to solve my problem by just doing better defensive coding in my case (if the return from the autoform value is not there, return null, etc.).  But your example is spot on in terms of template level subscriptions.

**Comment by aadamsx** [comment]
@bmanturner, defensive checks wasn't enough, I ended up doing the same thing as you:

'Finding a workaround for template subscriptions based on a field value was a pain. I used an event handler to change a session variable every time the value changed.'

Except I'm using ReactiveDict instead of session variables.  Basically I implemented my own reactive events and helpers that took the place of getFieldValues from autoform.  

You're right, it was a pain but now I feel better knowing it won't break with upgrades like it has so many times in the past (my experience is this portion of autoform has had many issues).

**Comment by jkd65** [comment]
Along with this issue, I was trying to call AutoForm.getFieldValue on a button event which would through the error `AutoForm.viewForForm: Unable to find autoForm view`

To solve this (probably poorly) I just put the button in another template and called the event for that template. Works now!
