### ISSUE TITLE
Dynamic arrays: Clicking "plus" button sets doc to null

### ISSUE THREAD

**Issue by nQk2** [Meteor-Community-Packages/meteor-autoform#828]
If you add update/insert functionality to my example here (https://github.com/aldeed/meteor-autoform/issues/762), in update mode, clicking the "plus" button sets doc to null.

**Comment by nQk2** [comment]
I found a workaround: I'm listing the products in a ```<ul>```. In the ```<li>``` click event I'm setting the session variable which doc relies on. This event handler is somehow called when clicking "plus", so before setting the variable, I check if this._id is defined.
```
  Template.hello.events({
    'click li': function () {
      if (this._id) // that check shouldn't be necessary, right?
        Session.set("selected", this._id);
    }
  });
```

**Comment by dburles** [comment]
I've experienced this issue too
