### ISSUE TITLE
Dynamic arrays: Clicking "minus" sets field to null instead of removing it

### ISSUE THREAD

**Issue by nQk2** [Meteor-Community-Packages/meteor-autoform#840]
Like in https://github.com/aldeed/meteor-autoform/issues/762 and https://github.com/aldeed/meteor-autoform/issues/828, clicking the "minus" button (and then submitting the form) sets the to-be-removed field to null instead of removing it. After clicking submit, the field reappears with empty values.

**Comment by hockeyj85** [comment]
This seems to be the same as #775, which is closed now.

Here's a minimal example that I already had handy from that: https://github.com/hockeyj85/autoforms-5-array-bug

**Comment by workflow** [comment]
Can confirm - bug is still here in 5.1.2. Happens on any array items except the first one.

@hockeyj85 Love your last commit message on the example ;)

**Comment by proxiper** [comment]
Can confirm too. In 5.1.2 it sets to null any item except the last one.

**Comment by Blood-dm** [comment]
A quick fix for now, if you don't want null inside your array->
Coffeescript:
```coffeescript
AutoForm.hooks
  editCollectionForm:
    before:
      update: (doc)->
        if doc.$set?.items?
          doc.$set.items = _.without(doc.$set.items, null)
        doc
```
JS:
```javascript
AutoForm.hooks({
  editCollectionForm: {
    before: {
      update: function(doc) {
        var ref;
        if (((ref = doc.$set) != null ? ref.items : void 0) != null) {
          doc.$set.items = _.without(doc.$set.items, null);
        }
        return doc;
      }
    }
  }
});
```

**Comment by briansayles** [comment]
Can confirm too. In 5.1.2 it sets to null any item that has been removed, even the last one. Happens on all array items.

**Comment by richarddewit** [comment]
@Blood-dm - thanks for the awesome (temporary) solution

**Comment by TimVenison** [comment]
Has there been any update on this bug?

**Comment by felberj** [comment]
@Blood-dm thanks for your workaround ;-)

**Comment by cosio55** [comment]
+1 to this error

**Comment by rafaelcorreiapoli** [comment]
+1

**Comment by livimonte** [comment]
The bug is still happening on 5.8.1. I solved with "initialCount:0" and updating doc before insert, but i make it little different which @Blood-dm.

```javascript
  states: {
    type: [Schemas.States],
    label: "Estados",
    optional: true,
    autoform: {
      initialCount:0
    }
  },

------

  AutoForm.addHooks(['EditLocationsForm'], {
    before: {
      update: function(doc) {
        doc.$set.states = doc.$set.states.filter(function() { return true; });

        _.each(doc.$set.states, function (item, i){
          if(!_.isUndefined(item.cities)){
            doc.$set.states[i].cities = item.cities.filter(function() { return true; });
          }
        });

        return doc;
      }
    }
  });

**Comment by osv** [comment]
I add to global:
```
// Fix null array items
// See https://github.com/aldeed/meteor-autoform/issues/840
AutoForm.addHooks(null, {
  before: {
    update: function(doc) {
      _.each(doc.$set, function(value, setter) {
        if (_.isArray(value)) {
          var newValue = _.compact(value);
          doc.$set[setter] = newValue;
        }
      });
      return doc;
    }
  }
});
```

**Comment by allenfuller** [comment]
Still getting this error as well. Thanks to everyone for the workarounds until there's a fix.

**Comment by yim1990** [comment]
+1

**Comment by thomasmenegotto** [comment]
+1

**Comment by semeano** [comment]
+1

**Comment by semeano** [comment]
In case you're using [meteor-admin](https://github.com/yogiben/meteor-admin), use @osv's solution but with _formToModifier_ instead of _update_ form type.

**Comment by alvara** [comment]
still having this issue. +1

**Comment by artemSoliar** [comment]
+1

**Comment by joshuagamboa** [comment]
+1

**Comment by Murukaen** [comment]
+1

**Comment by diuzzoli** [comment]
I extend array object to aggregate 'clean function'

`
Array.prototype.clean = function(deleteValue) {
    for (var i = 0; i < this.length; i++) {
        if (this[i] == deleteValue) {
            this.splice(i, 1);
            i--;
        }
    }
    return this;
};
`

then I use the new function into AutoForm.hooks

`AutoForm.hooks({
    MyForm: {
        before: {
            update: function(doc) {
                doc.$set.myItem = doc.$set.myItem.clean(undefined)
                return doc;
            }
        }
    }
});
`

**Comment by thumptech** [comment]
+1

**Comment by keyscores** [comment]
+1, using @osv fix worked. Can anyone contribute a pull request?

**Comment by pfmziota** [comment]
I don't know if anybody is still annoyed by this but here is my fix :

Add this code in the client (this just overrides the `cleanNulls` function from `Autoform.Utility` and adds a filter if the value is a non-empty array)

```
function isBasicObject (obj) {
    return _.isObject(obj) && Object.getPrototypeOf(obj) === Object.prototype;
}

AutoForm.Utility.cleanNulls = function cleanNulls(doc, isArray, keepEmptyStrings) {
    let newDoc = isArray ? [] : {};
    _.each(doc, function(val, key) {
        if (!_.isArray(val) && isBasicObject(val)) {
            val = AutoForm.Utility.cleanNulls(val, false, keepEmptyStrings); // recurse into plain objects
            if (!_.isEmpty(val)) {
                newDoc[key] = val;
            }
        } else if (_.isArray(val)) {
            val = cleanNulls(val, true, keepEmptyStrings); // recurse into non-typed arrays
            if (!_.isEmpty(val)) {
                newDoc[key] = val.filter(Boolean); // FIX : added a filter to remove empty values as indexes are kept after removal by cleanNulls function
            }
        } else if (!AutoForm.Utility.isNullUndefinedOrEmptyString(val)) {
            newDoc[key] = val;
        } else if (keepEmptyStrings && typeof val === 'string' && val.length === 0) {
            newDoc[key] = val;
        }
    });
    return newDoc;
};
```

This clears any issue I've had so far with deletion in arrays.
