### ISSUE TITLE
AutoForm.getFieldValue return undefined, after submit update.

### ISSUE THREAD

**Issue by agusputra** [Meteor-Community-Packages/meteor-autoform#843]
I have a form with `type='update'`.
And I have a templete helper that use `AutoForm.getFieldValue`.
But after I submit my form, then `AutoForm.getFieldValue` return undefined (while `AutoForm.getCurrentDataForForm` return the data).

It seems `AutoForm.getFieldValue` not reactive. Is it a bug ? Or is there another way that I can get the FieldValue ?

**Comment by garenor** [comment]
AutoForm.getFieldValue is indeed not reactive. See the docs: https://github.com/aldeed/meteor-autoform#getting-current-field-values. 

There are plenty of hooks you can use witch receive the insertDoc, updateDoc or modifier, from where you can do plenty of awesome things :)

**Comment by aldeed** [comment]
Actually getFieldValue is reactive, but getFormValues is not. Field value tracking needs a complete rewrite. Hopefully I can get to it within the next week. I think I know what needs to happen to resolve all the outstanding field value issues.

**Comment by agusputra** [comment]
Thanks aldeed.

Actually I just want to use afFieldValueIs. Because `getFormValues` is not reactive and
until this issue is fixed, temporary I get the FieldValue using `Autoform.getCurrentDataForForm`.
```
fieldValueIs: function () {
    var kw = arguments[arguments.length - 1];
    var mDoc = new MongoObject(AutoForm.getCurrentDataForForm().doc);
    var name = kw.hash.name;
    var value = kw.hash.value;
    var dataValue = mDoc.getValueForKey(name);

    return dataValue === value;
}
```

And use this inside template:
```
{{#if fieldValueIs name='name' value='value'}}
    
{{/if}}
```
