### ISSUE TITLE
Form disappering for a few ms when submitting a update form

### ISSUE THREAD

**Issue by nate331** [Meteor-Community-Packages/meteor-autoform#846]
When submitting an update quickform or autoform the form seems to disapper for a few milliseconds. This results in the following content to shift up for a few millisonds. It looks like a short flickering then. Not very nice. Does not happen with an insert form. Did not happen with AF 4.

Reproduction: https://github.com/nate331/flickeringReproduction

**Comment by aldeed** [comment]
I don't think there's any way to fix without removing the workaround for the form resetting issue, but we can't remove that until Meteor fixes it.

**Comment by gwendall** [comment]
+1

**Comment by nate331** [comment]
Another problem I face because of this issue: I am conditionally showing a field of the form depending on another fields value (see attached code). This is working fine until I submit the form (and stay on the same page). After submission the noVat helper returns undefined (because when the helper runs the form did not reappear yet) and therefore it does not work properly anymore.
Is there a nice way to deal with that? I can only think of pretty complicated work arounds.

template.html:
```
{{#autoForm collection="Consultants" id="updateTaxNumberForm" class="form-squared" type="update" doc=editingDoc}}
    {{> afFieldInput name="settings.noVAT" type="boolean-radios"}}
    {{#if noVat}}
        {{> afQuickField name="settings.infoText" rows="5"}}
    {{else}}
        {{> afQuickField name="settings.VAT" type="text"}}
    {{/if}}
    <button type="submit" class="btn btn-primary pull-right">Speichern</button>
{{/autoForm}}
```
helpers.js:
```
Template.consultant_settings_page.helpers({
    noVat: function () {
        return AutoForm.getFieldValue("settings.noVAT");
    }
});
```

**Comment by leonidez** [comment]
@nate331 My workaround is to handle validation/submission of the form myself. In my example the submit button is removed from the autoform:

```
{{#autoForm
  id='event-base-form' collection='Events'
  type='update' doc=currentEvent class='col s12'
}}
  <div class='row'>
    <div class='input-field col s12'>
      {{> afFieldInput name='title' id='title'}}
      <label for='title'>Event Title</label>
    </div>
  </div>

  <div class='row'>
    <div class='input-field col s12'>
      {{> afFieldInput name='description' id='description'}}
      <label for='description'>Description (optional)</label>
    </div>
  </div>

  {{> afQuickField name='isPlusOne'}}
{{/autoForm}}

```

In its place I have a button outside the form for which I handle a click action:
```
  'click #event-edit-main-submit': function(){
    var formId = 'event-base-form';
    var validated = AutoForm.validateForm(formId);
    var updates;

    if (validated) {
      updates = AutoForm.getFormValues(formId).updateDoc;
      Meteor.call('updateEvent', this.currentEvent._id, updates);

      EA.Params.setParam('event-form', null);
    }
  },

```

This will validate the form (along with displaying form errors if they exist) and allow you to do whatever actions are required if form submission is successful.

**Comment by 57even** [comment]
Are there any updates about this problem?

**Comment by abernix** [comment]
The fix is dependent on meteor/meteor#2431 getting fixed.  Right now, the autoform form is being destroyed (intentionally) as the solution for that, which is unfortunately, necessary.  Once meteor fixes this bug, this can be resolved.

**Comment by PolGuixe** [comment]
if you add `autosave=true` it prevent the reload from happening.

**Comment by GeniusAlex** [comment]
This problem fixed with resetOnSuccess=false

For example: +quickForm(id='editApp' collection='Apps' type='update' doc=doc resetOnSuccess=false)
