### ISSUE TITLE
Autoform runs validation on disabled field

### ISSUE THREAD

**Issue by mwarren2** [Meteor-Community-Packages/meteor-autoform#852]
I notice that validation is run on a field even if it is disabled, which intuitively would be wrong.

**Comment by aldeed** [comment]
The [selector](https://github.com/aldeed/meteor-autoform/blob/40a3a75ab2435351ad03ab3fe027c1b38ebb9dd4/autoform-inputs.js#L192) should be omitting disabled fields. Can you provide a reproduction of the issue?

**Comment by mwarren2** [comment]
Presumably then I am doing something wrong.
The code has been used successfully to insert a bare Meteor user.

Here's the template code:
<template name="signUpFormAutoForm">
            {{#unless currentUser}}
                {{#autoForm collection="Meteor.users"
                            schema="Schemas.SignIn"
                            id="signUpForm"
                            type="insert"}}
                    <fieldset>
                        {{> afQuickField name="email"}}
                        {{> afQuickField name="password" type="password" disabled="true" id="password"}}
                        <div>
                            <button class="btn btn-primary btn-lg sg-btn-primary"
                                    id="signUpFormAutoFormButton" type="submit">{{findTranslation 'trans_continue'}}</button>
                        </div>
                    </fieldset>
                {{/autoForm}}
            {{/unless}}
</template>


And here's the html:

<form id="signUpForm" novalidate="novalidate">
                    <fieldset>
    <div class="form-group" data-required="true">
    <label for="rtp8BQ4CPS9m6tRwn" class="control-label">Email</label>
    <input type="text" name="email" id="rtp8BQ4CPS9m6tRwn" required="" data-schema-key="email" class="form-control">    
    <span class="help-block"></span>
  </div>    
   <div class="form-group" data-required="true">
     <label for="password" class="control-label">Password</label>
    <input type="password" name="password" disabled="" id="password" required="" data-schema-key="password" class="form-control">    
    <span class="help-block"></span>
  </div>    
                        <div>
                            <button class="btn btn-primary btn-lg sg-btn-primary" id="signUpFormAutoFormButton" type="submit">Continue</button>
                        </div>
                    </fieldset>
                
  </form>

And the schema:

Schemas.SignIn = new SimpleSchema({
    email: {
        type: String,
        regEx: SimpleSchema.RegEx.Email
    },
    password: {
        type: String,
        min: 8
    },
    createdAt: {
        type: Date,
        defaultValue: new Date()
    },
    profile: {
        type: Object,
        defaultValue: {}
    }
});

**Comment by aldeed** [comment]
From docs:

> When providing a boolean attribute, set it to true (no quotation marks) or a helper that returns true.

**Comment by mwarren2** [comment]
So you mean it should be like this?
    {{> afQuickField name="password" type="password" disabled=true id="password"}}

It's still validating that field.

**Comment by aldeed** [comment]
Is the field actually disabled? Has `disabled` class when you look at the DOM?

**Comment by mwarren2** [comment]
The field is actually disabled, can't use it (Chrome canary latest)

Here's the DOM

    <input type="password" name="password" disabled id="password" required data-schema-key="password" class="form-control">

**Comment by aldeed** [comment]
I think the problem is `type="insert"` and `collection="Meteor.users"`. Since your form schema doesn't match the correct users schema, the error may actually be coming from the attempt to insert into the users collection. You shouldn't insert into that collection on the client. You should have an `onSubmit` handler for your form and call [Accounts.createUser](http://docs.meteor.com/#/full/accounts_createuser) to do it properly.

**Comment by mwarren2** [comment]
That's what I'm doing, in fact, and successfully

**Comment by mwarren2** [comment]
However since I am doing something à la carte, I think I shall have to try do all the html myself and try to use Autoform for validating behind the scenes.

**Comment by allenfuller** [comment]
I have run into this issue on the Meteor.users collection as well. It's validating on emails.$.verified, even though I have marked the field as disabled in the schema. If I set `disabled: true`, when I submit the form it displays an error message that "Verified is required." I would make the field optional, but am nervous that could open it up to removing the validation status elsewhere.

**Comment by Roshdy** [comment]
i think the problem is with `required`, try setting the field to `optional: true`
