### ISSUE TITLE
Checkboxes to a [Bollean] field type  

### ISSUE THREAD

**Issue by engenheiro** [Meteor-Community-Packages/meteor-autoform#855]
How I can pass the checkboxes data to a Schema with a field [Bollean] type?

I have a few services in a form dinamicaly created using a helper to populate the form with checkboxes and I dont know how I send the data to SimpleSchema with the name and value for each field.

The SimpleSchema its simple: 

BridesServicesList = {
    services: {
        type: [Boolean]
    }
};

And the form too, only with `<input type="checkbox" name="idService" checked>`

**Comment by aldeed** [comment]
You should use the `afFieldInput` component to render the inputs so that autoform recognizes them and knows how to get their value.

**Comment by engenheiro** [comment]
Ok, if I expose the options on the Schema, but Im using a helper (Its more simple) to pickup the checkboxes from the database dinamically (What I need). I tried to create a SimpleSchema with database data, but its so complex to do, because the same code needs to be run on Server and Client in different times (to create and validate the form), what is driving the process of creation and validation of the form, confusing.

Theres a way to create inputs checksbox dinamically using a helper and send to a SimpleSchema with a [Boolean] field type? Or another way?
