### ISSUE TITLE
autoform too slow on Cordova

### ISSUE THREAD

**Issue by ghost** [Meteor-Community-Packages/meteor-autoform#858]
Hi there,

good to hear that the recursion problem seems to be fixed now. Thx to the Meteor core dev team.

I am trying to get autoform to run on Cordova/Mobile with famous-views and it seems a bit slow.
If the user types something, it takes some seconds until the characters are displayed on the screen.
I dont know if this is bad, but might degrade the overall UX.
So are there others who have managed to make it run?
Can this be improved or are there just too many calculations in the background which make it slower?
Without famous-views it was also slow, I think famous improved it a little bit, but not as fast as with Mesosphere.

Regards

**Comment by aldeed** [comment]
There shouldn't be anything happening while typing unless you have keyup validation enabled. Did you put an `input` element by itself outside of an autoform and see if there is a delay on that.

**Comment by der-ede** [comment]
one minute, just checking
