### ISSUE TITLE
datetime-local (and probably others) don't play well with autosave=True

### ISSUE THREAD

**Issue by jfly** [Meteor-Community-Packages/meteor-autoform#867]
I have trouble editing datetime-local fields in Chrome with autosave=True. The problem seems to be due to the fact that autoform is setting the `.value` of the input I'm editing with a value that's different than the current value.

For example, when typing into an `input type="datetime-local"`, I see the following on https://github.com/aldeed/meteor-autoform/blob/master/inputTypes/datetime-local/datetime-local.js#L5

``` javascript
> val
Wed Apr 30 3 23:59:00 GMT-0700 (PDT)
> AutoForm.Utility.dateToNormalizedLocalDateAndTimeString(val, atts.timezoneId)
"0003-04-30T23:59:00.000"
```

This eventually results in the following if statement running in [attrs.js](https://github.com/meteor/meteor/blob/c22de092e9c5435cbdaa18ef5c27117b2d7ccba4/packages/blaze/attrs.js#L176):

``` javascript
var ValueHandler = AttributeHandler.extend({
  update: function (element, oldValue, value) {
    if (value !== element.value)
      element.value = value;
  }
});

> element
<input type=​"datetime-local" name=​"registrationOpenDate" id=​"uiENhKmFuDygkivAc" data-schema-key=​"registrationOpenDate" class=​"form-control">​
> element.value
"0003-04-30T23:59"
> value
"0003-04-30T23:59:00.000"
```

This if statement shouldn't run because the values are really the same, but `AutoForm.Utility.dateToNormalizedLocalDateAndTimeString` formats the time string with seconds, which screws this all up (for chrome at least, I don't know how other browsers behave).

**Comment by jfly** [comment]
This is kind of related to #774.

**Comment by jfly** [comment]
@jankapunkt, just curious: why did you close this?

**Comment by jankapunkt** [comment]
Hi @jfly the issue is 6 years old and I closed all before 2020. We did a major update to v7. If this issue persists in v7 feel free to reopen and I will dedicate some time to resolve it.
