### ISSUE TITLE
Add help attribute to afFormGroup for field help text

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#868]
I remember we talked about this a while back, but what would you think about adding instructions to fields? Unlike the validation message, these instructions would be displayed at all times under or near each field.

**Comment by SachaG** [comment]
(Oh and I'm happy to submit PRs for both this and the `cssCass` thing)

**Comment by tom2strobl** [comment]
+1

I'd imagine something like
```
autoform: {
   help: "Try to use actionable verbs for the description."
}
```
in the schema, which could render a classed ```div``` inside the ```.form-group```.

**Comment by kyooriouskoala** [comment]
+1

**Comment by cwaring** [comment]
+1

A solution to this would be great. Does anyone have a workaround in the meantime?

**Comment by SachaG** [comment]
If @aldeed thinks this would be a good feature to have, I'm happy to start working on it as soon as the field group stuff is released.

**Comment by cwaring** [comment]
After considering it a little more maybe it will be adequate to add a data element to the field and use a helper function to generate the inline element or hover help block?

```js
autoform: {
  "data-help": "A longer help description for this field"
}
```
Perhaps this could be provided by an extension package rather than adding additional markup in core?

Keen to hear your thoughts @SachaG & @aldeed.

**Comment by SachaG** [comment]
@cwaring Personally I feel like this is a common enough use case that it could just be built in the core templates.

**Comment by cwaring** [comment]
Yeah, it does feel more like a core feature and it would be useful, especially for explaining groups of fields in more detail.

Happy to pitch in if you have an idea of how this should be built.

**Comment by SachaG** [comment]
Something like:

```
autoform: {
   help: "Try to use actionable verbs for the description."
}
```

Seems good to me. After that it's just a matter of adding it to the default templates I imagine?

**Comment by aldeed** [comment]
I am OK with a `help` attribute and corresponding `autoform.help` in the schema. The afFormGroup and maybe also afObjectField and afArrayField input types and their templates will need to be updated to display the text as appropriate for the various cases.

**Comment by thebarty** [comment]
+ one for this request.

It's related to https://github.com/aldeed/meteor-autoform/issues/1215

**Comment by sakulstra** [comment]
:+1: this would be a really nice feature

**Comment by abhaytalreja** [comment]
+1 for this feature, has this been done yet?

**Comment by thebarty** [comment]
As far as I know: nope.

You can extend simpleschema to accept the data by doing something like:
```
SimpleSchema.extendOptions({
  // extend schema by help text
  labelHelp: Match.Optional(String),
});
```

BUT the templates in the pacakge need to be adapted to support this... I guess someone needs to do the work and do a PR. :-)

OR: does someone know an easy way to render the data within your templates?

**Comment by cesarve77** [comment]
here a pull request
https://github.com/aldeed/meteor-autoform/pull/1385

with help-block as a text or icon with tooltip o popover

**Comment by navardan** [comment]
+1

**Comment by abate** [comment]
@aldeed Can you please review this PR and maybe merge ?

**Comment by abate** [comment]
a new smaller PR trying to address the same problem : #1650
