### ISSUE TITLE
AutoForm.isFormValid(formId) ?

### ISSUE THREAD

**Issue by rclai** [Meteor-Community-Packages/meteor-autoform#872]
Reactive. This would be pretty helpful.

**Comment by aldeed** [comment]
`AutoForm.getValidationContext(formId).isValid()`

Maybe we just need to clarify this in the docs.

**Comment by rclai** [comment]
Oh wow that's deep.

**Comment by rclai** [comment]
Is that call reactive? As in, am I able to put that inside a template helper in order to say, set `disabled` on a submit button?

**Comment by aldeed** [comment]
Yes, it should be.

**Comment by rclai** [comment]
I noticed that it only works after `AutoForm.validateForm()` is run. Is that intentional? Does `validateForm()` always need to run before?
