### ISSUE TITLE
removeHooks onDestroyed

### ISSUE THREAD

**Issue by emmanuelbuah** [Meteor-Community-Packages/meteor-autoform#873]
Currently, its looks like we can setup auto form processing through its hooks. It would be nice to have the ability to remove a hook object for a form when its destroyed ex. at template.onDestroyed

**Comment by emmanuelbuah** [comment]
Current workaround 

```
 delete AutoForm._hooks.myFormId

```

**Comment by aldeed** [comment]
I don't recommend defining hooks dynamically. They should all be defined in top-level client code rather than in onRendered.
