### ISSUE TITLE
Validation messages don't appear for emails.0.address

### ISSUE THREAD

**Issue by fuatsengul** [Meteor-Community-Packages/meteor-autoform#874]
Hi, I'm using Semantic-UI's modal and for design porpuses they seperated the buttons at bottom from the content side, they are in different divs. So, to use these buttons and styling, I need to not use any submit button inside autoform and when I click an outside button, I have to submit the form.

I tried jquery's .submit() event, but validation fails, callbacks never returns.
So help me out :)
Thanks

Here is some code:

```
<div class="ui modal createUserModal">
    <div class="header">{{_ "admin_createUser_Title"}}</div>
    <div class="content">
        {{#autoForm
                        validation="keyup" 
                        id="createUserForm" 
                        schema=Schema.User
                        placeholder="schemaLabel"
                        type="normal"
                    }}
                        {{> afQuickField name='profile.name'}}
                        {{> afQuickField name='emails.0.address'}}
                        {{> afQuickField name='profile.job'}}
                        {{> afQuickField name='profile.organization'}}
                        {{> afQuickField name='profile.language'}}  
            {{/autoForm}}
    </div>
    <div class="actions">
        <div class="ui black cancel button">Cancel</div>
        <div class="ui ok positive right labeled icon button">
            Create User <i class="checkmark icon"></i>
        </div>
    </div>
</div>
```

**Comment by aldeed** [comment]
$('#createUserForm').submit() is correct

Also, I'm not sure about semantic ui, but with bootstrap modals, it works fine to put the content and action divs both inside the `autoForm`.

**Comment by fuatsengul** [comment]
My problem was little bit complicated.
I figured out that the submit() function works perfectly, 
but validation indicators hasn't been shown for array objects like emails.0.address.

I've searched all documentation but I can't figured it out that: I'm registering an user and I will add only one mail address for this user, so I'm intending to put a single input for e-mail. When I do this as emails.0.address it works as intended but without validation indications.
Maybe there's a better and correct way?

**Comment by aldeed** [comment]
OK, could be a bug. I'll have to investigate.

**Comment by nikhildaga** [comment]
I confirm the bug; am facing the same issue too. Thanks.

**Comment by egoldblum** [comment]
+1

**Comment by Jehu** [comment]
It's an old one, but seems to be still an issue.

**Comment by cesarve77** [comment]
+1

**Comment by twentyfortysix** [comment]
I tried input like this:
`{{> afQuickField name="emails.0.address"}}`
it work but with no validation
but if I use it like this:
`{{> afQuickField name="emails.0"}}`
it not only works but it is validated as well
