### ISSUE TITLE
Issue found when calling AutoForm.getFieldValue

### ISSUE THREAD

**Issue by aadamsx** [Meteor-Community-Packages/meteor-autoform#877]
This issue is probably not with AutoForm.getFieldValue, but I suspect with how I'm setting my form for inserts and updates.

Up until 5.0 everything has worked fine.

Here's the error I'm getting when trying to call AutoForm.getFieldValue:

```
Error: No form with ID MY_FORM_NAME is currently rendered. If this call originated from within a template event or helper, you should call without passing a formId to avoid seeing this error
```

I'm sure you've seen this before, but here's how I'm setting the form mode:

1) I check if I have a record in the DB for that form and user,

```
  if (count === 0)
    return {doc: null, type: "insert"};
  else
    return {doc: dataSet, type: "update"};
```

If I do then I set the type to update with the data, else insert with doc: null.  The dataSet is just a return value from,
`return MY_COLLECTION.findOne({_personId: Meteor.userId()});`

2) The above code is called within a helper on the form template,

```
my_form_Controller.helpers({
  setFormMode: function () {
    return getFormMode(this.MY_FORM_NAME());
  }
});
```

3) Then within the template, I have a `{{#with setFormMode}}`, and within this I set the form attributes like so,

```
{{#autoForm collection="MY_COLLECTION" id="MY_FORM_NAME" doc=doc type=type class="form-horizontal" }}
```

---

The error occurs when I call a `AutoForm.getFieldValue(fieldName, MY_FORM_NAME)` when the form is loading and the controls are being placed on the form....

What is seems like is that the form is not rendered before the call to `getFieldValue()`.  Again, this all worked fine before the upgrade from 4.0.2 to 5.1.2.

**Comment by aadamsx** [comment]
I got around this issue by coding defensively.  I don't just return whatever AutoForm.getFieldValue returns, I check the return value and if it's not a 'good' value I return null or undefined.  No more exceptions and no side effects -- so far.

**Comment by cskaandorp** [comment]
Hi aadamsx, 

I wonder if my problem is related to this one. I am using a similar setup to initiate the form. On update forms, all my conditional input fields are missing. But they appear after I hit refresh. I downloaded the source code and tried to trace what went wrong. I got stuck on these pieces of code:

```javascript
AutoForm.getFieldValue = function autoFormGetFieldValue(fieldName, formId) {
  // find AutoForm template
  var template = AutoForm.templateInstanceForForm(formId);
  if (!template || !template.fieldValuesReady.get() || !template.view._domrange || template.view.isDestroyed) {
    return;
  }
  // reactive dependency
  template.formValues = template.formValues || {};
  if (!template.formValues[fieldName]) {
    template.formValues[fieldName] = new Tracker.Dependency();
  }
  template.formValues[fieldName].depend();
  
  var doc = AutoForm.getFormValues(formId, template, null, false);
  var mDoc = new MongoObject(doc);
  return mDoc.getValueForKey(fieldName);
};
```

The **doc** variable returns an empty object. Since the object is empty, there is no way getFieldValue will return something useful. When checking out **getFormValues** I found out that this line:

```javascript
  // Build a flat document from field values
  var doc = getFlatDocOfFieldValues(getAllFieldsInForm(template), ss);
```

and more specific: the **getAllFieldsInForm** part delivers nothing:

```javascript
getAllFieldsInForm = function getAllFieldsInForm(template) {  
  // Get all elements with `data-schema-key` attribute, unless disabled
  return template.$("[data-schema-key]").not("[disabled]");
  // Exclude fields in sub-forms, since they will belong to a different AutoForm and schema.
  // TODO need some selector/filter that actually works correctly for excluding subforms
  // return template.$('[data-schema-key]').not("[disabled]").not(template.$('form form [data-schema-key]'));
};
```

I am kind of a noob on this. Although the template-parameter seems fine (I can find the correct mongoid record in there), it doesn't return an object needed for getFormValues, like it is not picking up the form yet.

Is this all related to #822? Or do you think I should open another issue??

thanks

Cspr

**Comment by aadamsx** [comment]
Well, I'll try to sum up what I think is going on:

I'm using a template that has a schema and collection attached to it (using Autoform and SimpleSchemas and Collection2).  This template has child or sub templates that contain the afFieldsInput templates.  Inside these child templates I have logic that calls out to AutoForm.getFieldValue.  

Some of these afFields are radio buttons and some are checkboxes.  Everything worked great until I updated.  Now a few things are happening.  The radio buttons, where I have show/hide logic that calls out to getFieldValues, no longer works, and the checkboxes no longer works -- they are no longer reactive.

I've gotten around this by implementing my own reactivity, thereby removing my dependency on getFieldValue for getting form data and reactivity.  Now my forms function find as far as I can tell.

If you post a repo where I can reproduce your situation, I'll take a look and try to help you.  Also, check out forums.meteor.com -- someone might be able to help you there too.  But in general, being able to create a github repo of your issue will help others help you.

Rant:
------
Eventually I want to remove autoform, simple schema, and collection 2 altogether -- and implement my own forms, with reactive validation on the client.  Why would I go through this trouble?  Because I've gotten burned by this and its related package so many times now, I can't put my trust in it any longer.  Every time I upgrade meteor I worry that autoform is going to break again.  

And with almost every upgrade of autoform, something gets fixed, and then something else breaks -- It's a ride I want to get off of, and really not worth the added upfront time savings IMO.

Also, at this point I think aldeed considers this package someone done from what I've read from him.  He's probably just busy, but he's stop responding to my and other's posts.  The problem with that is, I can't build software on a package that has major bugs, where PR are ignored (again probably busy), and doesn't respond to queries.  The guy is just stretch too thin with all the packages he maintains, not to mention the business he runs. 

It's simple enough to build out our own controls, reactive validation, hooks, etc., it will just take a little longer to get going is all.
