### ISSUE TITLE
AutoForm.getFieldValue() does not get value of disabled checkbox

### ISSUE THREAD

**Issue by rclai** [Meteor-Community-Packages/meteor-autoform#891]
This is what I was trying to do in my template:

``` html
{{> afFieldInput name="add" value=true disabled=true}}
{{#if afFieldValueIs name="add" value=true}}
   This is supposed to show but it doesn't (it used to in version 4).
{{/if}}
```

When I debugged, I noticed that `AutoForm.getFieldValue()` returned `undefined` for the checkbox, but when I removed the disabled, it returned `true`.

I don't know if this problem exists with other kinds of inputs.

**Comment by roelvan** [comment]
i have problems too with checkboxes since version 5

**Comment by roelvan** [comment]
I noticed that checkboxes work perfectly when you click them the first time, as soon as you try to toggle it a 2nd, 3rd,... time it doesn't changes it value anymore.

**Comment by rclai** [comment]
Yes, it's trying to be addressed [here](https://github.com/aldeed/meteor-autoform/pull/890).

**Comment by rclai** [comment]
For the meantime I settled on a workaround by enabling the checkboxes and adding an `unclickable` class and attaching it with:

```js
'click .unclickable': function (event) {
  event.preventDefault();
  event.stopImmediatePropagation();
  return false;
}
```

**Comment by roelvan** [comment]
@rclai I created a custom checkbox-fix package to fix this checkbox problem. That way you don't have to touch the core autoform code and it'll be easy to simply remove the input type as soon as there is on official solution for this issue. You can find it here: https://github.com/roelvan/autoform-checkbox-fix

**Comment by rclai** [comment]
Cool, thanks @roelvan.

**Comment by roelvan** [comment]
@rclai I forgot to check the initial value of the schema key, fixed and pushed this update. It should work fine now

**Comment by aldeed** [comment]
According to HTML spec, disabled controls should be considered to have no value. It makes sense to follow this guideline for form submission, which we do, but maybe we could correctly get the value for the reactive value helpers. Otherwise maybe you could just use "readonly" instead of "disabled".
