### ISSUE TITLE
Move documentation to ReadMe.io?

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#894]
I think AutoForm (as well as SimpleSchema and Collection2) is reaching the point where it's complex enough that the documentation is becoming hard to browse here on GitHub. 

I'm in the process of transferring the Telescope docs to http://readme.io, and since they offer free plans for open-source projects I was thinking it might be a good idea to do the same for AutoForm?

**Comment by Tim-W** [comment]
100% support. this would be great for iron:router and other bigger projects as well.

**Comment by SachaG** [comment]
@aldeed if you register an account on Readme.io and give a couple people admin access I think we could probably get started on this?

I'm just bringing it up again because unclear* documentation seems to be one of people's main issues with the SimpleSchema/Collection2/Autoform suite.

*not that the doc's content itself is unclear, just that people are never sure where to look.
