### ISSUE TITLE
Not sure what is happening, help?  TypeError: Cannot read property 'reset' of undefined     at Object.autoFormResetForm [as resetForm] 

### ISSUE THREAD

**Issue by theroadrunnershow** [Meteor-Community-Packages/meteor-autoform#905]
I get this error in the console for a simple insert form. 

I have a feeling it is because of the collection hooks that I have:
ServiceProviders.after.insert(function (userId, doc) {
  console.log("Updating address for inserted ServiceProvider _id=" + doc._id + ", officeaddress="+doc.officeaddress + " , location="+doc.location);
  Meteor.call('UpdateAddressAndLocation', userId, doc);
});

Do you know what I am doing wrong?

Exception:
Exception in delivering result of invoking '/serviceproviders/insert': TypeError: Cannot read property 'reset' of undefined
    at Object.autoFormResetForm [as resetForm](http://localhost:3000/packages/aldeed_autoform.js?b2b90d28d5cc29be68358bb3c8bb8a337992a7dd:2127:26)

**Comment by theroadrunnershow** [comment]
Also, note: the insert actually works, its just that I am getting this error in the client.

**Comment by aldeed** [comment]
If you are still getting this with latest autoform release, please link to a simple reproduction app.

**Comment by runlevelsix** [comment]
For what it's worth, I was experiencing the same (or a very similar) error today and found - by chance - that removing the `id` attributes from both my reset and submit buttons solved the issue.
