### ISSUE TITLE
input-col-class not useful with afFormGroup in case of autoForm

### ISSUE THREAD

**Issue by abhishekbatra** [Meteor-Community-Packages/meteor-autoform#906]
Hi,

For the case where `form-horizontal` class is needed in case of `#autoform` (ref. #787 ) , if `afFormGroup` is used with `label-class="col-sm-3" input-col-class="col-sm-9"` the `label-class` works fine, but `input-col-class` does not.

The reason is `afFormGroup_bootstrap3` does not use a `div` to wrap `afFieldInput`, that would include something like `rightColumnClass` as in case of `afFormGroup_bootstrap3-horizontal`.

I could send a PR for this if wrapping `afFieldInput` with the extra `div` in case of `afFormGroup_bootstrap3` seems meaningful.

Thanks,
Abhishek

**Comment by i-Hun** [comment]
+1
