### ISSUE TITLE
Template.currentdata inside hooks

### ISSUE THREAD

**Issue by Akash-dvd** [Meteor-Community-Packages/meteor-autoform#907]
Hi I cant seem to find any way to access Template data context inside autoform hooks.
this.template also doesn't help.
Can it be an enhancement.

**Comment by SachaG** [comment]
I actually just stumbled on the same issue. It doesn't seem possible to go up the chain using `Template.parentData()` from an AutoForm hook, is there any workaround?

**Comment by SachaG** [comment]
Oh never mind, it looks like I was just not going deep enough. I was able to get the context with:

```
Template.parentData(5);
```

But yeah, it'd be nice to have it accessible as some kind of AutoForm shortcut.

**Comment by Akash-dvd** [comment]
May be autoform should extend the template instance.

**Comment by afriC84** [comment]
Hey there! I had the same issue.
For me the smartest way is to simply pass the data you need into the child template:

```html
{{>quickForm
     id="..."
     collection="..."
     type="insert"
     dataYouNeedInTheAutoFormHooks=customTemplateHelper
}}
```

Your template helper can return anything you want. For example:

```javascript
Template.yourTemplate.helpers({
    customTemplateHelper: function () {
        return Template.currentData();
    }
});
```
Hope that helps.

**Comment by SachaG** [comment]
@afriC84 nice tip! thanks!

**Comment by zimme** [comment]
That's a nice one @afriC84.

I sorta expect `this.template` inside hooks to actually be the `TemplateInstance` of the template in which the autoform helper is used.

**Comment by chiester** [comment]
Excellent! Thanks for the tip.

**Comment by aldeed** [comment]
To me it makes the most sense for the autoform to be a black box, so if you need data from the outside template, you pass it in like @afriC84 said, with `outerData=this` attribute for example. This would be in line with the direction Blaze is going with componentization and lexical scope discussions.
