### ISSUE TITLE
Setting a default control for specific data type

### ISSUE THREAD

**Issue by smeijer** [Meteor-Community-Packages/meteor-autoform#908]
I guess I'm just missing something, but is it possible to set a default control for a specific datatype?

Let's say I've created a template called `fooBarControl`, and I've registered it with:

``` js
AutoForm.addInputType('fooBar', {
  template: 'fooBarControl',
  valueIn: function(value) {
    return value;
  },
  valueOut: function() {
    return this.val();
  }
});
```

Now we can render the control by specifying the template in the schema, like:

``` js
MySchema = new SimpleSchema({
  myField: {
    type: String,
    label: "Enter a value",
    autoform: {
      type: 'fooBar'
    }
  }
});
```

But what if, I wish to make the custom control the default control for all fields with type `String`? So I can omit the "autoform" part from my schema, and still have `fooBarControl` being rendered for each field of type `String`?

**Comment by aldeed** [comment]
There isn't an official way right now, but it's something I've thought about adding.

You can do it unofficially by redefining the `AutoForm.getInputType` function, adding your custom logic in: https://github.com/aldeed/meteor-autoform/blob/devel/autoform-api.js#L766-L857

Need to be sure to pull in any updates to that function with each release then.
