### ISSUE TITLE
Pattern: Schema transforms to control AutoForm fields

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#912]
I'm trying out a new pattern for using SimpleSchema and AutoForm inside Telescope, and I thought I'd share it here to get some feedback. 

If I want one of the schema's fields to be editable, I use the following syntax to specify which roles should be able to edit it:

``` js
  url: {
    type: String,
    editableBy: ["owner", "admin"]
  },
```

I then have a `setPermissions` transform function that loops over the schema and sets `autoform.omit = true` where appropriate (i.e. on fields that are _not_ editable and should be left out of the form):

``` js
SimpleSchema.prototype.setPermissions = function () {
  // this only makes sense on the client, because we set permissions relative to the current user
  if (Meteor.isClient) {
    var schema = this._schema;
    var user = Meteor.user();

    _.each(schema, function (field, key) {
      // if the current user cannot edit field, add autoform.omit = true
      if (!Users.can.editField(user, field)) {
        this[key] = _.extend(field, {autoform: {omit: true}});
      }

    });

  }
  return this;
}
```

(Note: `Users.can.editField` just compared the contents of `editableBy` with the current user's roles)

I can then call the transform on the `posts` schema (chained with an `internationalize()` transform):

``` js
Telescope.schemas.posts = new SimpleSchema({...});
Telescope.schemas.posts.internationalize().setPermissions();
Posts.attachSchema(Telescope.schemas.posts);
```

I used to have some pretty complex `fields=...` logic for every `quickForm` in Telescope, but this approach lets me specify everything at the schema level, so I feel it's cleaner and easier to understand.

**Comment by SachaG** [comment]
Actually this doesn't quite work for a very obvious reason (well, at least it seems obvious now): different documents might have different permissions for different fields. So you can't just set them all at once for a user. 

Still, it might be an interesting pattern to keep in mind and revisit later…

**Comment by KristerV** [comment]
> different documents might have different permissions for different fields.

What do you mean by this?

I want to specify what role can edit each field. Your solution seems to make sense, should I not use this solution?

**Comment by SachaG** [comment]
Actually you can look at Telescope to see how I ended up implementing this: https://github.com/TelescopeJS/Telescope/blob/master/packages/telescope-lib/lib/collections.js#L82-L92

**Comment by aldeed** [comment]
This is an interesting pattern. Not sure how it could be made generic as part of the API, but I will give it some thought.
