### ISSUE TITLE
Add AutoForm.submit('<formId>')

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#913]
What would be the best way to implement keyboard shortcuts for AutoForm, i.e. submitting the form when `ctrl/cmd+enter` is pressed? 

Is there a way to manually trigger a form's submission?

**Comment by zimme** [comment]
```js
this.$('#profileForm').submit();
```
in a click handler is one way to manually submit.

**Comment by SachaG** [comment]
Yeah, I hadn't thought about just using jQuery's form submit event. I was talking about it with @aldeed as well, maybe it'd be cool to have an AutoForm wrapper for this just in case?

**Comment by zimme** [comment]
Maybe, but tbh I don't really see the need when jQuery's `.submit()` trigger is as easy as it is.

Maybe `AutoForm.submit('<formId>')` might help some people out?

**Comment by zimme** [comment]
Also about the keypress submit thing, isn't that default behaviour in browsers?

i.e. when you're on a text input and press enter the form should submit unless you've overridden the keypress event and suppressed it.

I don't know how it is with textareas though.

**Comment by SachaG** [comment]
Yeah, it was for a textarea. 

And I don't know, I figured maybe one day we'll have forms that are not rendered in HTML or something. So we could have a common API in anticipation of the day where we render everything in WebGL ;)
