### ISSUE TITLE
Using the "array of object fields" example... there is an issue removing a middle element from the list

### ISSUE THREAD

**Issue by wesyah234** [Meteor-Community-Packages/meteor-autoform#914]
Using the following schema:

``` js
Books.attachSchema(new SimpleSchema({
  title: {
    type: String,
    label: "Title",
    max: 200
  },
  author: {
    type: String,
    label: "Author"
  },  
  'nestedField' : {
    type:[Object],
    label:"hello"
  },
  'nestedField.$.city': {
    type: String,
    label: "City",
    max: 200
  },
  'nestedField.$.state': {
    type: String,
    label: "State",
    max: 200
  }
}));
```

and creating 3 sets of city/state objects,leaves me with the following in the database:

```
{ 
    "_id" : "ftfxdtGS6BPudexCw", 
    "title" : "df", 
    "author" : "df", 
    "nestedField" : [
        {
            "city" : "one", 
            "state" : "one"
        }, 
        {
            "city" : "two", 
            "state" : "two"
        }, 
        {
            "city" : "three", 
            "state" : "three"
        }
    ]
}
```

Then, going back to edit the record and clicking the MINUS button to remove the middle city/state, gives me:

```
{ 
    "_id" : "ftfxdtGS6BPudexCw", 
    "title" : "df", 
    "author" : "df", 
    "nestedField" : [
        {
            "city" : "one", 
            "state" : "one"
        }, 
        null, 
        {
            "city" : "three", 
            "state" : "three"
        }
    ]
}
```

I would expect just 2 elements under "nestedField" , not that "null" in the middle.

**Comment by metalik** [comment]
I have encountered the same issue using meteor 1.1.0.2 and autoform 5.1.2. No such problem if I fallback to autoform 4.2.2.

below is the meteorpad code for reproducing the issue:

http://meteorpad.com/pad/dC5xXAZddxNYBH2Kj/quickForm-ObjectArray-Bug

**Comment by stachrom** [comment]
jep, I encounter the same "error"

**Comment by st3phan** [comment]
Same here. I can confirm the issue.

**Comment by briansayles** [comment]
Same here. Occurs no matter which item is removed, not just a middle element. Autoform 5.1.2. Also occurs if you use a custom template for each item via afEachArrayItem.

**Comment by JeremyBYU** [comment]
Same here, just experienced it myself. I had some custom code that did poor error checking, now it crashed from the null....

**Comment by JeremyBYU** [comment]
Small fix while using meteor methods for autoform submit.  Remove the null object with the underscore function _.compact. In this case my key that has an array is called params.
```
        updateTag: function(modifier,doc_id){
            //console.log(modifier);
            modifier.$set.params = _.compact(modifier.$set.params)            
            //console.log(modifier);
        	Tags.update(doc_id,modifier);

        },
``

**Comment by bloigge** [comment]
I solved by pulling the null values from my collection in the method:

''''
//MeteorMethod
  updateForm: function(modifier,doc_id){

      if (modifier.$unset) {

      } else {
        modifier.$set.params = _.compact(modifier.$set.params, null)
      };
      MyCollection.update(doc_id,modifier);
      MyCollection.update({_id: doc_id}, {$pull: {"MyItem": null}});
  }
''''

**Comment by ChJJin** [comment]
Same here, with Meteor 1.1.0.2 and AutoForm 5.3.2.

**Comment by agad** [comment]
+1 problem occurs with Meteor 1.2 AF 5.5.1.  Any time an array item that is NOT the last item is removed, everything is thrown out of whack.  The rows keep their names - ie: properties.0.name and properties.2.name (assuming row 1 was removed).  The validation context names are incorrect.  So if properties.2.name is wrong, the validationContext will actually have properties.0.name as being incorrect.  Hope that makes sense.

**Comment by maxnowack** [comment]
same here ...

**Comment by alvara** [comment]
same exact problem here as well..

**Comment by rafinskipg** [comment]
Same problem @agad .

**Comment by mozfet** [comment]
3 years later... confirming this is still an issue with Autoform 6.2.0 on Meteor 1.6.0.1.
