### ISSUE TITLE
Integrate with meteorhacks:ssr

### ISSUE THREAD

**Issue by petermikitsh** [Meteor-Community-Packages/meteor-autoform#915]
Feature request: It would be nice if I could use the beautiful templates from this package (e.g., `quickform`) in server-sider rendering like so:

``` html
<!-- private/quickform.html -->
<html>
  <body>
    {{ >quickForm collection=collection doc=doc id="emailQuickform" type="readonly" }}
  </body>
</html>
```

``` javascript
// server/email.js
Meteor.ssrEmail = function (emailOpts, data) {
  var html = SSR.render('quickform', {doc: ..., collection: ...});
  ...
}
```

In `package.js`, these templates are explicitly limited to client scope (https://github.com/aldeed/meteor-autoform/blob/master/package.js#L126-L127).

Consequently, the following error is thrown:

``` console
I20150427-17:25:29.638(-4)? Exception while invoking method 'bookAppointment' Error: No such template: quickForm
I20150427-17:25:29.640(-4)?     at packages/meteorhacks:ssr/lib/overrides.js:41:1
...
```

**Comment by aldeed** [comment]
This is something we can consider, but I doubt all the Tracker stuff will work properly with SSR. Could be a big project to get it working.
