### ISSUE TITLE
_.debounce autosaveOnKeyup, don't _.throttle

### ISSUE THREAD

**Issue by zimme** [Meteor-Community-Packages/meteor-autoform#916]
`_.debounce` is better for `autosaveOnKeyup`, it will mitigate the "trim spaces" problem but there will still be edge cases when you write one word add a space at the end then wait before continue writing. This will trim the trailing space if `trimStrings` isn't `false`.

I'll try and put together a PR for this during the weekend.

**Comment by aldeed** [comment]
You might be right. Will have to try it.
