### ISSUE TITLE
Autoform insert downloads file on success

### ISSUE THREAD

**Issue by hadynz** [Meteor-Community-Packages/meteor-autoform#923]
I have an Autoform configured to insert a record into a Mongo collection. I would like to serve the user with a file attachment on success afterwards. I am having trouble putting the two together and was hoping to put the question out there in case someone has an answer.

To serve a user with an attachment, I have a server route (using `iron:route`) configured that works correctly:

``` js
Router.route('/download', function () {
  var buffer = fs.readFileSync('./myfile.txt', "utf8");
  this.response.write(buffer);
  this.response.end();

}, {where: 'server'});
```

I am struggling to find the best way to redirect or POST to this route after a successful Autoform transaction.
### Attempt 1

I configured `submitPost` to redirect to my attachment route, however, that didn't work.

``` html
{{> quickForm collection="Posts" id="submitPostForm" type="method" meteormethod="submitPost"}}
```

``` js
Meteor.methods({
  submitPost: function() {
    // Manually insert doc
    Router.go('/download');
  }
});
```
### Attempt 2

I tried to use jQuery to do an AJAX post on success. It doesn't work off the bat of course, and there are some workarounds suggested. This method is too flaky anyway because the download should really be driven by the server.

``` html
{{> quickForm collection="Posts" id="submitPostForm" type="insert"}}
```

``` js
AutoForm.addHooks({
  submitPostForm: {
    onSuccess: function(){
      var doc = this.currentDoc;
      $.post('/download', JSON.stringify(doc));
    }
  }
});
```

I understand this is not directly an AutoForm question, but curious to hear from the AutoForm community what they thought.

**Comment by aldeed** [comment]
I think `Router.go('/download');` in `onSuccess` should work.
