### ISSUE TITLE
How would i integrate mdg:camera

### ISSUE THREAD

**Issue by premesh** [Meteor-Community-Packages/meteor-autoform#926]
A little bit confused on how to get this working. id like to have a button to push that would take a picture ( easy with mdf:camera) and then use that image for the field of a form managed by autoform. ... i actually would have 3 images but assuming if i get it to work with one it should be fine?

**Comment by langfors** [comment]
same question - @premesh - did you get this sorted?

**Comment by xpluscal** [comment]
same question. Any news?

**Comment by tcastelli** [comment]
+1

**Comment by dragugu** [comment]
Hello, is there an update to this question?

**Comment by llvasconcellos** [comment]
@premesh @langfors @xpluscal @tcastelli @ghost
I'm going to do this right now. Did you guys succeed? Any tips?
