### ISSUE TITLE
Bug: AutoForm.validateField() skips fields

### ISSUE THREAD

**Issue by mariorodriguespt** [Meteor-Community-Packages/meteor-autoform#934]
I'm building a wizard and I need validation as I god. I'm using `AutoForm.validateField` to validate only a specific set of fields. On chrome dev tools it works fine because I'm running 1 command at a time, on the code I'm running it inside a loop and that's when I noticed the issue. On my case, the first and last fields got a red visual warning but the remaining fields remained valid.

```
var valid = true;

_.each( instance.fields.metadata , function( field ){
    valid = AutoForm.validateField( 'myForm', field , false ) && valid;
});

if( valid ){
    instance.vars.set( 'current-step' , step +1 );
}
```

But things get even worst: I'm using only select type fields and when I provide a valid value for the first field ( remember that the last one was marked invalid ), all the fields pass the validation and my wizard steps with incomplete data.

I'm not using plugins, just a regular select, and I'm sure that my schema validation is correct.

The only reason why I'm using approach is because `AutoForm.validateForm`on an insert forces to be compliance with all the schema required fields.

**Comment by capensisma** [comment]
Can you try ??

_.each( instance.fields , function( field ){//remove the .metada
    valid = AutoForm.validateField( 'myForm', field , false ) && valid;
});

**Comment by mariorodriguespt** [comment]
That's irrelevant, I'm iterating over that array metadata which is contained in the object fields. `AutoForm.validateField` should return false, unless I'm missing something from the docs.

**Comment by Chun-Yang** [comment]
Have the same problem.
I have two inputs I want to validate like this
```
  var valids = _.map(fields, function(field) {
    return AutoForm.validateField(id, field)
  })
```
valids return [true, true] even only one the of filed is valid.

This may be related to throttling of validation?

**Comment by Chun-Yang** [comment]
OK, I found the problem:
```
validateField = _.throttle(_validateField, 300);
```
Since there is a throttle, it will return true if we do multiple validations.

**Comment by Chun-Yang** [comment]
We can 
1. provide a way to configure throttleTime globally
2. modify validateField to accept throttleTime
3. do both of them

I can do a PR on this and I prefer the third solution.
Any ideas?

**Comment by aldeed** [comment]
We could add a way to set throttling time, but I think this should also be fixed by figuring out a way to do field-specific throttling.

**Comment by ayal** [comment]
+1 this took me some time to figure out.. for now using _validateField version in my code.

**Comment by ddanna** [comment]
What's the intended work around for this? I want to validate a subset of a form.

**Comment by timmygee** [comment]
+1 for a fix for this issue.

Autoform._validateField seems to have no effect when run. AutoForm.validateField triggers some but not all validation on my form

**Comment by Roshdy** [comment]
Any solution for this problem yet?
