### ISSUE TITLE
HTML in labels

### ISSUE THREAD

**Issue by mankowitz** [Meteor-Community-Packages/meteor-autoform#936]
Is there a way to include HTML in the labels for radio buttons when the form is generated with a quickform? For example

```
{
        label: "method of tracking data",
        type: String,
        autoform: {
            noselect: true,
            options: [
                { value: 1, label: "<strong>option one</strong> Most people like this" },
                { value: 2, label: "<strong>option two</strong> Most people don't like this" },
            ]
        }
    },
```

**Comment by vieko** [comment]
+1

**Comment by tvld** [comment]
+1 :)

**Comment by macroramesh6** [comment]
+1

**Comment by robertdavid010** [comment]
Confirming this is still not supported/needs PR (since it seems a while).

**Comment by kosst** [comment]
A simple solution for putting links inside the label, is to use the `Spacebars.SafeString`-function which doesn't escape the string. It's documented here: 

[http://blazejs.org/api/spacebars.html#SafeString](url)

Example:

```javascript
terms: {
    type: Boolean,
    label() {
        return new Spacebars.SafeString(
            `I accept the <a href="/terms" target="_blank">Terms of Service</a>.`,
        );
    },
},
```

If the link/label is dynamically generated, make sure it's from a trusted source and properly escaped, so it isn't malicious.

**Comment by nasuke0302** [comment]
@kosst Hi,  your solution was a dream but did not work for me, it just renders the "Terms" as the label.
Please help

**Comment by nasuke0302** [comment]
No wait, it works but slightly different:
`terms: {
    type: Boolean,
    label: new Spacebars.SafeString(`I accept the <a href="/terms" target="_blank">Terms of Service</a>.);
},
`

Cool

**Comment by nasuke0302** [comment]
No wait, it works but slightly different, instead of a method, declare the label as property like this:

`terms: {`
    `label: new Spacebars.SafeString('<a>Terms of Service</a>')`
`}`

very nice
