### ISSUE TITLE
how to custom array field with table template?

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-autoform#944]
I have array field like this in schema:

``` js
contact: {
        type: Array,
        label: "Contact"
    },
    'contact.$': {
        type: Object
    },
    'contact.$.address': {
        type: String
    },
    'contact.$.phone': {
        type: String
    }
```

The result in table style

<pre>
Address           |              Phone       |            Action
-----------------------------------------------------------------
##########        |     ###########          |           -
-----------------------------------------------------------------
##########        |     ###########          |           -
-----------------------------------------------------------------
##########        |     ###########          |           -
-----------------------------------------------------------------
                                                          +
</pre>

please help me to custom template.

**Comment by elGusto** [comment]
You should check out this repo https://github.com/aldeed/meteor-tabular

It has many nice features.

**Comment by yuomtheara** [comment]
Thanks for your reply, but `tabular` is list view.
I need add more of dynamic input in array fields in `autoform` and `schema`.

**Comment by elGusto** [comment]
Sorry for not re'ading correctly the question.

Then something along the lines of this should get you what you want ?:


```
<template name="tableTest">
	{{#autoForm schema="testSchema" type="insert" id="testTableForm"}}
	<table class="table">
	<thead>
	<tr>
		<th>#</th>
		<th>adress</th>
		<th>phone</th>
	</tr>
	</thead>
	<tbody>
		{{#afEachArrayItem name="contact" minCount=this.atts.minCount maxCount=this.atts.maxCount}}

		<tr>
			<th>
					{{#if afArrayFieldHasMoreThanMinimum name="contact" minCount=0 maxCount=''}}
					<button type="button" class="btn btn-primary autoform-remove-item"><span class="glyphicon glyphicon-minus"></span></button>
					{{/if}}
				</th>
					{{> customObjectField name="contact" label=false options=afOptionsFromSchema}}
		</tr>
		{{/afEachArrayItem}}
		{{#if afArrayFieldHasLessThanMaximum name="contact" minCount=0 maxCount=''}}
		<tr>
		<th>
			<button type="button" class="btn btn-primary autoform-add-item" data-autoform-field="contact" data-autoform-minCount="{{this.atts.minCount}}" data-autoform-maxCount="{{this.atts.maxCount}}"><span class="glyphicon glyphicon-plus"></span></button>
			</th>
		</tr>
		{{/if}}
	</tbody>
	</table>
	{{/autoForm}}
</template>

<template name="customObjectField">
	<th><input type="text"></th>
	<th><input type="text"></th>
</template>
```

**Comment by yuomtheara** [comment]
Very thanks, I will try, and reply you.

**Comment by yuomtheara** [comment]
Now I tried, but have problem with validate on `customObjectField`
```js
<template name="customObjectField">
    <th><input type="text"></th>
    <th><input type="text"></th>
</template>
```
I want to use `{{> afQuickField name=address}}`, ...

**Comment by yuomtheara** [comment]
Please help me................

**Comment by lgertel** [comment]
@thearabbit did you have the solution?

**Comment by thearabbit** [comment]
Yes, It work fine.
But have problem with `select2`, when I click add more row the select2 is clear all.
