### ISSUE TITLE
Dependable or cascading selects

### ISSUE THREAD

**Issue by lobosan** [Meteor-Community-Packages/meteor-autoform#945]
Hi everyone, how can I implement 3 dependent selects?
Here is an example of what I need to achieve http://www.ajaxray.com/Examples/depend.html
Thanks in advance for any help

**Comment by sturoid** [comment]
Hi @lobosan. I did this with two checkboxes but it would be the same thing to add another one I imagine. You can use Autoform.getFieldValue to get the previously selected value, then change the options in the next select box based on that. So something like this:

```
   officeId:
      type: String
      label: 'Office'
      autoform:
         options: -> _.map Offices.find().fetch(), (office)-> { label: office.name, value: office._id }
   clientId:
      type: String
      label: 'Client'
      autoform:
         options: ->
            selectedOffice = AutoForm.getFieldValue('officeId')
            if(selectedOffice)
               _.map Clients.find({$where: "this.officeId == '#{selectedOffice}'"}).fetch(), (client)->
                  { label: client.name, value: client._id }
            else
              _.map Clients.find().fetch(), (client)-> { label: client.name, value: client._id }

```

**Comment by lobosan** [comment]
Hi @sturoid. Thank you very much for your reply. The way I solved it was very similar. However for the third select to return the selected value once the first select is updated I had to use JQuery. This might help to someone in need of something similar. But if there is a better way to do it please let me know. Cheers

```javascript
Organizaciones = new Mongo.Collection('organizaciones');

Organizaciones.attachSchema(new SimpleSchema({
    provincia: {
        type: String,
        label: 'Provincia',
        autoform: {
            type: 'select',
            firstOption: '',
            options: function () {
                return DPA.find({grupo: 'Provincia'}).map(function (dpa) {
                    return {label: dpa.descripcion, value: dpa.codigo};
                });
            }
        }
    },
    canton: {
        type: String,
        label: 'Cantón',
        autoform: {
            type: 'select',
            firstOption: '',
            options: function () {
                var codigoProvincia = AutoForm.getFieldValue('provincia');
                var cantones = new RegExp('^' + codigoProvincia + '[\\d]{2}$');
                return DPA.find({codigo: {$regex: cantones}}).map(function (dpa) {
                    return {label: dpa.descripcion, value: dpa.codigo};
                });
            }
        }
    },
    parroquia: {
        type: String,
        label: 'Parroquia',
        autoform: {
            type: 'select',
            firstOption: '',
            options: function () {
                $('#provincia').change(function() {
                    $('#parroquia option[value!=""]').remove();
                });
                var codigoCanton = AutoForm.getFieldValue('canton');
                var parroquias = new RegExp('^' + codigoCanton + '[\\d]{2}$');
                return DPA.find({codigo: {$regex: parroquias}}).map(function (dpa) {
                    return {label: dpa.descripcion, value: dpa.codigo};
                });
            }
        }
    }
}));
```

**Comment by fuzzyshark** [comment]
Hi @sturoid 
I get the logic of what you mentioned. What i don't get is how to do this : 
 _.map Offices.find().fetch(), (office)

Does it work with the default js file with autoform or do i need to do something with routes?

**Comment by sturoid** [comment]
@fuzzyshark I was using lodash.js to do the _.map function. The rest should work with everything else being default.

**Comment by tuxbear** [comment]
Any idea how do do this inside a "sub schema" ? I have a list of options, in whitch I need cascasding drop downs.

This approach seems to not work, as I am unable to get the value of the first select box. It is inside an array in the form, so I get a name like attributes.0.defaultOption, and I need to populate the second selectbox based on attributes.0.attributeId

Any ideas?
