### ISSUE TITLE
autosave bug

### ISSUE THREAD

**Issue by partus** [Meteor-Community-Packages/meteor-autoform#950]
if a field of form with autosave  is set to "some value" (autosave is triggered here),   then if  the document is change to another document and the same field is set to the same value ("some value")  then the second document is not autosaved.

this is caused by https://github.com/aldeed/meteor-autoform/blob/3f219adaf59b342e9bb8e22915af1af31aa3e0d2/autoform-events.js lines 391-393 where the autosave is not triggered without checking if the document _id is changed

**Comment by lgandecki** [comment]
+1 
Definitely a bug. We've had to work around this to force the autosave on the field change event.

**Comment by allanlundhansen** [comment]
+1
