### ISSUE TITLE
Question: Template.instance() for Custom Types

### ISSUE THREAD

**Issue by boustanihani** [Meteor-Community-Packages/meteor-autoform#964]
Hi, is it possible to access the `Template.instance()` inside `valueOut` & `valueIn` when creating custom input types ??

I am building a custom input type for "chips"
(Similar to: https://material.angularjs.org/#/demo/material.components.chips)

I would like to store my value as a string array inside a `ReacitveVar` in my `Template.instance()` and use the `ReacitveVar` to later return the `valueOut` (instead of parsing the dom) ...

**Comment by glesperance** [comment]
+1

**Comment by mengnic** [comment]
+1

**Comment by kainisoft** [comment]
+1

**Comment by jsep** [comment]
+1

**Comment by samybob1** [comment]
:+1:
