### ISSUE TITLE
"Error: template.formValues[fieldName] is undefined

### ISSUE THREAD

**Issue by boustanihani** [Meteor-Community-Packages/meteor-autoform#965]
I am getting `"Error: template.formValues[fieldName] is undefined` on my console without any further information, I tried using `AutoForm.debug();` to try to understand what is happening but sadly this did not help :( 

It seems this error only occurs when using **v5.2.0**, if I downgrade to **v5.1.2** the error disappears...

**Comment by fabienb4** [comment]
See #961.
