### ISSUE TITLE
Form hidden fields not rendering defaultValue and not saving

### ISSUE THREAD

**Issue by mchan75** [Meteor-Community-Packages/meteor-autoform#975]
I have two hidden fields in my autoform Schema defined as shown below. I wish to save those two fields with other fields while not showing them to the app user. But I noticed from the autoform rendered html that the two hidden fields have no value, also they don't save with other fields to DB. Not sure what I might be missing / wrong here? Thanks for your help

```
  Invoice = new SimpleSchema({
    clientid: {
      type: String,
      optional: true
    },
    total: {
      type: String,
      label: 'Total Amount',
      optional: true
    },
    tax: {
      type: String,
      label: 'Taxes',
      optional: true
    },
    category: {
      type: String,              
      optional: true,
      autoform: {
        type: "hidden",                
        label: false
      },
      defaultValue: 'Test Category'
    }
  });


  {{> quickForm id="invoiceForm" buttonContent="Insert" buttonClasses="btn btn-primary btn-sm" schema=Invoice type="method" meteormethod="saveInvoice"}}
```

**Comment by sylwekg** [comment]
How did you solve it ? I am facing the same problem

**Comment by Diptyajit1994** [comment]
@sylwekg Just add this two line of codes on top of your js file 
import SimpleSchema from 'simpl-schema';
SimpleSchema.extendOptions(['autoform']);

I hope this will solve your issue
