### ISSUE TITLE
Use Two Different Collection in One Form

### ISSUE THREAD

**Issue by himadrighosh13** [Meteor-Community-Packages/meteor-autoform#978]
I made one form using autoForm & collection2 package in meteor. I want to add one dropdown field to that form which option is populate based on another collection i have. can i do that way?

Any advice...

**Comment by sturoid** [comment]
You can do that from the schema like this:

```
@Clients = new Meteor.Collection('clients')
@Offices = new Meteor.Collection('offices')

Schema.Client = new SimpleSchema
   officeId:
      type: String
      label: 'Office'
      autoform:
         options: ->
             _.map Offices.find().fetch(), (office)->
                { label: office.name, value: office._id }

```

**Comment by himadrighosh13** [comment]
In this case publish-subscribe technique should be there between client-server. But i not using that technique because of some reason. Every time i need back-end data, i am making call server using "Meteor.call(..)". So here if i do "Offices.find()" then getting "undefined". then i tried get option using helper as per autoform document and it is working fine. But i want to do it inside SimpleSchema! Is there any way...
