### ISSUE TITLE
afFieldIsValid method

### ISSUE THREAD

**Issue by vladshcherbin** [Meteor-Community-Packages/meteor-autoform#980]
Hello, when we have validation keyup or blur, we can have the error state class.

Is there a way to add a class after value is validated and has no errors (for example to make it green).

Is it possible?

**Comment by timmygee** [comment]
You could perhaps do this using a custom template for your field. You can then use the template context to add a "validated" class if the conditions are met.

See https://github.com/aldeed/meteor-autoform/#creating-a-custom-template
