### ISSUE TITLE
Using AutoForm with GroundDB to handle forms when offline

### ISSUE THREAD

**Issue by TravisDart** [Meteor-Community-Packages/meteor-autoform#984]
I couldn't find where anyone had posted a full solution for using AutoForm + GroundDB to make a web application that worked with intermittent network access. But, starting with the hint from #223, [this blog post](https://blog.groupbuddies.com/posts/45-offline-web-apps-with-meteor), and [this section from the docs](https://github.com/aldeed/meteor-autoform#normal), I've come up with a working solution:

Template:

```
{{#autoForm collection="Registrations" id="insertRegistrationForm" validation="submit" fields="first_name,last_name,zipcode,email_address,owns_business,plan_to_start_business,essay,over18" }}
```

JavaScript:

```
AutoForm.hooks({
    insertRegistrationForm: {
        onSubmit: function (insertDoc, updateDoc, currentDoc) {
            Registrations.insert(insertDoc);
            this.done();
            Router.go('successfulInsertRegistration');
            return false;
        }
    }
});
```

Validation still works, and form submissions made offline will sync to the server when the network comes back online.

FYI.

**Comment by jtmcmc** [comment]
just to clarify. In this case you've made the collection "Registrations" a grounddb Ground.Collection right?

**Comment by TravisDart** [comment]
Er, yes. You are correct.

The post above implicitly defines a few variables:

* The collection (`Registrations`)
* Fields in the collection (in the fields attribute of the autoForm template tag)
* The form name (`insertRegistrationForm`)
* The route for the success page (`successfulInsertRegistration`)

**Comment by AnthonyAstige** [comment]
I've started a package for this at https://github.com/AnthonyAstige/ground-autoform
