### ISSUE TITLE
Vanilla Install Not Working Due to Collection "Not in Window Scope"

### ISSUE THREAD

**Issue by ppedrazzi** [Meteor-Community-Packages/meteor-autoform#986]
For testing, I created a vanilla meteor app with the books demo example (https://atmospherejs.com/aldeed/autoform).

Oddly, I receive the error about window scope.  

Here are the only packages running:

aldeed:collection2  2.3.3  Automatic validation of insert and update operations on...
autopublish         1.0.3  Publish the entire database to all clients
bootstrap           1.0.1  Front-end framework from Twitter
coffeescript        1.0.6  Javascript dialect with fewer braces and semicolons
insecure            1.0.3  Allow all database writes by default
meteor-platform     1.2.2  Include a standard set of Meteor packages in your app

**Comment by ppedrazzi** [comment]
Here is the coffee file: https://gist.github.com/ppedrazzi/45e7d7ec3eca393338aa

Here is the HTML file: https://gist.github.com/ppedrazzi/fc78da98f2327e086671

**Comment by ppedrazzi** [comment]
Been researching this more.  It seems to be a global variable issue with CoffeeScript.

**Comment by c316** [comment]
+1 

I'm having the same issue, but I'm not using CoffeeScript

**Comment by c316** [comment]
@ppedrazzi Actually my issue was that I only had the schema attached on the server side. Once I moved that file to the both directory or into the root directory it worked fine.

**Comment by DylanKojiCheslin** [comment]
+ 1

@c316 could you post a gist of the working version that you have?
