### ISSUE TITLE
Empty Autoform, the $unset operator, and nested fields

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#992]
I'm running into a bit of an edge case. My user schema stores some data on a nested `telescope` object:

``` js
{
  _id: "123xyz",
  telescope: {
    email: "foo@bar.com"
  }
}
```

I am then using Autoform to generate a `meteormethod` form for that `telescope.email` field. So far so good. 

The problem happens when the email field is left empty. Here's the modifier that is passed on to the method:

``` js
{
  $unset: {
    telescope: ""
  }
}
```

Now passing an `$unset` when a field is left empty is a nice feature. But the problem here is that it's trying to unset `telescope`, instead of `telescope.email`. That doesn't seem right?

**Comment by PhilippSpo** [comment]
+1 experiencing the same here

**Comment by oliroy** [comment]
+1 same issue.

**Comment by serkandurusoy** [comment]
This is even more clear if you are trying to unset a nested field that is not being unset by autoform on the parent level. for example if you want to unset `b`  from {top: {a:'b', b:'b' }} in its autovalue, it is not getting unset, ending up in the persisted document!

**Comment by jlmbaka** [comment]
Any idea as to when this might be resolved? Any possible workaround?

**Comment by mehrdadarvin** [comment]
Ran into the same issue. Not the best workaround but this does the job.
```javascript
formToModifier: function(modifier) {
  if (_.has(modifier, "$unset.telescope")) {
    _.unset(modifier, "$unset.telescope");
    _.set(modifier, "$unset.telescope.email", "");
  }
  return modifier;
}
```
