### ISSUE TITLE
Making fields required in *some* forms

### ISSUE THREAD

**Issue by SachaG** [Meteor-Community-Packages/meteor-autoform#993]
I know how you can declare a field as required through SimpleSchema (`optional: false`). But I was wondering if there's any way to mark fields as required only in the context of a _specific_ form?

**Comment by mandreko** [comment]
I'm trying to do something similar, and I have a feeling it has to do with Validation Contexts, but I haven't yet figured it out.

**Comment by SachaG** [comment]
I ended up creating a new, separate `required` property and redirecting users to a form until all fields with `required: true` were filled out.
