### ISSUE TITLE
AutoForm doesn't have clear validation errors for form.

### ISSUE THREAD

**Issue by Mateusz-Naturaily** [Meteor-Community-Packages/meteor-autoform#999]
Hi,

The problem I'm having right now is not being able to clear all errors for my form.
Why am I having this issue?
Well mainly because I have a "clear all" option in my form (which is unchecking all select checkboxes, and whole form contains only checkboxes). Additionally my form looks like this:

``` html
{{#autoForm schema='HandsFilterSchema' id='handsFilters' resetOnSuccess=false doc=handsFiltersDefaultDoc}}
```

handsFiltersDefaultDoc is by default checking all checkboxes in form. This is why  AutoForm.resetForm('handsFilters') is completely pointless in this case.

So now I managed easily enough (or so I thought) to create a workaround for my problem, manual clearing of errors in my AutoForm form:

``` javascript
  'click #clear-form': (e) ->
    e.stopPropagation()
    $('#handsFilters .help-block').html("")
    $('#handsFilters *').removeClass('has-error')
    $('#dropdown-recent-hands input:checked').prop('checked',false)
```

Beautiful right? Not quite, because even though initially it is clearing all errors and removing 'has-error' class, if I try to submit my form once again (and expecting errors to show again since all checkboxes are unchecked) I get this error: 

```
Exception from Tracker recompute function:
debug.js:41 Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Error (native)
    at DOMRange.detach (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:512:24)
    at DOMRange.setMembers (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:471:12)
    at doMaterialize (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2019:22)
    at Object.Tracker.nonreactive (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:593:12)
    at doRender (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2015:17)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1865:18
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1864:29
    at Object.Blaze._withCurrentView (http://localhost:3000/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2197:12)
```

BUT if I use my event code a bit differently, everything works as expected without errors.

``` javascript
  'click #clear-form': (e) ->
    e.stopPropagation()
    $('#handsFilters .help-block').html("A")
    $('#handsFilters *').removeClass('has-error')
    $('#dropdown-recent-hands input:checked').prop('checked',false)
```

Please notice that the only thing I changed is that I no longer completely empty .help-block tag, but instead I change it's content to "A".

Any ideas why is it happening?
And second question, is it possible maybe to implement AutoForm.resetForm with additional attribute which will be doc with values we want to have in our form inputs? or maybe create new class function AutoForm.clearAllValidationErrors(formId) which will clear all validation errors and AutoForm.clearValidationError(formId, field) which will clear one validation error?

These features could be very helpful if we have "clear all" option in our form which differ from default doc values in our AutoForm.

**Comment by andmitsch** [comment]
Why is it necessary to delete the error message? It should be overwritten next event.
Instead of using `.html()` you may want to try `.empty()`.

'$('#handsFilters *')' is a pretty crude and thus slow selector. There is no need to use * if you exactly know where your targeted content is.

**Comment by Mateusz-Naturaily** [comment]
Hi, sorry for delay,

Using empty() also didn't help, I did it this way and it worked perfectly:
```coffeescript
   'click #clear-form': (e) ->
     e.stopPropagation()
     $('#handsFilters .help-block').css('display','none')
     $('#handsFilters *').removeClass('has-error')
     $('#dropdown-recent-hands input:checked').prop('checked',false)
```
With some additional code:
```coffeescript
  'click #handsFilters button[type="submit"]': (e) ->
    e.stopPropagation()
    $('#handsFilters .help-block').css('display','inline')
```
But during last week we changed specs for this feature at our company and now we no longer need this code. But still it works (provided that anybody will find it useful). But still I believe that AutoForm lacks easy way to clear errors with simple function, especially if you have "clear all" option in your form.
